// Code generated by ent, DO NOT EDIT.

package interestdistribution

import (
	"reserve-interbank-settlement/services/payments-svc/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldContainsFold(FieldID, id))
}

// At applies equality check predicate on the "at" field. It's identical to AtEQ.
func At(v time.Time) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldEQ(FieldAt, v))
}

// RunBy applies equality check predicate on the "run_by" field. It's identical to RunByEQ.
func RunBy(v string) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldEQ(FieldRunBy, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v int64) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldEQ(FieldAmount, v))
}

// Paid applies equality check predicate on the "paid" field. It's identical to PaidEQ.
func Paid(v int64) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldEQ(FieldPaid, v))
}

// Retained applies equality check predicate on the "retained" field. It's identical to RetainedEQ.
func Retained(v int64) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldEQ(FieldRetained, v))
}

// AtEQ applies the EQ predicate on the "at" field.
func AtEQ(v time.Time) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldEQ(FieldAt, v))
}

// AtNEQ applies the NEQ predicate on the "at" field.
func AtNEQ(v time.Time) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldNEQ(FieldAt, v))
}

// AtIn applies the In predicate on the "at" field.
func AtIn(vs ...time.Time) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldIn(FieldAt, vs...))
}

// AtNotIn applies the NotIn predicate on the "at" field.
func AtNotIn(vs ...time.Time) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldNotIn(FieldAt, vs...))
}

// AtGT applies the GT predicate on the "at" field.
func AtGT(v time.Time) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldGT(FieldAt, v))
}

// AtGTE applies the GTE predicate on the "at" field.
func AtGTE(v time.Time) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldGTE(FieldAt, v))
}

// AtLT applies the LT predicate on the "at" field.
func AtLT(v time.Time) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldLT(FieldAt, v))
}

// AtLTE applies the LTE predicate on the "at" field.
func AtLTE(v time.Time) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldLTE(FieldAt, v))
}

// RunByEQ applies the EQ predicate on the "run_by" field.
func RunByEQ(v string) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldEQ(FieldRunBy, v))
}

// RunByNEQ applies the NEQ predicate on the "run_by" field.
func RunByNEQ(v string) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldNEQ(FieldRunBy, v))
}

// RunByIn applies the In predicate on the "run_by" field.
func RunByIn(vs ...string) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldIn(FieldRunBy, vs...))
}

// RunByNotIn applies the NotIn predicate on the "run_by" field.
func RunByNotIn(vs ...string) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldNotIn(FieldRunBy, vs...))
}

// RunByGT applies the GT predicate on the "run_by" field.
func RunByGT(v string) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldGT(FieldRunBy, v))
}

// RunByGTE applies the GTE predicate on the "run_by" field.
func RunByGTE(v string) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldGTE(FieldRunBy, v))
}

// RunByLT applies the LT predicate on the "run_by" field.
func RunByLT(v string) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldLT(FieldRunBy, v))
}

// RunByLTE applies the LTE predicate on the "run_by" field.
func RunByLTE(v string) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldLTE(FieldRunBy, v))
}

// RunByContains applies the Contains predicate on the "run_by" field.
func RunByContains(v string) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldContains(FieldRunBy, v))
}

// RunByHasPrefix applies the HasPrefix predicate on the "run_by" field.
func RunByHasPrefix(v string) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldHasPrefix(FieldRunBy, v))
}

// RunByHasSuffix applies the HasSuffix predicate on the "run_by" field.
func RunByHasSuffix(v string) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldHasSuffix(FieldRunBy, v))
}

// RunByEqualFold applies the EqualFold predicate on the "run_by" field.
func RunByEqualFold(v string) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldEqualFold(FieldRunBy, v))
}

// RunByContainsFold applies the ContainsFold predicate on the "run_by" field.
func RunByContainsFold(v string) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldContainsFold(FieldRunBy, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v int64) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v int64) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...int64) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...int64) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v int64) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v int64) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v int64) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v int64) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldLTE(FieldAmount, v))
}

// PaidEQ applies the EQ predicate on the "paid" field.
func PaidEQ(v int64) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldEQ(FieldPaid, v))
}

// PaidNEQ applies the NEQ predicate on the "paid" field.
func PaidNEQ(v int64) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldNEQ(FieldPaid, v))
}

// PaidIn applies the In predicate on the "paid" field.
func PaidIn(vs ...int64) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldIn(FieldPaid, vs...))
}

// PaidNotIn applies the NotIn predicate on the "paid" field.
func PaidNotIn(vs ...int64) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldNotIn(FieldPaid, vs...))
}

// PaidGT applies the GT predicate on the "paid" field.
func PaidGT(v int64) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldGT(FieldPaid, v))
}

// PaidGTE applies the GTE predicate on the "paid" field.
func PaidGTE(v int64) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldGTE(FieldPaid, v))
}

// PaidLT applies the LT predicate on the "paid" field.
func PaidLT(v int64) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldLT(FieldPaid, v))
}

// PaidLTE applies the LTE predicate on the "paid" field.
func PaidLTE(v int64) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldLTE(FieldPaid, v))
}

// RetainedEQ applies the EQ predicate on the "retained" field.
func RetainedEQ(v int64) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldEQ(FieldRetained, v))
}

// RetainedNEQ applies the NEQ predicate on the "retained" field.
func RetainedNEQ(v int64) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldNEQ(FieldRetained, v))
}

// RetainedIn applies the In predicate on the "retained" field.
func RetainedIn(vs ...int64) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldIn(FieldRetained, vs...))
}

// RetainedNotIn applies the NotIn predicate on the "retained" field.
func RetainedNotIn(vs ...int64) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldNotIn(FieldRetained, vs...))
}

// RetainedGT applies the GT predicate on the "retained" field.
func RetainedGT(v int64) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldGT(FieldRetained, v))
}

// RetainedGTE applies the GTE predicate on the "retained" field.
func RetainedGTE(v int64) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldGTE(FieldRetained, v))
}

// RetainedLT applies the LT predicate on the "retained" field.
func RetainedLT(v int64) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldLT(FieldRetained, v))
}

// RetainedLTE applies the LTE predicate on the "retained" field.
func RetainedLTE(v int64) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.FieldLTE(FieldRetained, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.InterestDistribution) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.InterestDistribution) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.InterestDistribution) predicate.InterestDistribution {
	return predicate.InterestDistribution(sql.NotPredicates(p))
}
