// Code generated by ent, DO NOT EDIT.

package paymentorder

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the paymentorder type in the database.
	Label = "payment_order"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOrganizationID holds the string denoting the organization_id field in the database.
	FieldOrganizationID = "organization_id"
	// FieldBankID holds the string denoting the bank_id field in the database.
	FieldBankID = "bank_id"
	// FieldFileID holds the string denoting the file_id field in the database.
	FieldFileID = "file_id"
	// FieldIdempotencyKey holds the string denoting the idempotency_key field in the database.
	FieldIdempotencyKey = "idempotency_key"
	// FieldRequestHash holds the string denoting the request_hash field in the database.
	FieldRequestHash = "request_hash"
	// FieldEndToEndID holds the string denoting the end_to_end_id field in the database.
	FieldEndToEndID = "end_to_end_id"
	// FieldUetr holds the string denoting the uetr field in the database.
	FieldUetr = "uetr"
	// FieldDebtorAccount holds the string denoting the debtor_account field in the database.
	FieldDebtorAccount = "debtor_account"
	// FieldCreditorName holds the string denoting the creditor_name field in the database.
	FieldCreditorName = "creditor_name"
	// FieldCreditorRouting holds the string denoting the creditor_routing field in the database.
	FieldCreditorRouting = "creditor_routing"
	// FieldCreditorAccount holds the string denoting the creditor_account field in the database.
	FieldCreditorAccount = "creditor_account"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldPriority holds the string denoting the priority field in the database.
	FieldPriority = "priority"
	// FieldRemittance holds the string denoting the remittance field in the database.
	FieldRemittance = "remittance"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldIsoStatus holds the string denoting the iso_status field in the database.
	FieldIsoStatus = "iso_status"
	// FieldReasonCode holds the string denoting the reason_code field in the database.
	FieldReasonCode = "reason_code"
	// FieldRoute holds the string denoting the route field in the database.
	FieldRoute = "route"
	// FieldRouteNote holds the string denoting the route_note field in the database.
	FieldRouteNote = "route_note"
	// FieldPayeeAccountStatus holds the string denoting the payee_account_status field in the database.
	FieldPayeeAccountStatus = "payee_account_status"
	// FieldPayeeNameMatch holds the string denoting the payee_name_match field in the database.
	FieldPayeeNameMatch = "payee_name_match"
	// FieldPayeeRegisteredName holds the string denoting the payee_registered_name field in the database.
	FieldPayeeRegisteredName = "payee_registered_name"
	// FieldApprovalsRequired holds the string denoting the approvals_required field in the database.
	FieldApprovalsRequired = "approvals_required"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldSettledAt holds the string denoting the settled_at field in the database.
	FieldSettledAt = "settled_at"
	// FieldOfacReportDue holds the string denoting the ofac_report_due field in the database.
	FieldOfacReportDue = "ofac_report_due"
	// FieldSanctionsMatch holds the string denoting the sanctions_match field in the database.
	FieldSanctionsMatch = "sanctions_match"
	// FieldPaymentRef holds the string denoting the payment_ref field in the database.
	FieldPaymentRef = "payment_ref"
	// FieldObligationRef holds the string denoting the obligation_ref field in the database.
	FieldObligationRef = "obligation_ref"
	// FieldTokenized holds the string denoting the tokenized field in the database.
	FieldTokenized = "tokenized"
	// FieldReleased holds the string denoting the released field in the database.
	FieldReleased = "released"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// EdgeEvents holds the string denoting the events edge name in mutations.
	EdgeEvents = "events"
	// EdgeApprovals holds the string denoting the approvals edge name in mutations.
	EdgeApprovals = "approvals"
	// Table holds the table name of the paymentorder in the database.
	Table = "payment_orders"
	// EventsTable is the table that holds the events relation/edge.
	EventsTable = "order_events"
	// EventsInverseTable is the table name for the OrderEvent entity.
	// It exists in this package in order to avoid circular dependency with the "orderevent" package.
	EventsInverseTable = "order_events"
	// EventsColumn is the table column denoting the events relation/edge.
	EventsColumn = "order_id"
	// ApprovalsTable is the table that holds the approvals relation/edge.
	ApprovalsTable = "approvals"
	// ApprovalsInverseTable is the table name for the Approval entity.
	// It exists in this package in order to avoid circular dependency with the "approval" package.
	ApprovalsInverseTable = "approvals"
	// ApprovalsColumn is the table column denoting the approvals relation/edge.
	ApprovalsColumn = "order_id"
)

// Columns holds all SQL columns for paymentorder fields.
var Columns = []string{
	FieldID,
	FieldOrganizationID,
	FieldBankID,
	FieldFileID,
	FieldIdempotencyKey,
	FieldRequestHash,
	FieldEndToEndID,
	FieldUetr,
	FieldDebtorAccount,
	FieldCreditorName,
	FieldCreditorRouting,
	FieldCreditorAccount,
	FieldAmount,
	FieldPriority,
	FieldRemittance,
	FieldStatus,
	FieldIsoStatus,
	FieldReasonCode,
	FieldRoute,
	FieldRouteNote,
	FieldPayeeAccountStatus,
	FieldPayeeNameMatch,
	FieldPayeeRegisteredName,
	FieldApprovalsRequired,
	FieldCreatedBy,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldSettledAt,
	FieldOfacReportDue,
	FieldSanctionsMatch,
	FieldPaymentRef,
	FieldObligationRef,
	FieldTokenized,
	FieldReleased,
	FieldVersion,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// OrganizationIDValidator is a validator for the "organization_id" field. It is called by the builders before save.
	OrganizationIDValidator func(string) error
	// BankIDValidator is a validator for the "bank_id" field. It is called by the builders before save.
	BankIDValidator func(string) error
	// EndToEndIDValidator is a validator for the "end_to_end_id" field. It is called by the builders before save.
	EndToEndIDValidator func(string) error
	// UetrValidator is a validator for the "uetr" field. It is called by the builders before save.
	UetrValidator func(string) error
	// DebtorAccountValidator is a validator for the "debtor_account" field. It is called by the builders before save.
	DebtorAccountValidator func(string) error
	// CreditorNameValidator is a validator for the "creditor_name" field. It is called by the builders before save.
	CreditorNameValidator func(string) error
	// CreditorRoutingValidator is a validator for the "creditor_routing" field. It is called by the builders before save.
	CreditorRoutingValidator func(string) error
	// CreditorAccountValidator is a validator for the "creditor_account" field. It is called by the builders before save.
	CreditorAccountValidator func(string) error
	// AmountValidator is a validator for the "amount" field. It is called by the builders before save.
	AmountValidator func(int64) error
	// DefaultRemittance holds the default value on creation for the "remittance" field.
	DefaultRemittance string
	// DefaultReasonCode holds the default value on creation for the "reason_code" field.
	DefaultReasonCode string
	// DefaultRoute holds the default value on creation for the "route" field.
	DefaultRoute string
	// DefaultRouteNote holds the default value on creation for the "route_note" field.
	DefaultRouteNote string
	// DefaultPayeeRegisteredName holds the default value on creation for the "payee_registered_name" field.
	DefaultPayeeRegisteredName string
	// DefaultSanctionsMatch holds the default value on creation for the "sanctions_match" field.
	DefaultSanctionsMatch string
	// DefaultPaymentRef holds the default value on creation for the "payment_ref" field.
	DefaultPaymentRef string
	// DefaultObligationRef holds the default value on creation for the "obligation_ref" field.
	DefaultObligationRef string
	// DefaultTokenized holds the default value on creation for the "tokenized" field.
	DefaultTokenized bool
	// DefaultReleased holds the default value on creation for the "released" field.
	DefaultReleased bool
	// DefaultVersion holds the default value on creation for the "version" field.
	DefaultVersion int
)

// OrderOption defines the ordering options for the PaymentOrder queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByOrganizationID orders the results by the organization_id field.
func ByOrganizationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrganizationID, opts...).ToFunc()
}

// ByBankID orders the results by the bank_id field.
func ByBankID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBankID, opts...).ToFunc()
}

// ByFileID orders the results by the file_id field.
func ByFileID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFileID, opts...).ToFunc()
}

// ByIdempotencyKey orders the results by the idempotency_key field.
func ByIdempotencyKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdempotencyKey, opts...).ToFunc()
}

// ByRequestHash orders the results by the request_hash field.
func ByRequestHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestHash, opts...).ToFunc()
}

// ByEndToEndID orders the results by the end_to_end_id field.
func ByEndToEndID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndToEndID, opts...).ToFunc()
}

// ByUetr orders the results by the uetr field.
func ByUetr(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUetr, opts...).ToFunc()
}

// ByDebtorAccount orders the results by the debtor_account field.
func ByDebtorAccount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDebtorAccount, opts...).ToFunc()
}

// ByCreditorName orders the results by the creditor_name field.
func ByCreditorName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreditorName, opts...).ToFunc()
}

// ByCreditorRouting orders the results by the creditor_routing field.
func ByCreditorRouting(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreditorRouting, opts...).ToFunc()
}

// ByCreditorAccount orders the results by the creditor_account field.
func ByCreditorAccount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreditorAccount, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByPriority orders the results by the priority field.
func ByPriority(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriority, opts...).ToFunc()
}

// ByRemittance orders the results by the remittance field.
func ByRemittance(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemittance, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByIsoStatus orders the results by the iso_status field.
func ByIsoStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsoStatus, opts...).ToFunc()
}

// ByReasonCode orders the results by the reason_code field.
func ByReasonCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReasonCode, opts...).ToFunc()
}

// ByRoute orders the results by the route field.
func ByRoute(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRoute, opts...).ToFunc()
}

// ByRouteNote orders the results by the route_note field.
func ByRouteNote(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRouteNote, opts...).ToFunc()
}

// ByPayeeAccountStatus orders the results by the payee_account_status field.
func ByPayeeAccountStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPayeeAccountStatus, opts...).ToFunc()
}

// ByPayeeNameMatch orders the results by the payee_name_match field.
func ByPayeeNameMatch(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPayeeNameMatch, opts...).ToFunc()
}

// ByPayeeRegisteredName orders the results by the payee_registered_name field.
func ByPayeeRegisteredName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPayeeRegisteredName, opts...).ToFunc()
}

// ByApprovalsRequired orders the results by the approvals_required field.
func ByApprovalsRequired(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldApprovalsRequired, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// BySettledAt orders the results by the settled_at field.
func BySettledAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSettledAt, opts...).ToFunc()
}

// ByOfacReportDue orders the results by the ofac_report_due field.
func ByOfacReportDue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOfacReportDue, opts...).ToFunc()
}

// BySanctionsMatch orders the results by the sanctions_match field.
func BySanctionsMatch(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSanctionsMatch, opts...).ToFunc()
}

// ByPaymentRef orders the results by the payment_ref field.
func ByPaymentRef(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaymentRef, opts...).ToFunc()
}

// ByObligationRef orders the results by the obligation_ref field.
func ByObligationRef(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldObligationRef, opts...).ToFunc()
}

// ByTokenized orders the results by the tokenized field.
func ByTokenized(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokenized, opts...).ToFunc()
}

// ByReleased orders the results by the released field.
func ByReleased(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReleased, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByEventsCount orders the results by events count.
func ByEventsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newEventsStep(), opts...)
	}
}

// ByEvents orders the results by events terms.
func ByEvents(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEventsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByApprovalsCount orders the results by approvals count.
func ByApprovalsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newApprovalsStep(), opts...)
	}
}

// ByApprovals orders the results by approvals terms.
func ByApprovals(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newApprovalsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newEventsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EventsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, EventsTable, EventsColumn),
	)
}
func newApprovalsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ApprovalsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ApprovalsTable, ApprovalsColumn),
	)
}
