// Code generated by ent, DO NOT EDIT.

package defund

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the defund type in the database.
	Label = "defund"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBankID holds the string denoting the bank_id field in the database.
	FieldBankID = "bank_id"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldRequestedByID holds the string denoting the requested_by_id field in the database.
	FieldRequestedByID = "requested_by_id"
	// FieldRequestedBy holds the string denoting the requested_by field in the database.
	FieldRequestedBy = "requested_by"
	// FieldApprovedBy holds the string denoting the approved_by field in the database.
	FieldApprovedBy = "approved_by"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldLedgerRef holds the string denoting the ledger_ref field in the database.
	FieldLedgerRef = "ledger_ref"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the defund in the database.
	Table = "defunds"
)

// Columns holds all SQL columns for defund fields.
var Columns = []string{
	FieldID,
	FieldBankID,
	FieldAmount,
	FieldRequestedByID,
	FieldRequestedBy,
	FieldApprovedBy,
	FieldStatus,
	FieldLedgerRef,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// AmountValidator is a validator for the "amount" field. It is called by the builders before save.
	AmountValidator func(int64) error
	// DefaultApprovedBy holds the default value on creation for the "approved_by" field.
	DefaultApprovedBy string
)

// OrderOption defines the ordering options for the Defund queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByBankID orders the results by the bank_id field.
func ByBankID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBankID, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByRequestedByID orders the results by the requested_by_id field.
func ByRequestedByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestedByID, opts...).ToFunc()
}

// ByRequestedBy orders the results by the requested_by field.
func ByRequestedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestedBy, opts...).ToFunc()
}

// ByApprovedBy orders the results by the approved_by field.
func ByApprovedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldApprovedBy, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByLedgerRef orders the results by the ledger_ref field.
func ByLedgerRef(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLedgerRef, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
