// Code generated by ent, DO NOT EDIT.

package defund

import (
	"reserve-interbank-settlement/services/payments-svc/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Defund {
	return predicate.Defund(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Defund {
	return predicate.Defund(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Defund {
	return predicate.Defund(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Defund {
	return predicate.Defund(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Defund {
	return predicate.Defund(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Defund {
	return predicate.Defund(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Defund {
	return predicate.Defund(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Defund {
	return predicate.Defund(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Defund {
	return predicate.Defund(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Defund {
	return predicate.Defund(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Defund {
	return predicate.Defund(sql.FieldContainsFold(FieldID, id))
}

// BankID applies equality check predicate on the "bank_id" field. It's identical to BankIDEQ.
func BankID(v string) predicate.Defund {
	return predicate.Defund(sql.FieldEQ(FieldBankID, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v int64) predicate.Defund {
	return predicate.Defund(sql.FieldEQ(FieldAmount, v))
}

// RequestedByID applies equality check predicate on the "requested_by_id" field. It's identical to RequestedByIDEQ.
func RequestedByID(v string) predicate.Defund {
	return predicate.Defund(sql.FieldEQ(FieldRequestedByID, v))
}

// RequestedBy applies equality check predicate on the "requested_by" field. It's identical to RequestedByEQ.
func RequestedBy(v string) predicate.Defund {
	return predicate.Defund(sql.FieldEQ(FieldRequestedBy, v))
}

// ApprovedBy applies equality check predicate on the "approved_by" field. It's identical to ApprovedByEQ.
func ApprovedBy(v string) predicate.Defund {
	return predicate.Defund(sql.FieldEQ(FieldApprovedBy, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Defund {
	return predicate.Defund(sql.FieldEQ(FieldStatus, v))
}

// LedgerRef applies equality check predicate on the "ledger_ref" field. It's identical to LedgerRefEQ.
func LedgerRef(v string) predicate.Defund {
	return predicate.Defund(sql.FieldEQ(FieldLedgerRef, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Defund {
	return predicate.Defund(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Defund {
	return predicate.Defund(sql.FieldEQ(FieldUpdatedAt, v))
}

// BankIDEQ applies the EQ predicate on the "bank_id" field.
func BankIDEQ(v string) predicate.Defund {
	return predicate.Defund(sql.FieldEQ(FieldBankID, v))
}

// BankIDNEQ applies the NEQ predicate on the "bank_id" field.
func BankIDNEQ(v string) predicate.Defund {
	return predicate.Defund(sql.FieldNEQ(FieldBankID, v))
}

// BankIDIn applies the In predicate on the "bank_id" field.
func BankIDIn(vs ...string) predicate.Defund {
	return predicate.Defund(sql.FieldIn(FieldBankID, vs...))
}

// BankIDNotIn applies the NotIn predicate on the "bank_id" field.
func BankIDNotIn(vs ...string) predicate.Defund {
	return predicate.Defund(sql.FieldNotIn(FieldBankID, vs...))
}

// BankIDGT applies the GT predicate on the "bank_id" field.
func BankIDGT(v string) predicate.Defund {
	return predicate.Defund(sql.FieldGT(FieldBankID, v))
}

// BankIDGTE applies the GTE predicate on the "bank_id" field.
func BankIDGTE(v string) predicate.Defund {
	return predicate.Defund(sql.FieldGTE(FieldBankID, v))
}

// BankIDLT applies the LT predicate on the "bank_id" field.
func BankIDLT(v string) predicate.Defund {
	return predicate.Defund(sql.FieldLT(FieldBankID, v))
}

// BankIDLTE applies the LTE predicate on the "bank_id" field.
func BankIDLTE(v string) predicate.Defund {
	return predicate.Defund(sql.FieldLTE(FieldBankID, v))
}

// BankIDContains applies the Contains predicate on the "bank_id" field.
func BankIDContains(v string) predicate.Defund {
	return predicate.Defund(sql.FieldContains(FieldBankID, v))
}

// BankIDHasPrefix applies the HasPrefix predicate on the "bank_id" field.
func BankIDHasPrefix(v string) predicate.Defund {
	return predicate.Defund(sql.FieldHasPrefix(FieldBankID, v))
}

// BankIDHasSuffix applies the HasSuffix predicate on the "bank_id" field.
func BankIDHasSuffix(v string) predicate.Defund {
	return predicate.Defund(sql.FieldHasSuffix(FieldBankID, v))
}

// BankIDEqualFold applies the EqualFold predicate on the "bank_id" field.
func BankIDEqualFold(v string) predicate.Defund {
	return predicate.Defund(sql.FieldEqualFold(FieldBankID, v))
}

// BankIDContainsFold applies the ContainsFold predicate on the "bank_id" field.
func BankIDContainsFold(v string) predicate.Defund {
	return predicate.Defund(sql.FieldContainsFold(FieldBankID, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v int64) predicate.Defund {
	return predicate.Defund(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v int64) predicate.Defund {
	return predicate.Defund(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...int64) predicate.Defund {
	return predicate.Defund(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...int64) predicate.Defund {
	return predicate.Defund(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v int64) predicate.Defund {
	return predicate.Defund(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v int64) predicate.Defund {
	return predicate.Defund(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v int64) predicate.Defund {
	return predicate.Defund(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v int64) predicate.Defund {
	return predicate.Defund(sql.FieldLTE(FieldAmount, v))
}

// RequestedByIDEQ applies the EQ predicate on the "requested_by_id" field.
func RequestedByIDEQ(v string) predicate.Defund {
	return predicate.Defund(sql.FieldEQ(FieldRequestedByID, v))
}

// RequestedByIDNEQ applies the NEQ predicate on the "requested_by_id" field.
func RequestedByIDNEQ(v string) predicate.Defund {
	return predicate.Defund(sql.FieldNEQ(FieldRequestedByID, v))
}

// RequestedByIDIn applies the In predicate on the "requested_by_id" field.
func RequestedByIDIn(vs ...string) predicate.Defund {
	return predicate.Defund(sql.FieldIn(FieldRequestedByID, vs...))
}

// RequestedByIDNotIn applies the NotIn predicate on the "requested_by_id" field.
func RequestedByIDNotIn(vs ...string) predicate.Defund {
	return predicate.Defund(sql.FieldNotIn(FieldRequestedByID, vs...))
}

// RequestedByIDGT applies the GT predicate on the "requested_by_id" field.
func RequestedByIDGT(v string) predicate.Defund {
	return predicate.Defund(sql.FieldGT(FieldRequestedByID, v))
}

// RequestedByIDGTE applies the GTE predicate on the "requested_by_id" field.
func RequestedByIDGTE(v string) predicate.Defund {
	return predicate.Defund(sql.FieldGTE(FieldRequestedByID, v))
}

// RequestedByIDLT applies the LT predicate on the "requested_by_id" field.
func RequestedByIDLT(v string) predicate.Defund {
	return predicate.Defund(sql.FieldLT(FieldRequestedByID, v))
}

// RequestedByIDLTE applies the LTE predicate on the "requested_by_id" field.
func RequestedByIDLTE(v string) predicate.Defund {
	return predicate.Defund(sql.FieldLTE(FieldRequestedByID, v))
}

// RequestedByIDContains applies the Contains predicate on the "requested_by_id" field.
func RequestedByIDContains(v string) predicate.Defund {
	return predicate.Defund(sql.FieldContains(FieldRequestedByID, v))
}

// RequestedByIDHasPrefix applies the HasPrefix predicate on the "requested_by_id" field.
func RequestedByIDHasPrefix(v string) predicate.Defund {
	return predicate.Defund(sql.FieldHasPrefix(FieldRequestedByID, v))
}

// RequestedByIDHasSuffix applies the HasSuffix predicate on the "requested_by_id" field.
func RequestedByIDHasSuffix(v string) predicate.Defund {
	return predicate.Defund(sql.FieldHasSuffix(FieldRequestedByID, v))
}

// RequestedByIDEqualFold applies the EqualFold predicate on the "requested_by_id" field.
func RequestedByIDEqualFold(v string) predicate.Defund {
	return predicate.Defund(sql.FieldEqualFold(FieldRequestedByID, v))
}

// RequestedByIDContainsFold applies the ContainsFold predicate on the "requested_by_id" field.
func RequestedByIDContainsFold(v string) predicate.Defund {
	return predicate.Defund(sql.FieldContainsFold(FieldRequestedByID, v))
}

// RequestedByEQ applies the EQ predicate on the "requested_by" field.
func RequestedByEQ(v string) predicate.Defund {
	return predicate.Defund(sql.FieldEQ(FieldRequestedBy, v))
}

// RequestedByNEQ applies the NEQ predicate on the "requested_by" field.
func RequestedByNEQ(v string) predicate.Defund {
	return predicate.Defund(sql.FieldNEQ(FieldRequestedBy, v))
}

// RequestedByIn applies the In predicate on the "requested_by" field.
func RequestedByIn(vs ...string) predicate.Defund {
	return predicate.Defund(sql.FieldIn(FieldRequestedBy, vs...))
}

// RequestedByNotIn applies the NotIn predicate on the "requested_by" field.
func RequestedByNotIn(vs ...string) predicate.Defund {
	return predicate.Defund(sql.FieldNotIn(FieldRequestedBy, vs...))
}

// RequestedByGT applies the GT predicate on the "requested_by" field.
func RequestedByGT(v string) predicate.Defund {
	return predicate.Defund(sql.FieldGT(FieldRequestedBy, v))
}

// RequestedByGTE applies the GTE predicate on the "requested_by" field.
func RequestedByGTE(v string) predicate.Defund {
	return predicate.Defund(sql.FieldGTE(FieldRequestedBy, v))
}

// RequestedByLT applies the LT predicate on the "requested_by" field.
func RequestedByLT(v string) predicate.Defund {
	return predicate.Defund(sql.FieldLT(FieldRequestedBy, v))
}

// RequestedByLTE applies the LTE predicate on the "requested_by" field.
func RequestedByLTE(v string) predicate.Defund {
	return predicate.Defund(sql.FieldLTE(FieldRequestedBy, v))
}

// RequestedByContains applies the Contains predicate on the "requested_by" field.
func RequestedByContains(v string) predicate.Defund {
	return predicate.Defund(sql.FieldContains(FieldRequestedBy, v))
}

// RequestedByHasPrefix applies the HasPrefix predicate on the "requested_by" field.
func RequestedByHasPrefix(v string) predicate.Defund {
	return predicate.Defund(sql.FieldHasPrefix(FieldRequestedBy, v))
}

// RequestedByHasSuffix applies the HasSuffix predicate on the "requested_by" field.
func RequestedByHasSuffix(v string) predicate.Defund {
	return predicate.Defund(sql.FieldHasSuffix(FieldRequestedBy, v))
}

// RequestedByEqualFold applies the EqualFold predicate on the "requested_by" field.
func RequestedByEqualFold(v string) predicate.Defund {
	return predicate.Defund(sql.FieldEqualFold(FieldRequestedBy, v))
}

// RequestedByContainsFold applies the ContainsFold predicate on the "requested_by" field.
func RequestedByContainsFold(v string) predicate.Defund {
	return predicate.Defund(sql.FieldContainsFold(FieldRequestedBy, v))
}

// ApprovedByEQ applies the EQ predicate on the "approved_by" field.
func ApprovedByEQ(v string) predicate.Defund {
	return predicate.Defund(sql.FieldEQ(FieldApprovedBy, v))
}

// ApprovedByNEQ applies the NEQ predicate on the "approved_by" field.
func ApprovedByNEQ(v string) predicate.Defund {
	return predicate.Defund(sql.FieldNEQ(FieldApprovedBy, v))
}

// ApprovedByIn applies the In predicate on the "approved_by" field.
func ApprovedByIn(vs ...string) predicate.Defund {
	return predicate.Defund(sql.FieldIn(FieldApprovedBy, vs...))
}

// ApprovedByNotIn applies the NotIn predicate on the "approved_by" field.
func ApprovedByNotIn(vs ...string) predicate.Defund {
	return predicate.Defund(sql.FieldNotIn(FieldApprovedBy, vs...))
}

// ApprovedByGT applies the GT predicate on the "approved_by" field.
func ApprovedByGT(v string) predicate.Defund {
	return predicate.Defund(sql.FieldGT(FieldApprovedBy, v))
}

// ApprovedByGTE applies the GTE predicate on the "approved_by" field.
func ApprovedByGTE(v string) predicate.Defund {
	return predicate.Defund(sql.FieldGTE(FieldApprovedBy, v))
}

// ApprovedByLT applies the LT predicate on the "approved_by" field.
func ApprovedByLT(v string) predicate.Defund {
	return predicate.Defund(sql.FieldLT(FieldApprovedBy, v))
}

// ApprovedByLTE applies the LTE predicate on the "approved_by" field.
func ApprovedByLTE(v string) predicate.Defund {
	return predicate.Defund(sql.FieldLTE(FieldApprovedBy, v))
}

// ApprovedByContains applies the Contains predicate on the "approved_by" field.
func ApprovedByContains(v string) predicate.Defund {
	return predicate.Defund(sql.FieldContains(FieldApprovedBy, v))
}

// ApprovedByHasPrefix applies the HasPrefix predicate on the "approved_by" field.
func ApprovedByHasPrefix(v string) predicate.Defund {
	return predicate.Defund(sql.FieldHasPrefix(FieldApprovedBy, v))
}

// ApprovedByHasSuffix applies the HasSuffix predicate on the "approved_by" field.
func ApprovedByHasSuffix(v string) predicate.Defund {
	return predicate.Defund(sql.FieldHasSuffix(FieldApprovedBy, v))
}

// ApprovedByEqualFold applies the EqualFold predicate on the "approved_by" field.
func ApprovedByEqualFold(v string) predicate.Defund {
	return predicate.Defund(sql.FieldEqualFold(FieldApprovedBy, v))
}

// ApprovedByContainsFold applies the ContainsFold predicate on the "approved_by" field.
func ApprovedByContainsFold(v string) predicate.Defund {
	return predicate.Defund(sql.FieldContainsFold(FieldApprovedBy, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Defund {
	return predicate.Defund(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Defund {
	return predicate.Defund(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Defund {
	return predicate.Defund(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Defund {
	return predicate.Defund(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Defund {
	return predicate.Defund(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Defund {
	return predicate.Defund(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Defund {
	return predicate.Defund(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Defund {
	return predicate.Defund(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Defund {
	return predicate.Defund(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Defund {
	return predicate.Defund(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Defund {
	return predicate.Defund(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Defund {
	return predicate.Defund(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Defund {
	return predicate.Defund(sql.FieldContainsFold(FieldStatus, v))
}

// LedgerRefEQ applies the EQ predicate on the "ledger_ref" field.
func LedgerRefEQ(v string) predicate.Defund {
	return predicate.Defund(sql.FieldEQ(FieldLedgerRef, v))
}

// LedgerRefNEQ applies the NEQ predicate on the "ledger_ref" field.
func LedgerRefNEQ(v string) predicate.Defund {
	return predicate.Defund(sql.FieldNEQ(FieldLedgerRef, v))
}

// LedgerRefIn applies the In predicate on the "ledger_ref" field.
func LedgerRefIn(vs ...string) predicate.Defund {
	return predicate.Defund(sql.FieldIn(FieldLedgerRef, vs...))
}

// LedgerRefNotIn applies the NotIn predicate on the "ledger_ref" field.
func LedgerRefNotIn(vs ...string) predicate.Defund {
	return predicate.Defund(sql.FieldNotIn(FieldLedgerRef, vs...))
}

// LedgerRefGT applies the GT predicate on the "ledger_ref" field.
func LedgerRefGT(v string) predicate.Defund {
	return predicate.Defund(sql.FieldGT(FieldLedgerRef, v))
}

// LedgerRefGTE applies the GTE predicate on the "ledger_ref" field.
func LedgerRefGTE(v string) predicate.Defund {
	return predicate.Defund(sql.FieldGTE(FieldLedgerRef, v))
}

// LedgerRefLT applies the LT predicate on the "ledger_ref" field.
func LedgerRefLT(v string) predicate.Defund {
	return predicate.Defund(sql.FieldLT(FieldLedgerRef, v))
}

// LedgerRefLTE applies the LTE predicate on the "ledger_ref" field.
func LedgerRefLTE(v string) predicate.Defund {
	return predicate.Defund(sql.FieldLTE(FieldLedgerRef, v))
}

// LedgerRefContains applies the Contains predicate on the "ledger_ref" field.
func LedgerRefContains(v string) predicate.Defund {
	return predicate.Defund(sql.FieldContains(FieldLedgerRef, v))
}

// LedgerRefHasPrefix applies the HasPrefix predicate on the "ledger_ref" field.
func LedgerRefHasPrefix(v string) predicate.Defund {
	return predicate.Defund(sql.FieldHasPrefix(FieldLedgerRef, v))
}

// LedgerRefHasSuffix applies the HasSuffix predicate on the "ledger_ref" field.
func LedgerRefHasSuffix(v string) predicate.Defund {
	return predicate.Defund(sql.FieldHasSuffix(FieldLedgerRef, v))
}

// LedgerRefEqualFold applies the EqualFold predicate on the "ledger_ref" field.
func LedgerRefEqualFold(v string) predicate.Defund {
	return predicate.Defund(sql.FieldEqualFold(FieldLedgerRef, v))
}

// LedgerRefContainsFold applies the ContainsFold predicate on the "ledger_ref" field.
func LedgerRefContainsFold(v string) predicate.Defund {
	return predicate.Defund(sql.FieldContainsFold(FieldLedgerRef, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Defund {
	return predicate.Defund(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Defund {
	return predicate.Defund(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Defund {
	return predicate.Defund(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Defund {
	return predicate.Defund(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Defund {
	return predicate.Defund(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Defund {
	return predicate.Defund(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Defund {
	return predicate.Defund(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Defund {
	return predicate.Defund(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Defund {
	return predicate.Defund(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Defund {
	return predicate.Defund(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Defund {
	return predicate.Defund(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Defund {
	return predicate.Defund(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Defund {
	return predicate.Defund(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Defund {
	return predicate.Defund(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Defund {
	return predicate.Defund(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Defund {
	return predicate.Defund(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Defund) predicate.Defund {
	return predicate.Defund(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Defund) predicate.Defund {
	return predicate.Defund(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Defund) predicate.Defund {
	return predicate.Defund(sql.NotPredicates(p))
}
