// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"reserve-interbank-settlement/services/payments-svc/ent/approval"
	"reserve-interbank-settlement/services/payments-svc/ent/paymentorder"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ApprovalCreate is the builder for creating a Approval entity.
type ApprovalCreate struct {
	config
	mutation *ApprovalMutation
	hooks    []Hook
}

// SetOrderID sets the "order_id" field.
func (ac *ApprovalCreate) SetOrderID(s string) *ApprovalCreate {
	ac.mutation.SetOrderID(s)
	return ac
}

// SetApproverID sets the "approver_id" field.
func (ac *ApprovalCreate) SetApproverID(s string) *ApprovalCreate {
	ac.mutation.SetApproverID(s)
	return ac
}

// SetApproverName sets the "approver_name" field.
func (ac *ApprovalCreate) SetApproverName(s string) *ApprovalCreate {
	ac.mutation.SetApproverName(s)
	return ac
}

// SetAt sets the "at" field.
func (ac *ApprovalCreate) SetAt(t time.Time) *ApprovalCreate {
	ac.mutation.SetAt(t)
	return ac
}

// SetOrder sets the "order" edge to the PaymentOrder entity.
func (ac *ApprovalCreate) SetOrder(p *PaymentOrder) *ApprovalCreate {
	return ac.SetOrderID(p.ID)
}

// Mutation returns the ApprovalMutation object of the builder.
func (ac *ApprovalCreate) Mutation() *ApprovalMutation {
	return ac.mutation
}

// Save creates the Approval in the database.
func (ac *ApprovalCreate) Save(ctx context.Context) (*Approval, error) {
	return withHooks(ctx, ac.sqlSave, ac.mutation, ac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ac *ApprovalCreate) SaveX(ctx context.Context) *Approval {
	v, err := ac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ac *ApprovalCreate) Exec(ctx context.Context) error {
	_, err := ac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ac *ApprovalCreate) ExecX(ctx context.Context) {
	if err := ac.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ac *ApprovalCreate) check() error {
	if _, ok := ac.mutation.OrderID(); !ok {
		return &ValidationError{Name: "order_id", err: errors.New(`ent: missing required field "Approval.order_id"`)}
	}
	if _, ok := ac.mutation.ApproverID(); !ok {
		return &ValidationError{Name: "approver_id", err: errors.New(`ent: missing required field "Approval.approver_id"`)}
	}
	if _, ok := ac.mutation.ApproverName(); !ok {
		return &ValidationError{Name: "approver_name", err: errors.New(`ent: missing required field "Approval.approver_name"`)}
	}
	if _, ok := ac.mutation.At(); !ok {
		return &ValidationError{Name: "at", err: errors.New(`ent: missing required field "Approval.at"`)}
	}
	if len(ac.mutation.OrderIDs()) == 0 {
		return &ValidationError{Name: "order", err: errors.New(`ent: missing required edge "Approval.order"`)}
	}
	return nil
}

func (ac *ApprovalCreate) sqlSave(ctx context.Context) (*Approval, error) {
	if err := ac.check(); err != nil {
		return nil, err
	}
	_node, _spec := ac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	ac.mutation.id = &_node.ID
	ac.mutation.done = true
	return _node, nil
}

func (ac *ApprovalCreate) createSpec() (*Approval, *sqlgraph.CreateSpec) {
	var (
		_node = &Approval{config: ac.config}
		_spec = sqlgraph.NewCreateSpec(approval.Table, sqlgraph.NewFieldSpec(approval.FieldID, field.TypeInt))
	)
	if value, ok := ac.mutation.ApproverID(); ok {
		_spec.SetField(approval.FieldApproverID, field.TypeString, value)
		_node.ApproverID = value
	}
	if value, ok := ac.mutation.ApproverName(); ok {
		_spec.SetField(approval.FieldApproverName, field.TypeString, value)
		_node.ApproverName = value
	}
	if value, ok := ac.mutation.At(); ok {
		_spec.SetField(approval.FieldAt, field.TypeTime, value)
		_node.At = value
	}
	if nodes := ac.mutation.OrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   approval.OrderTable,
			Columns: []string{approval.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OrderID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ApprovalCreateBulk is the builder for creating many Approval entities in bulk.
type ApprovalCreateBulk struct {
	config
	err      error
	builders []*ApprovalCreate
}

// Save creates the Approval entities in the database.
func (acb *ApprovalCreateBulk) Save(ctx context.Context) ([]*Approval, error) {
	if acb.err != nil {
		return nil, acb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(acb.builders))
	nodes := make([]*Approval, len(acb.builders))
	mutators := make([]Mutator, len(acb.builders))
	for i := range acb.builders {
		func(i int, root context.Context) {
			builder := acb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ApprovalMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, acb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, acb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, acb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (acb *ApprovalCreateBulk) SaveX(ctx context.Context) []*Approval {
	v, err := acb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (acb *ApprovalCreateBulk) Exec(ctx context.Context) error {
	_, err := acb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acb *ApprovalCreateBulk) ExecX(ctx context.Context) {
	if err := acb.Exec(ctx); err != nil {
		panic(err)
	}
}
