// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"reserve-interbank-settlement/services/payments-svc/ent/defund"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DefundCreate is the builder for creating a Defund entity.
type DefundCreate struct {
	config
	mutation *DefundMutation
	hooks    []Hook
}

// SetBankID sets the "bank_id" field.
func (dc *DefundCreate) SetBankID(s string) *DefundCreate {
	dc.mutation.SetBankID(s)
	return dc
}

// SetAmount sets the "amount" field.
func (dc *DefundCreate) SetAmount(i int64) *DefundCreate {
	dc.mutation.SetAmount(i)
	return dc
}

// SetRequestedByID sets the "requested_by_id" field.
func (dc *DefundCreate) SetRequestedByID(s string) *DefundCreate {
	dc.mutation.SetRequestedByID(s)
	return dc
}

// SetRequestedBy sets the "requested_by" field.
func (dc *DefundCreate) SetRequestedBy(s string) *DefundCreate {
	dc.mutation.SetRequestedBy(s)
	return dc
}

// SetApprovedBy sets the "approved_by" field.
func (dc *DefundCreate) SetApprovedBy(s string) *DefundCreate {
	dc.mutation.SetApprovedBy(s)
	return dc
}

// SetNillableApprovedBy sets the "approved_by" field if the given value is not nil.
func (dc *DefundCreate) SetNillableApprovedBy(s *string) *DefundCreate {
	if s != nil {
		dc.SetApprovedBy(*s)
	}
	return dc
}

// SetStatus sets the "status" field.
func (dc *DefundCreate) SetStatus(s string) *DefundCreate {
	dc.mutation.SetStatus(s)
	return dc
}

// SetLedgerRef sets the "ledger_ref" field.
func (dc *DefundCreate) SetLedgerRef(s string) *DefundCreate {
	dc.mutation.SetLedgerRef(s)
	return dc
}

// SetCreatedAt sets the "created_at" field.
func (dc *DefundCreate) SetCreatedAt(t time.Time) *DefundCreate {
	dc.mutation.SetCreatedAt(t)
	return dc
}

// SetUpdatedAt sets the "updated_at" field.
func (dc *DefundCreate) SetUpdatedAt(t time.Time) *DefundCreate {
	dc.mutation.SetUpdatedAt(t)
	return dc
}

// SetID sets the "id" field.
func (dc *DefundCreate) SetID(s string) *DefundCreate {
	dc.mutation.SetID(s)
	return dc
}

// Mutation returns the DefundMutation object of the builder.
func (dc *DefundCreate) Mutation() *DefundMutation {
	return dc.mutation
}

// Save creates the Defund in the database.
func (dc *DefundCreate) Save(ctx context.Context) (*Defund, error) {
	dc.defaults()
	return withHooks(ctx, dc.sqlSave, dc.mutation, dc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (dc *DefundCreate) SaveX(ctx context.Context) *Defund {
	v, err := dc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dc *DefundCreate) Exec(ctx context.Context) error {
	_, err := dc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dc *DefundCreate) ExecX(ctx context.Context) {
	if err := dc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (dc *DefundCreate) defaults() {
	if _, ok := dc.mutation.ApprovedBy(); !ok {
		v := defund.DefaultApprovedBy
		dc.mutation.SetApprovedBy(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dc *DefundCreate) check() error {
	if _, ok := dc.mutation.BankID(); !ok {
		return &ValidationError{Name: "bank_id", err: errors.New(`ent: missing required field "Defund.bank_id"`)}
	}
	if _, ok := dc.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "Defund.amount"`)}
	}
	if v, ok := dc.mutation.Amount(); ok {
		if err := defund.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "Defund.amount": %w`, err)}
		}
	}
	if _, ok := dc.mutation.RequestedByID(); !ok {
		return &ValidationError{Name: "requested_by_id", err: errors.New(`ent: missing required field "Defund.requested_by_id"`)}
	}
	if _, ok := dc.mutation.RequestedBy(); !ok {
		return &ValidationError{Name: "requested_by", err: errors.New(`ent: missing required field "Defund.requested_by"`)}
	}
	if _, ok := dc.mutation.ApprovedBy(); !ok {
		return &ValidationError{Name: "approved_by", err: errors.New(`ent: missing required field "Defund.approved_by"`)}
	}
	if _, ok := dc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Defund.status"`)}
	}
	if _, ok := dc.mutation.LedgerRef(); !ok {
		return &ValidationError{Name: "ledger_ref", err: errors.New(`ent: missing required field "Defund.ledger_ref"`)}
	}
	if _, ok := dc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Defund.created_at"`)}
	}
	if _, ok := dc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Defund.updated_at"`)}
	}
	return nil
}

func (dc *DefundCreate) sqlSave(ctx context.Context) (*Defund, error) {
	if err := dc.check(); err != nil {
		return nil, err
	}
	_node, _spec := dc.createSpec()
	if err := sqlgraph.CreateNode(ctx, dc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Defund.ID type: %T", _spec.ID.Value)
		}
	}
	dc.mutation.id = &_node.ID
	dc.mutation.done = true
	return _node, nil
}

func (dc *DefundCreate) createSpec() (*Defund, *sqlgraph.CreateSpec) {
	var (
		_node = &Defund{config: dc.config}
		_spec = sqlgraph.NewCreateSpec(defund.Table, sqlgraph.NewFieldSpec(defund.FieldID, field.TypeString))
	)
	if id, ok := dc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := dc.mutation.BankID(); ok {
		_spec.SetField(defund.FieldBankID, field.TypeString, value)
		_node.BankID = value
	}
	if value, ok := dc.mutation.Amount(); ok {
		_spec.SetField(defund.FieldAmount, field.TypeInt64, value)
		_node.Amount = value
	}
	if value, ok := dc.mutation.RequestedByID(); ok {
		_spec.SetField(defund.FieldRequestedByID, field.TypeString, value)
		_node.RequestedByID = value
	}
	if value, ok := dc.mutation.RequestedBy(); ok {
		_spec.SetField(defund.FieldRequestedBy, field.TypeString, value)
		_node.RequestedBy = value
	}
	if value, ok := dc.mutation.ApprovedBy(); ok {
		_spec.SetField(defund.FieldApprovedBy, field.TypeString, value)
		_node.ApprovedBy = value
	}
	if value, ok := dc.mutation.Status(); ok {
		_spec.SetField(defund.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := dc.mutation.LedgerRef(); ok {
		_spec.SetField(defund.FieldLedgerRef, field.TypeString, value)
		_node.LedgerRef = value
	}
	if value, ok := dc.mutation.CreatedAt(); ok {
		_spec.SetField(defund.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := dc.mutation.UpdatedAt(); ok {
		_spec.SetField(defund.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// DefundCreateBulk is the builder for creating many Defund entities in bulk.
type DefundCreateBulk struct {
	config
	err      error
	builders []*DefundCreate
}

// Save creates the Defund entities in the database.
func (dcb *DefundCreateBulk) Save(ctx context.Context) ([]*Defund, error) {
	if dcb.err != nil {
		return nil, dcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(dcb.builders))
	nodes := make([]*Defund, len(dcb.builders))
	mutators := make([]Mutator, len(dcb.builders))
	for i := range dcb.builders {
		func(i int, root context.Context) {
			builder := dcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DefundMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, dcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, dcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, dcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (dcb *DefundCreateBulk) SaveX(ctx context.Context) []*Defund {
	v, err := dcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dcb *DefundCreateBulk) Exec(ctx context.Context) error {
	_, err := dcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dcb *DefundCreateBulk) ExecX(ctx context.Context) {
	if err := dcb.Exec(ctx); err != nil {
		panic(err)
	}
}
