// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"reserve-interbank-settlement/services/payments-svc/ent/interestdistribution"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// InterestDistribution is the model entity for the InterestDistribution schema.
type InterestDistribution struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// At holds the value of the "at" field.
	At time.Time `json:"at,omitempty"`
	// RunBy holds the value of the "run_by" field.
	RunBy string `json:"run_by,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount int64 `json:"amount,omitempty"`
	// Paid holds the value of the "paid" field.
	Paid int64 `json:"paid,omitempty"`
	// Retained holds the value of the "retained" field.
	Retained int64 `json:"retained,omitempty"`
	// Shares holds the value of the "shares" field.
	Shares       map[string]int64 `json:"shares,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*InterestDistribution) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case interestdistribution.FieldShares:
			values[i] = new([]byte)
		case interestdistribution.FieldAmount, interestdistribution.FieldPaid, interestdistribution.FieldRetained:
			values[i] = new(sql.NullInt64)
		case interestdistribution.FieldID, interestdistribution.FieldRunBy:
			values[i] = new(sql.NullString)
		case interestdistribution.FieldAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the InterestDistribution fields.
func (id *InterestDistribution) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case interestdistribution.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				id.ID = value.String
			}
		case interestdistribution.FieldAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field at", values[i])
			} else if value.Valid {
				id.At = value.Time
			}
		case interestdistribution.FieldRunBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field run_by", values[i])
			} else if value.Valid {
				id.RunBy = value.String
			}
		case interestdistribution.FieldAmount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				id.Amount = value.Int64
			}
		case interestdistribution.FieldPaid:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field paid", values[i])
			} else if value.Valid {
				id.Paid = value.Int64
			}
		case interestdistribution.FieldRetained:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field retained", values[i])
			} else if value.Valid {
				id.Retained = value.Int64
			}
		case interestdistribution.FieldShares:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field shares", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &id.Shares); err != nil {
					return fmt.Errorf("unmarshal field shares: %w", err)
				}
			}
		default:
			id.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the InterestDistribution.
// This includes values selected through modifiers, order, etc.
func (id *InterestDistribution) Value(name string) (ent.Value, error) {
	return id.selectValues.Get(name)
}

// Update returns a builder for updating this InterestDistribution.
// Note that you need to call InterestDistribution.Unwrap() before calling this method if this InterestDistribution
// was returned from a transaction, and the transaction was committed or rolled back.
func (id *InterestDistribution) Update() *InterestDistributionUpdateOne {
	return NewInterestDistributionClient(id.config).UpdateOne(id)
}

// Unwrap unwraps the InterestDistribution entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (id *InterestDistribution) Unwrap() *InterestDistribution {
	_tx, ok := id.config.driver.(*txDriver)
	if !ok {
		panic("ent: InterestDistribution is not a transactional entity")
	}
	id.config.driver = _tx.drv
	return id
}

// String implements the fmt.Stringer.
func (id *InterestDistribution) String() string {
	var builder strings.Builder
	builder.WriteString("InterestDistribution(")
	builder.WriteString(fmt.Sprintf("id=%v, ", id.ID))
	builder.WriteString("at=")
	builder.WriteString(id.At.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("run_by=")
	builder.WriteString(id.RunBy)
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", id.Amount))
	builder.WriteString(", ")
	builder.WriteString("paid=")
	builder.WriteString(fmt.Sprintf("%v", id.Paid))
	builder.WriteString(", ")
	builder.WriteString("retained=")
	builder.WriteString(fmt.Sprintf("%v", id.Retained))
	builder.WriteString(", ")
	builder.WriteString("shares=")
	builder.WriteString(fmt.Sprintf("%v", id.Shares))
	builder.WriteByte(')')
	return builder.String()
}

// InterestDistributions is a parsable slice of InterestDistribution.
type InterestDistributions []*InterestDistribution
