// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"reserve-interbank-settlement/services/payments-svc/ent/nettingcycle"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// NettingCycle is the model entity for the NettingCycle schema.
type NettingCycle struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// CycleRef holds the value of the "cycle_ref" field.
	CycleRef string `json:"cycle_ref,omitempty"`
	// At holds the value of the "at" field.
	At time.Time `json:"at,omitempty"`
	// Trigger holds the value of the "trigger" field.
	Trigger string `json:"trigger,omitempty"`
	// Discharged holds the value of the "discharged" field.
	Discharged int `json:"discharged,omitempty"`
	// Deferred holds the value of the "deferred" field.
	Deferred int `json:"deferred,omitempty"`
	// Gross holds the value of the "gross" field.
	Gross int64 `json:"gross,omitempty"`
	// Net holds the value of the "net" field.
	Net          int64 `json:"net,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*NettingCycle) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case nettingcycle.FieldDischarged, nettingcycle.FieldDeferred, nettingcycle.FieldGross, nettingcycle.FieldNet:
			values[i] = new(sql.NullInt64)
		case nettingcycle.FieldID, nettingcycle.FieldCycleRef, nettingcycle.FieldTrigger:
			values[i] = new(sql.NullString)
		case nettingcycle.FieldAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the NettingCycle fields.
func (nc *NettingCycle) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case nettingcycle.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				nc.ID = value.String
			}
		case nettingcycle.FieldCycleRef:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cycle_ref", values[i])
			} else if value.Valid {
				nc.CycleRef = value.String
			}
		case nettingcycle.FieldAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field at", values[i])
			} else if value.Valid {
				nc.At = value.Time
			}
		case nettingcycle.FieldTrigger:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trigger", values[i])
			} else if value.Valid {
				nc.Trigger = value.String
			}
		case nettingcycle.FieldDischarged:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field discharged", values[i])
			} else if value.Valid {
				nc.Discharged = int(value.Int64)
			}
		case nettingcycle.FieldDeferred:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deferred", values[i])
			} else if value.Valid {
				nc.Deferred = int(value.Int64)
			}
		case nettingcycle.FieldGross:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field gross", values[i])
			} else if value.Valid {
				nc.Gross = value.Int64
			}
		case nettingcycle.FieldNet:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field net", values[i])
			} else if value.Valid {
				nc.Net = value.Int64
			}
		default:
			nc.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the NettingCycle.
// This includes values selected through modifiers, order, etc.
func (nc *NettingCycle) Value(name string) (ent.Value, error) {
	return nc.selectValues.Get(name)
}

// Update returns a builder for updating this NettingCycle.
// Note that you need to call NettingCycle.Unwrap() before calling this method if this NettingCycle
// was returned from a transaction, and the transaction was committed or rolled back.
func (nc *NettingCycle) Update() *NettingCycleUpdateOne {
	return NewNettingCycleClient(nc.config).UpdateOne(nc)
}

// Unwrap unwraps the NettingCycle entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (nc *NettingCycle) Unwrap() *NettingCycle {
	_tx, ok := nc.config.driver.(*txDriver)
	if !ok {
		panic("ent: NettingCycle is not a transactional entity")
	}
	nc.config.driver = _tx.drv
	return nc
}

// String implements the fmt.Stringer.
func (nc *NettingCycle) String() string {
	var builder strings.Builder
	builder.WriteString("NettingCycle(")
	builder.WriteString(fmt.Sprintf("id=%v, ", nc.ID))
	builder.WriteString("cycle_ref=")
	builder.WriteString(nc.CycleRef)
	builder.WriteString(", ")
	builder.WriteString("at=")
	builder.WriteString(nc.At.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("trigger=")
	builder.WriteString(nc.Trigger)
	builder.WriteString(", ")
	builder.WriteString("discharged=")
	builder.WriteString(fmt.Sprintf("%v", nc.Discharged))
	builder.WriteString(", ")
	builder.WriteString("deferred=")
	builder.WriteString(fmt.Sprintf("%v", nc.Deferred))
	builder.WriteString(", ")
	builder.WriteString("gross=")
	builder.WriteString(fmt.Sprintf("%v", nc.Gross))
	builder.WriteString(", ")
	builder.WriteString("net=")
	builder.WriteString(fmt.Sprintf("%v", nc.Net))
	builder.WriteByte(')')
	return builder.String()
}

// NettingCycles is a parsable slice of NettingCycle.
type NettingCycles []*NettingCycle
