// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"reserve-interbank-settlement/services/payments-svc/ent/nettingcycle"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NettingCycleCreate is the builder for creating a NettingCycle entity.
type NettingCycleCreate struct {
	config
	mutation *NettingCycleMutation
	hooks    []Hook
}

// SetCycleRef sets the "cycle_ref" field.
func (ncc *NettingCycleCreate) SetCycleRef(s string) *NettingCycleCreate {
	ncc.mutation.SetCycleRef(s)
	return ncc
}

// SetNillableCycleRef sets the "cycle_ref" field if the given value is not nil.
func (ncc *NettingCycleCreate) SetNillableCycleRef(s *string) *NettingCycleCreate {
	if s != nil {
		ncc.SetCycleRef(*s)
	}
	return ncc
}

// SetAt sets the "at" field.
func (ncc *NettingCycleCreate) SetAt(t time.Time) *NettingCycleCreate {
	ncc.mutation.SetAt(t)
	return ncc
}

// SetTrigger sets the "trigger" field.
func (ncc *NettingCycleCreate) SetTrigger(s string) *NettingCycleCreate {
	ncc.mutation.SetTrigger(s)
	return ncc
}

// SetDischarged sets the "discharged" field.
func (ncc *NettingCycleCreate) SetDischarged(i int) *NettingCycleCreate {
	ncc.mutation.SetDischarged(i)
	return ncc
}

// SetDeferred sets the "deferred" field.
func (ncc *NettingCycleCreate) SetDeferred(i int) *NettingCycleCreate {
	ncc.mutation.SetDeferred(i)
	return ncc
}

// SetGross sets the "gross" field.
func (ncc *NettingCycleCreate) SetGross(i int64) *NettingCycleCreate {
	ncc.mutation.SetGross(i)
	return ncc
}

// SetNet sets the "net" field.
func (ncc *NettingCycleCreate) SetNet(i int64) *NettingCycleCreate {
	ncc.mutation.SetNet(i)
	return ncc
}

// SetID sets the "id" field.
func (ncc *NettingCycleCreate) SetID(s string) *NettingCycleCreate {
	ncc.mutation.SetID(s)
	return ncc
}

// Mutation returns the NettingCycleMutation object of the builder.
func (ncc *NettingCycleCreate) Mutation() *NettingCycleMutation {
	return ncc.mutation
}

// Save creates the NettingCycle in the database.
func (ncc *NettingCycleCreate) Save(ctx context.Context) (*NettingCycle, error) {
	ncc.defaults()
	return withHooks(ctx, ncc.sqlSave, ncc.mutation, ncc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ncc *NettingCycleCreate) SaveX(ctx context.Context) *NettingCycle {
	v, err := ncc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ncc *NettingCycleCreate) Exec(ctx context.Context) error {
	_, err := ncc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ncc *NettingCycleCreate) ExecX(ctx context.Context) {
	if err := ncc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ncc *NettingCycleCreate) defaults() {
	if _, ok := ncc.mutation.CycleRef(); !ok {
		v := nettingcycle.DefaultCycleRef
		ncc.mutation.SetCycleRef(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ncc *NettingCycleCreate) check() error {
	if _, ok := ncc.mutation.CycleRef(); !ok {
		return &ValidationError{Name: "cycle_ref", err: errors.New(`ent: missing required field "NettingCycle.cycle_ref"`)}
	}
	if _, ok := ncc.mutation.At(); !ok {
		return &ValidationError{Name: "at", err: errors.New(`ent: missing required field "NettingCycle.at"`)}
	}
	if _, ok := ncc.mutation.Trigger(); !ok {
		return &ValidationError{Name: "trigger", err: errors.New(`ent: missing required field "NettingCycle.trigger"`)}
	}
	if _, ok := ncc.mutation.Discharged(); !ok {
		return &ValidationError{Name: "discharged", err: errors.New(`ent: missing required field "NettingCycle.discharged"`)}
	}
	if _, ok := ncc.mutation.Deferred(); !ok {
		return &ValidationError{Name: "deferred", err: errors.New(`ent: missing required field "NettingCycle.deferred"`)}
	}
	if _, ok := ncc.mutation.Gross(); !ok {
		return &ValidationError{Name: "gross", err: errors.New(`ent: missing required field "NettingCycle.gross"`)}
	}
	if _, ok := ncc.mutation.Net(); !ok {
		return &ValidationError{Name: "net", err: errors.New(`ent: missing required field "NettingCycle.net"`)}
	}
	return nil
}

func (ncc *NettingCycleCreate) sqlSave(ctx context.Context) (*NettingCycle, error) {
	if err := ncc.check(); err != nil {
		return nil, err
	}
	_node, _spec := ncc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ncc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected NettingCycle.ID type: %T", _spec.ID.Value)
		}
	}
	ncc.mutation.id = &_node.ID
	ncc.mutation.done = true
	return _node, nil
}

func (ncc *NettingCycleCreate) createSpec() (*NettingCycle, *sqlgraph.CreateSpec) {
	var (
		_node = &NettingCycle{config: ncc.config}
		_spec = sqlgraph.NewCreateSpec(nettingcycle.Table, sqlgraph.NewFieldSpec(nettingcycle.FieldID, field.TypeString))
	)
	if id, ok := ncc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := ncc.mutation.CycleRef(); ok {
		_spec.SetField(nettingcycle.FieldCycleRef, field.TypeString, value)
		_node.CycleRef = value
	}
	if value, ok := ncc.mutation.At(); ok {
		_spec.SetField(nettingcycle.FieldAt, field.TypeTime, value)
		_node.At = value
	}
	if value, ok := ncc.mutation.Trigger(); ok {
		_spec.SetField(nettingcycle.FieldTrigger, field.TypeString, value)
		_node.Trigger = value
	}
	if value, ok := ncc.mutation.Discharged(); ok {
		_spec.SetField(nettingcycle.FieldDischarged, field.TypeInt, value)
		_node.Discharged = value
	}
	if value, ok := ncc.mutation.Deferred(); ok {
		_spec.SetField(nettingcycle.FieldDeferred, field.TypeInt, value)
		_node.Deferred = value
	}
	if value, ok := ncc.mutation.Gross(); ok {
		_spec.SetField(nettingcycle.FieldGross, field.TypeInt64, value)
		_node.Gross = value
	}
	if value, ok := ncc.mutation.Net(); ok {
		_spec.SetField(nettingcycle.FieldNet, field.TypeInt64, value)
		_node.Net = value
	}
	return _node, _spec
}

// NettingCycleCreateBulk is the builder for creating many NettingCycle entities in bulk.
type NettingCycleCreateBulk struct {
	config
	err      error
	builders []*NettingCycleCreate
}

// Save creates the NettingCycle entities in the database.
func (nccb *NettingCycleCreateBulk) Save(ctx context.Context) ([]*NettingCycle, error) {
	if nccb.err != nil {
		return nil, nccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(nccb.builders))
	nodes := make([]*NettingCycle, len(nccb.builders))
	mutators := make([]Mutator, len(nccb.builders))
	for i := range nccb.builders {
		func(i int, root context.Context) {
			builder := nccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NettingCycleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, nccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, nccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, nccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (nccb *NettingCycleCreateBulk) SaveX(ctx context.Context) []*NettingCycle {
	v, err := nccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (nccb *NettingCycleCreateBulk) Exec(ctx context.Context) error {
	_, err := nccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nccb *NettingCycleCreateBulk) ExecX(ctx context.Context) {
	if err := nccb.Exec(ctx); err != nil {
		panic(err)
	}
}
