// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"reserve-interbank-settlement/services/payments-svc/ent/paymentorder"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// PaymentOrder is the model entity for the PaymentOrder schema.
type PaymentOrder struct {
	config `json:"-"`
	// ID of the ent.
	// UUIDv7
	ID string `json:"id,omitempty"`
	// OrganizationID holds the value of the "organization_id" field.
	OrganizationID string `json:"organization_id,omitempty"`
	// the organization's bank (member id)
	BankID string `json:"bank_id,omitempty"`
	// pain.001 file it came in
	FileID *string `json:"file_id,omitempty"`
	// IdempotencyKey holds the value of the "idempotency_key" field.
	IdempotencyKey *string `json:"idempotency_key,omitempty"`
	// SHA-256 of the request, to tell a replay from a key reuse
	RequestHash string `json:"request_hash,omitempty"`
	// EndToEndID holds the value of the "end_to_end_id" field.
	EndToEndID string `json:"end_to_end_id,omitempty"`
	// Uetr holds the value of the "uetr" field.
	Uetr string `json:"uetr,omitempty"`
	// DebtorAccount holds the value of the "debtor_account" field.
	DebtorAccount string `json:"debtor_account,omitempty"`
	// CreditorName holds the value of the "creditor_name" field.
	CreditorName string `json:"creditor_name,omitempty"`
	// CreditorRouting holds the value of the "creditor_routing" field.
	CreditorRouting string `json:"creditor_routing,omitempty"`
	// CreditorAccount holds the value of the "creditor_account" field.
	CreditorAccount string `json:"creditor_account,omitempty"`
	// cents
	Amount int64 `json:"amount,omitempty"`
	// Priority holds the value of the "priority" field.
	Priority string `json:"priority,omitempty"`
	// Remittance holds the value of the "remittance" field.
	Remittance string `json:"remittance,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// IsoStatus holds the value of the "iso_status" field.
	IsoStatus string `json:"iso_status,omitempty"`
	// ReasonCode holds the value of the "reason_code" field.
	ReasonCode string `json:"reason_code,omitempty"`
	// Route holds the value of the "route" field.
	Route string `json:"route,omitempty"`
	// RouteNote holds the value of the "route_note" field.
	RouteNote string `json:"route_note,omitempty"`
	// PayeeAccountStatus holds the value of the "payee_account_status" field.
	PayeeAccountStatus string `json:"payee_account_status,omitempty"`
	// PayeeNameMatch holds the value of the "payee_name_match" field.
	PayeeNameMatch string `json:"payee_name_match,omitempty"`
	// PayeeRegisteredName holds the value of the "payee_registered_name" field.
	PayeeRegisteredName string `json:"payee_registered_name,omitempty"`
	// ApprovalsRequired holds the value of the "approvals_required" field.
	ApprovalsRequired int `json:"approvals_required,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy string `json:"created_by,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// SettledAt holds the value of the "settled_at" field.
	SettledAt *time.Time `json:"settled_at,omitempty"`
	// OfacReportDue holds the value of the "ofac_report_due" field.
	OfacReportDue *time.Time `json:"ofac_report_due,omitempty"`
	// SanctionsMatch holds the value of the "sanctions_match" field.
	SanctionsMatch string `json:"sanctions_match,omitempty"`
	// router payment id
	PaymentRef string `json:"payment_ref,omitempty"`
	// netting obligation id
	ObligationRef string `json:"obligation_ref,omitempty"`
	// Tokenized holds the value of the "tokenized" field.
	Tokenized bool `json:"tokenized,omitempty"`
	// Released holds the value of the "released" field.
	Released bool `json:"released,omitempty"`
	// optimistic lock
	Version int `json:"version,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PaymentOrderQuery when eager-loading is set.
	Edges        PaymentOrderEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PaymentOrderEdges holds the relations/edges for other nodes in the graph.
type PaymentOrderEdges struct {
	// Events holds the value of the events edge.
	Events []*OrderEvent `json:"events,omitempty"`
	// Approvals holds the value of the approvals edge.
	Approvals []*Approval `json:"approvals,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// EventsOrErr returns the Events value or an error if the edge
// was not loaded in eager-loading.
func (e PaymentOrderEdges) EventsOrErr() ([]*OrderEvent, error) {
	if e.loadedTypes[0] {
		return e.Events, nil
	}
	return nil, &NotLoadedError{edge: "events"}
}

// ApprovalsOrErr returns the Approvals value or an error if the edge
// was not loaded in eager-loading.
func (e PaymentOrderEdges) ApprovalsOrErr() ([]*Approval, error) {
	if e.loadedTypes[1] {
		return e.Approvals, nil
	}
	return nil, &NotLoadedError{edge: "approvals"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PaymentOrder) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case paymentorder.FieldTokenized, paymentorder.FieldReleased:
			values[i] = new(sql.NullBool)
		case paymentorder.FieldAmount, paymentorder.FieldApprovalsRequired, paymentorder.FieldVersion:
			values[i] = new(sql.NullInt64)
		case paymentorder.FieldID, paymentorder.FieldOrganizationID, paymentorder.FieldBankID, paymentorder.FieldFileID, paymentorder.FieldIdempotencyKey, paymentorder.FieldRequestHash, paymentorder.FieldEndToEndID, paymentorder.FieldUetr, paymentorder.FieldDebtorAccount, paymentorder.FieldCreditorName, paymentorder.FieldCreditorRouting, paymentorder.FieldCreditorAccount, paymentorder.FieldPriority, paymentorder.FieldRemittance, paymentorder.FieldStatus, paymentorder.FieldIsoStatus, paymentorder.FieldReasonCode, paymentorder.FieldRoute, paymentorder.FieldRouteNote, paymentorder.FieldPayeeAccountStatus, paymentorder.FieldPayeeNameMatch, paymentorder.FieldPayeeRegisteredName, paymentorder.FieldCreatedBy, paymentorder.FieldSanctionsMatch, paymentorder.FieldPaymentRef, paymentorder.FieldObligationRef:
			values[i] = new(sql.NullString)
		case paymentorder.FieldCreatedAt, paymentorder.FieldUpdatedAt, paymentorder.FieldSettledAt, paymentorder.FieldOfacReportDue:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PaymentOrder fields.
func (po *PaymentOrder) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case paymentorder.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				po.ID = value.String
			}
		case paymentorder.FieldOrganizationID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field organization_id", values[i])
			} else if value.Valid {
				po.OrganizationID = value.String
			}
		case paymentorder.FieldBankID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field bank_id", values[i])
			} else if value.Valid {
				po.BankID = value.String
			}
		case paymentorder.FieldFileID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field file_id", values[i])
			} else if value.Valid {
				po.FileID = new(string)
				*po.FileID = value.String
			}
		case paymentorder.FieldIdempotencyKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field idempotency_key", values[i])
			} else if value.Valid {
				po.IdempotencyKey = new(string)
				*po.IdempotencyKey = value.String
			}
		case paymentorder.FieldRequestHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_hash", values[i])
			} else if value.Valid {
				po.RequestHash = value.String
			}
		case paymentorder.FieldEndToEndID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field end_to_end_id", values[i])
			} else if value.Valid {
				po.EndToEndID = value.String
			}
		case paymentorder.FieldUetr:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field uetr", values[i])
			} else if value.Valid {
				po.Uetr = value.String
			}
		case paymentorder.FieldDebtorAccount:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field debtor_account", values[i])
			} else if value.Valid {
				po.DebtorAccount = value.String
			}
		case paymentorder.FieldCreditorName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field creditor_name", values[i])
			} else if value.Valid {
				po.CreditorName = value.String
			}
		case paymentorder.FieldCreditorRouting:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field creditor_routing", values[i])
			} else if value.Valid {
				po.CreditorRouting = value.String
			}
		case paymentorder.FieldCreditorAccount:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field creditor_account", values[i])
			} else if value.Valid {
				po.CreditorAccount = value.String
			}
		case paymentorder.FieldAmount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				po.Amount = value.Int64
			}
		case paymentorder.FieldPriority:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				po.Priority = value.String
			}
		case paymentorder.FieldRemittance:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field remittance", values[i])
			} else if value.Valid {
				po.Remittance = value.String
			}
		case paymentorder.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				po.Status = value.String
			}
		case paymentorder.FieldIsoStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field iso_status", values[i])
			} else if value.Valid {
				po.IsoStatus = value.String
			}
		case paymentorder.FieldReasonCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason_code", values[i])
			} else if value.Valid {
				po.ReasonCode = value.String
			}
		case paymentorder.FieldRoute:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field route", values[i])
			} else if value.Valid {
				po.Route = value.String
			}
		case paymentorder.FieldRouteNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field route_note", values[i])
			} else if value.Valid {
				po.RouteNote = value.String
			}
		case paymentorder.FieldPayeeAccountStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payee_account_status", values[i])
			} else if value.Valid {
				po.PayeeAccountStatus = value.String
			}
		case paymentorder.FieldPayeeNameMatch:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payee_name_match", values[i])
			} else if value.Valid {
				po.PayeeNameMatch = value.String
			}
		case paymentorder.FieldPayeeRegisteredName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payee_registered_name", values[i])
			} else if value.Valid {
				po.PayeeRegisteredName = value.String
			}
		case paymentorder.FieldApprovalsRequired:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field approvals_required", values[i])
			} else if value.Valid {
				po.ApprovalsRequired = int(value.Int64)
			}
		case paymentorder.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				po.CreatedBy = value.String
			}
		case paymentorder.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				po.CreatedAt = value.Time
			}
		case paymentorder.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				po.UpdatedAt = value.Time
			}
		case paymentorder.FieldSettledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field settled_at", values[i])
			} else if value.Valid {
				po.SettledAt = new(time.Time)
				*po.SettledAt = value.Time
			}
		case paymentorder.FieldOfacReportDue:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field ofac_report_due", values[i])
			} else if value.Valid {
				po.OfacReportDue = new(time.Time)
				*po.OfacReportDue = value.Time
			}
		case paymentorder.FieldSanctionsMatch:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sanctions_match", values[i])
			} else if value.Valid {
				po.SanctionsMatch = value.String
			}
		case paymentorder.FieldPaymentRef:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payment_ref", values[i])
			} else if value.Valid {
				po.PaymentRef = value.String
			}
		case paymentorder.FieldObligationRef:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field obligation_ref", values[i])
			} else if value.Valid {
				po.ObligationRef = value.String
			}
		case paymentorder.FieldTokenized:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field tokenized", values[i])
			} else if value.Valid {
				po.Tokenized = value.Bool
			}
		case paymentorder.FieldReleased:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field released", values[i])
			} else if value.Valid {
				po.Released = value.Bool
			}
		case paymentorder.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				po.Version = int(value.Int64)
			}
		default:
			po.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PaymentOrder.
// This includes values selected through modifiers, order, etc.
func (po *PaymentOrder) Value(name string) (ent.Value, error) {
	return po.selectValues.Get(name)
}

// QueryEvents queries the "events" edge of the PaymentOrder entity.
func (po *PaymentOrder) QueryEvents() *OrderEventQuery {
	return NewPaymentOrderClient(po.config).QueryEvents(po)
}

// QueryApprovals queries the "approvals" edge of the PaymentOrder entity.
func (po *PaymentOrder) QueryApprovals() *ApprovalQuery {
	return NewPaymentOrderClient(po.config).QueryApprovals(po)
}

// Update returns a builder for updating this PaymentOrder.
// Note that you need to call PaymentOrder.Unwrap() before calling this method if this PaymentOrder
// was returned from a transaction, and the transaction was committed or rolled back.
func (po *PaymentOrder) Update() *PaymentOrderUpdateOne {
	return NewPaymentOrderClient(po.config).UpdateOne(po)
}

// Unwrap unwraps the PaymentOrder entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (po *PaymentOrder) Unwrap() *PaymentOrder {
	_tx, ok := po.config.driver.(*txDriver)
	if !ok {
		panic("ent: PaymentOrder is not a transactional entity")
	}
	po.config.driver = _tx.drv
	return po
}

// String implements the fmt.Stringer.
func (po *PaymentOrder) String() string {
	var builder strings.Builder
	builder.WriteString("PaymentOrder(")
	builder.WriteString(fmt.Sprintf("id=%v, ", po.ID))
	builder.WriteString("organization_id=")
	builder.WriteString(po.OrganizationID)
	builder.WriteString(", ")
	builder.WriteString("bank_id=")
	builder.WriteString(po.BankID)
	builder.WriteString(", ")
	if v := po.FileID; v != nil {
		builder.WriteString("file_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := po.IdempotencyKey; v != nil {
		builder.WriteString("idempotency_key=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("request_hash=")
	builder.WriteString(po.RequestHash)
	builder.WriteString(", ")
	builder.WriteString("end_to_end_id=")
	builder.WriteString(po.EndToEndID)
	builder.WriteString(", ")
	builder.WriteString("uetr=")
	builder.WriteString(po.Uetr)
	builder.WriteString(", ")
	builder.WriteString("debtor_account=")
	builder.WriteString(po.DebtorAccount)
	builder.WriteString(", ")
	builder.WriteString("creditor_name=")
	builder.WriteString(po.CreditorName)
	builder.WriteString(", ")
	builder.WriteString("creditor_routing=")
	builder.WriteString(po.CreditorRouting)
	builder.WriteString(", ")
	builder.WriteString("creditor_account=")
	builder.WriteString(po.CreditorAccount)
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", po.Amount))
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(po.Priority)
	builder.WriteString(", ")
	builder.WriteString("remittance=")
	builder.WriteString(po.Remittance)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(po.Status)
	builder.WriteString(", ")
	builder.WriteString("iso_status=")
	builder.WriteString(po.IsoStatus)
	builder.WriteString(", ")
	builder.WriteString("reason_code=")
	builder.WriteString(po.ReasonCode)
	builder.WriteString(", ")
	builder.WriteString("route=")
	builder.WriteString(po.Route)
	builder.WriteString(", ")
	builder.WriteString("route_note=")
	builder.WriteString(po.RouteNote)
	builder.WriteString(", ")
	builder.WriteString("payee_account_status=")
	builder.WriteString(po.PayeeAccountStatus)
	builder.WriteString(", ")
	builder.WriteString("payee_name_match=")
	builder.WriteString(po.PayeeNameMatch)
	builder.WriteString(", ")
	builder.WriteString("payee_registered_name=")
	builder.WriteString(po.PayeeRegisteredName)
	builder.WriteString(", ")
	builder.WriteString("approvals_required=")
	builder.WriteString(fmt.Sprintf("%v", po.ApprovalsRequired))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(po.CreatedBy)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(po.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(po.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := po.SettledAt; v != nil {
		builder.WriteString("settled_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := po.OfacReportDue; v != nil {
		builder.WriteString("ofac_report_due=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("sanctions_match=")
	builder.WriteString(po.SanctionsMatch)
	builder.WriteString(", ")
	builder.WriteString("payment_ref=")
	builder.WriteString(po.PaymentRef)
	builder.WriteString(", ")
	builder.WriteString("obligation_ref=")
	builder.WriteString(po.ObligationRef)
	builder.WriteString(", ")
	builder.WriteString("tokenized=")
	builder.WriteString(fmt.Sprintf("%v", po.Tokenized))
	builder.WriteString(", ")
	builder.WriteString("released=")
	builder.WriteString(fmt.Sprintf("%v", po.Released))
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", po.Version))
	builder.WriteByte(')')
	return builder.String()
}

// PaymentOrders is a parsable slice of PaymentOrder.
type PaymentOrders []*PaymentOrder
