// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"reserve-interbank-settlement/services/payments-svc/ent/paymentfile"
	"reserve-interbank-settlement/services/payments-svc/ent/predicate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PaymentFileQuery is the builder for querying PaymentFile entities.
type PaymentFileQuery struct {
	config
	ctx        *QueryContext
	order      []paymentfile.OrderOption
	inters     []Interceptor
	predicates []predicate.PaymentFile
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PaymentFileQuery builder.
func (pfq *PaymentFileQuery) Where(ps ...predicate.PaymentFile) *PaymentFileQuery {
	pfq.predicates = append(pfq.predicates, ps...)
	return pfq
}

// Limit the number of records to be returned by this query.
func (pfq *PaymentFileQuery) Limit(limit int) *PaymentFileQuery {
	pfq.ctx.Limit = &limit
	return pfq
}

// Offset to start from.
func (pfq *PaymentFileQuery) Offset(offset int) *PaymentFileQuery {
	pfq.ctx.Offset = &offset
	return pfq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (pfq *PaymentFileQuery) Unique(unique bool) *PaymentFileQuery {
	pfq.ctx.Unique = &unique
	return pfq
}

// Order specifies how the records should be ordered.
func (pfq *PaymentFileQuery) Order(o ...paymentfile.OrderOption) *PaymentFileQuery {
	pfq.order = append(pfq.order, o...)
	return pfq
}

// First returns the first PaymentFile entity from the query.
// Returns a *NotFoundError when no PaymentFile was found.
func (pfq *PaymentFileQuery) First(ctx context.Context) (*PaymentFile, error) {
	nodes, err := pfq.Limit(1).All(setContextOp(ctx, pfq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{paymentfile.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (pfq *PaymentFileQuery) FirstX(ctx context.Context) *PaymentFile {
	node, err := pfq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PaymentFile ID from the query.
// Returns a *NotFoundError when no PaymentFile ID was found.
func (pfq *PaymentFileQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = pfq.Limit(1).IDs(setContextOp(ctx, pfq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{paymentfile.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (pfq *PaymentFileQuery) FirstIDX(ctx context.Context) string {
	id, err := pfq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PaymentFile entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PaymentFile entity is found.
// Returns a *NotFoundError when no PaymentFile entities are found.
func (pfq *PaymentFileQuery) Only(ctx context.Context) (*PaymentFile, error) {
	nodes, err := pfq.Limit(2).All(setContextOp(ctx, pfq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{paymentfile.Label}
	default:
		return nil, &NotSingularError{paymentfile.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (pfq *PaymentFileQuery) OnlyX(ctx context.Context) *PaymentFile {
	node, err := pfq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PaymentFile ID in the query.
// Returns a *NotSingularError when more than one PaymentFile ID is found.
// Returns a *NotFoundError when no entities are found.
func (pfq *PaymentFileQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = pfq.Limit(2).IDs(setContextOp(ctx, pfq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{paymentfile.Label}
	default:
		err = &NotSingularError{paymentfile.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (pfq *PaymentFileQuery) OnlyIDX(ctx context.Context) string {
	id, err := pfq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PaymentFiles.
func (pfq *PaymentFileQuery) All(ctx context.Context) ([]*PaymentFile, error) {
	ctx = setContextOp(ctx, pfq.ctx, ent.OpQueryAll)
	if err := pfq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PaymentFile, *PaymentFileQuery]()
	return withInterceptors[[]*PaymentFile](ctx, pfq, qr, pfq.inters)
}

// AllX is like All, but panics if an error occurs.
func (pfq *PaymentFileQuery) AllX(ctx context.Context) []*PaymentFile {
	nodes, err := pfq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PaymentFile IDs.
func (pfq *PaymentFileQuery) IDs(ctx context.Context) (ids []string, err error) {
	if pfq.ctx.Unique == nil && pfq.path != nil {
		pfq.Unique(true)
	}
	ctx = setContextOp(ctx, pfq.ctx, ent.OpQueryIDs)
	if err = pfq.Select(paymentfile.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (pfq *PaymentFileQuery) IDsX(ctx context.Context) []string {
	ids, err := pfq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (pfq *PaymentFileQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, pfq.ctx, ent.OpQueryCount)
	if err := pfq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, pfq, querierCount[*PaymentFileQuery](), pfq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (pfq *PaymentFileQuery) CountX(ctx context.Context) int {
	count, err := pfq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (pfq *PaymentFileQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, pfq.ctx, ent.OpQueryExist)
	switch _, err := pfq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (pfq *PaymentFileQuery) ExistX(ctx context.Context) bool {
	exist, err := pfq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PaymentFileQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (pfq *PaymentFileQuery) Clone() *PaymentFileQuery {
	if pfq == nil {
		return nil
	}
	return &PaymentFileQuery{
		config:     pfq.config,
		ctx:        pfq.ctx.Clone(),
		order:      append([]paymentfile.OrderOption{}, pfq.order...),
		inters:     append([]Interceptor{}, pfq.inters...),
		predicates: append([]predicate.PaymentFile{}, pfq.predicates...),
		// clone intermediate query.
		sql:  pfq.sql.Clone(),
		path: pfq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		OrganizationID string `json:"organization_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PaymentFile.Query().
//		GroupBy(paymentfile.FieldOrganizationID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (pfq *PaymentFileQuery) GroupBy(field string, fields ...string) *PaymentFileGroupBy {
	pfq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PaymentFileGroupBy{build: pfq}
	grbuild.flds = &pfq.ctx.Fields
	grbuild.label = paymentfile.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		OrganizationID string `json:"organization_id,omitempty"`
//	}
//
//	client.PaymentFile.Query().
//		Select(paymentfile.FieldOrganizationID).
//		Scan(ctx, &v)
func (pfq *PaymentFileQuery) Select(fields ...string) *PaymentFileSelect {
	pfq.ctx.Fields = append(pfq.ctx.Fields, fields...)
	sbuild := &PaymentFileSelect{PaymentFileQuery: pfq}
	sbuild.label = paymentfile.Label
	sbuild.flds, sbuild.scan = &pfq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PaymentFileSelect configured with the given aggregations.
func (pfq *PaymentFileQuery) Aggregate(fns ...AggregateFunc) *PaymentFileSelect {
	return pfq.Select().Aggregate(fns...)
}

func (pfq *PaymentFileQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range pfq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, pfq); err != nil {
				return err
			}
		}
	}
	for _, f := range pfq.ctx.Fields {
		if !paymentfile.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if pfq.path != nil {
		prev, err := pfq.path(ctx)
		if err != nil {
			return err
		}
		pfq.sql = prev
	}
	return nil
}

func (pfq *PaymentFileQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PaymentFile, error) {
	var (
		nodes = []*PaymentFile{}
		_spec = pfq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PaymentFile).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PaymentFile{config: pfq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(pfq.modifiers) > 0 {
		_spec.Modifiers = pfq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, pfq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (pfq *PaymentFileQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := pfq.querySpec()
	if len(pfq.modifiers) > 0 {
		_spec.Modifiers = pfq.modifiers
	}
	_spec.Node.Columns = pfq.ctx.Fields
	if len(pfq.ctx.Fields) > 0 {
		_spec.Unique = pfq.ctx.Unique != nil && *pfq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, pfq.driver, _spec)
}

func (pfq *PaymentFileQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(paymentfile.Table, paymentfile.Columns, sqlgraph.NewFieldSpec(paymentfile.FieldID, field.TypeString))
	_spec.From = pfq.sql
	if unique := pfq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if pfq.path != nil {
		_spec.Unique = true
	}
	if fields := pfq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, paymentfile.FieldID)
		for i := range fields {
			if fields[i] != paymentfile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := pfq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := pfq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := pfq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := pfq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (pfq *PaymentFileQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(pfq.driver.Dialect())
	t1 := builder.Table(paymentfile.Table)
	columns := pfq.ctx.Fields
	if len(columns) == 0 {
		columns = paymentfile.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if pfq.sql != nil {
		selector = pfq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if pfq.ctx.Unique != nil && *pfq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range pfq.modifiers {
		m(selector)
	}
	for _, p := range pfq.predicates {
		p(selector)
	}
	for _, p := range pfq.order {
		p(selector)
	}
	if offset := pfq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := pfq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (pfq *PaymentFileQuery) ForUpdate(opts ...sql.LockOption) *PaymentFileQuery {
	if pfq.driver.Dialect() == dialect.Postgres {
		pfq.Unique(false)
	}
	pfq.modifiers = append(pfq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return pfq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (pfq *PaymentFileQuery) ForShare(opts ...sql.LockOption) *PaymentFileQuery {
	if pfq.driver.Dialect() == dialect.Postgres {
		pfq.Unique(false)
	}
	pfq.modifiers = append(pfq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return pfq
}

// PaymentFileGroupBy is the group-by builder for PaymentFile entities.
type PaymentFileGroupBy struct {
	selector
	build *PaymentFileQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pfgb *PaymentFileGroupBy) Aggregate(fns ...AggregateFunc) *PaymentFileGroupBy {
	pfgb.fns = append(pfgb.fns, fns...)
	return pfgb
}

// Scan applies the selector query and scans the result into the given value.
func (pfgb *PaymentFileGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pfgb.build.ctx, ent.OpQueryGroupBy)
	if err := pfgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PaymentFileQuery, *PaymentFileGroupBy](ctx, pfgb.build, pfgb, pfgb.build.inters, v)
}

func (pfgb *PaymentFileGroupBy) sqlScan(ctx context.Context, root *PaymentFileQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(pfgb.fns))
	for _, fn := range pfgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*pfgb.flds)+len(pfgb.fns))
		for _, f := range *pfgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*pfgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pfgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PaymentFileSelect is the builder for selecting fields of PaymentFile entities.
type PaymentFileSelect struct {
	*PaymentFileQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pfs *PaymentFileSelect) Aggregate(fns ...AggregateFunc) *PaymentFileSelect {
	pfs.fns = append(pfs.fns, fns...)
	return pfs
}

// Scan applies the selector query and scans the result into the given value.
func (pfs *PaymentFileSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pfs.ctx, ent.OpQuerySelect)
	if err := pfs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PaymentFileQuery, *PaymentFileSelect](ctx, pfs.PaymentFileQuery, pfs, pfs.inters, v)
}

func (pfs *PaymentFileSelect) sqlScan(ctx context.Context, root *PaymentFileQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pfs.fns))
	for _, fn := range pfs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pfs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pfs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
