// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"reserve-interbank-settlement/services/payments-svc/ent/paymentfile"
	"reserve-interbank-settlement/services/payments-svc/ent/schema"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// PaymentFile is the model entity for the PaymentFile schema.
type PaymentFile struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// OrganizationID holds the value of the "organization_id" field.
	OrganizationID string `json:"organization_id,omitempty"`
	// GrpHdr/MsgId
	MessageID string `json:"message_id,omitempty"`
	// RequestHash holds the value of the "request_hash" field.
	RequestHash string `json:"request_hash,omitempty"`
	// IdempotencyKey holds the value of the "idempotency_key" field.
	IdempotencyKey string `json:"idempotency_key,omitempty"`
	// Transactions holds the value of the "transactions" field.
	Transactions int `json:"transactions,omitempty"`
	// ControlSum holds the value of the "control_sum" field.
	ControlSum int64 `json:"control_sum,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy string `json:"created_by,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Rejections holds the value of the "rejections" field.
	Rejections   []schema.Rejection `json:"rejections,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PaymentFile) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case paymentfile.FieldRejections:
			values[i] = new([]byte)
		case paymentfile.FieldTransactions, paymentfile.FieldControlSum:
			values[i] = new(sql.NullInt64)
		case paymentfile.FieldID, paymentfile.FieldOrganizationID, paymentfile.FieldMessageID, paymentfile.FieldRequestHash, paymentfile.FieldIdempotencyKey, paymentfile.FieldCreatedBy:
			values[i] = new(sql.NullString)
		case paymentfile.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PaymentFile fields.
func (pf *PaymentFile) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case paymentfile.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				pf.ID = value.String
			}
		case paymentfile.FieldOrganizationID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field organization_id", values[i])
			} else if value.Valid {
				pf.OrganizationID = value.String
			}
		case paymentfile.FieldMessageID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message_id", values[i])
			} else if value.Valid {
				pf.MessageID = value.String
			}
		case paymentfile.FieldRequestHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_hash", values[i])
			} else if value.Valid {
				pf.RequestHash = value.String
			}
		case paymentfile.FieldIdempotencyKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field idempotency_key", values[i])
			} else if value.Valid {
				pf.IdempotencyKey = value.String
			}
		case paymentfile.FieldTransactions:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field transactions", values[i])
			} else if value.Valid {
				pf.Transactions = int(value.Int64)
			}
		case paymentfile.FieldControlSum:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field control_sum", values[i])
			} else if value.Valid {
				pf.ControlSum = value.Int64
			}
		case paymentfile.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				pf.CreatedBy = value.String
			}
		case paymentfile.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				pf.CreatedAt = value.Time
			}
		case paymentfile.FieldRejections:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field rejections", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &pf.Rejections); err != nil {
					return fmt.Errorf("unmarshal field rejections: %w", err)
				}
			}
		default:
			pf.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PaymentFile.
// This includes values selected through modifiers, order, etc.
func (pf *PaymentFile) Value(name string) (ent.Value, error) {
	return pf.selectValues.Get(name)
}

// Update returns a builder for updating this PaymentFile.
// Note that you need to call PaymentFile.Unwrap() before calling this method if this PaymentFile
// was returned from a transaction, and the transaction was committed or rolled back.
func (pf *PaymentFile) Update() *PaymentFileUpdateOne {
	return NewPaymentFileClient(pf.config).UpdateOne(pf)
}

// Unwrap unwraps the PaymentFile entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pf *PaymentFile) Unwrap() *PaymentFile {
	_tx, ok := pf.config.driver.(*txDriver)
	if !ok {
		panic("ent: PaymentFile is not a transactional entity")
	}
	pf.config.driver = _tx.drv
	return pf
}

// String implements the fmt.Stringer.
func (pf *PaymentFile) String() string {
	var builder strings.Builder
	builder.WriteString("PaymentFile(")
	builder.WriteString(fmt.Sprintf("id=%v, ", pf.ID))
	builder.WriteString("organization_id=")
	builder.WriteString(pf.OrganizationID)
	builder.WriteString(", ")
	builder.WriteString("message_id=")
	builder.WriteString(pf.MessageID)
	builder.WriteString(", ")
	builder.WriteString("request_hash=")
	builder.WriteString(pf.RequestHash)
	builder.WriteString(", ")
	builder.WriteString("idempotency_key=")
	builder.WriteString(pf.IdempotencyKey)
	builder.WriteString(", ")
	builder.WriteString("transactions=")
	builder.WriteString(fmt.Sprintf("%v", pf.Transactions))
	builder.WriteString(", ")
	builder.WriteString("control_sum=")
	builder.WriteString(fmt.Sprintf("%v", pf.ControlSum))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(pf.CreatedBy)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(pf.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("rejections=")
	builder.WriteString(fmt.Sprintf("%v", pf.Rejections))
	builder.WriteByte(')')
	return builder.String()
}

// PaymentFiles is a parsable slice of PaymentFile.
type PaymentFiles []*PaymentFile
