// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"reserve-interbank-settlement/services/payments-svc/ent/approval"
	"reserve-interbank-settlement/services/payments-svc/ent/orderevent"
	"reserve-interbank-settlement/services/payments-svc/ent/paymentorder"
	"reserve-interbank-settlement/services/payments-svc/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PaymentOrderUpdate is the builder for updating PaymentOrder entities.
type PaymentOrderUpdate struct {
	config
	hooks    []Hook
	mutation *PaymentOrderMutation
}

// Where appends a list predicates to the PaymentOrderUpdate builder.
func (pou *PaymentOrderUpdate) Where(ps ...predicate.PaymentOrder) *PaymentOrderUpdate {
	pou.mutation.Where(ps...)
	return pou
}

// SetStatus sets the "status" field.
func (pou *PaymentOrderUpdate) SetStatus(s string) *PaymentOrderUpdate {
	pou.mutation.SetStatus(s)
	return pou
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (pou *PaymentOrderUpdate) SetNillableStatus(s *string) *PaymentOrderUpdate {
	if s != nil {
		pou.SetStatus(*s)
	}
	return pou
}

// SetIsoStatus sets the "iso_status" field.
func (pou *PaymentOrderUpdate) SetIsoStatus(s string) *PaymentOrderUpdate {
	pou.mutation.SetIsoStatus(s)
	return pou
}

// SetNillableIsoStatus sets the "iso_status" field if the given value is not nil.
func (pou *PaymentOrderUpdate) SetNillableIsoStatus(s *string) *PaymentOrderUpdate {
	if s != nil {
		pou.SetIsoStatus(*s)
	}
	return pou
}

// SetReasonCode sets the "reason_code" field.
func (pou *PaymentOrderUpdate) SetReasonCode(s string) *PaymentOrderUpdate {
	pou.mutation.SetReasonCode(s)
	return pou
}

// SetNillableReasonCode sets the "reason_code" field if the given value is not nil.
func (pou *PaymentOrderUpdate) SetNillableReasonCode(s *string) *PaymentOrderUpdate {
	if s != nil {
		pou.SetReasonCode(*s)
	}
	return pou
}

// SetRoute sets the "route" field.
func (pou *PaymentOrderUpdate) SetRoute(s string) *PaymentOrderUpdate {
	pou.mutation.SetRoute(s)
	return pou
}

// SetNillableRoute sets the "route" field if the given value is not nil.
func (pou *PaymentOrderUpdate) SetNillableRoute(s *string) *PaymentOrderUpdate {
	if s != nil {
		pou.SetRoute(*s)
	}
	return pou
}

// SetRouteNote sets the "route_note" field.
func (pou *PaymentOrderUpdate) SetRouteNote(s string) *PaymentOrderUpdate {
	pou.mutation.SetRouteNote(s)
	return pou
}

// SetNillableRouteNote sets the "route_note" field if the given value is not nil.
func (pou *PaymentOrderUpdate) SetNillableRouteNote(s *string) *PaymentOrderUpdate {
	if s != nil {
		pou.SetRouteNote(*s)
	}
	return pou
}

// SetUpdatedAt sets the "updated_at" field.
func (pou *PaymentOrderUpdate) SetUpdatedAt(t time.Time) *PaymentOrderUpdate {
	pou.mutation.SetUpdatedAt(t)
	return pou
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (pou *PaymentOrderUpdate) SetNillableUpdatedAt(t *time.Time) *PaymentOrderUpdate {
	if t != nil {
		pou.SetUpdatedAt(*t)
	}
	return pou
}

// SetSettledAt sets the "settled_at" field.
func (pou *PaymentOrderUpdate) SetSettledAt(t time.Time) *PaymentOrderUpdate {
	pou.mutation.SetSettledAt(t)
	return pou
}

// SetNillableSettledAt sets the "settled_at" field if the given value is not nil.
func (pou *PaymentOrderUpdate) SetNillableSettledAt(t *time.Time) *PaymentOrderUpdate {
	if t != nil {
		pou.SetSettledAt(*t)
	}
	return pou
}

// ClearSettledAt clears the value of the "settled_at" field.
func (pou *PaymentOrderUpdate) ClearSettledAt() *PaymentOrderUpdate {
	pou.mutation.ClearSettledAt()
	return pou
}

// SetOfacReportDue sets the "ofac_report_due" field.
func (pou *PaymentOrderUpdate) SetOfacReportDue(t time.Time) *PaymentOrderUpdate {
	pou.mutation.SetOfacReportDue(t)
	return pou
}

// SetNillableOfacReportDue sets the "ofac_report_due" field if the given value is not nil.
func (pou *PaymentOrderUpdate) SetNillableOfacReportDue(t *time.Time) *PaymentOrderUpdate {
	if t != nil {
		pou.SetOfacReportDue(*t)
	}
	return pou
}

// ClearOfacReportDue clears the value of the "ofac_report_due" field.
func (pou *PaymentOrderUpdate) ClearOfacReportDue() *PaymentOrderUpdate {
	pou.mutation.ClearOfacReportDue()
	return pou
}

// SetSanctionsMatch sets the "sanctions_match" field.
func (pou *PaymentOrderUpdate) SetSanctionsMatch(s string) *PaymentOrderUpdate {
	pou.mutation.SetSanctionsMatch(s)
	return pou
}

// SetNillableSanctionsMatch sets the "sanctions_match" field if the given value is not nil.
func (pou *PaymentOrderUpdate) SetNillableSanctionsMatch(s *string) *PaymentOrderUpdate {
	if s != nil {
		pou.SetSanctionsMatch(*s)
	}
	return pou
}

// SetPaymentRef sets the "payment_ref" field.
func (pou *PaymentOrderUpdate) SetPaymentRef(s string) *PaymentOrderUpdate {
	pou.mutation.SetPaymentRef(s)
	return pou
}

// SetNillablePaymentRef sets the "payment_ref" field if the given value is not nil.
func (pou *PaymentOrderUpdate) SetNillablePaymentRef(s *string) *PaymentOrderUpdate {
	if s != nil {
		pou.SetPaymentRef(*s)
	}
	return pou
}

// SetObligationRef sets the "obligation_ref" field.
func (pou *PaymentOrderUpdate) SetObligationRef(s string) *PaymentOrderUpdate {
	pou.mutation.SetObligationRef(s)
	return pou
}

// SetNillableObligationRef sets the "obligation_ref" field if the given value is not nil.
func (pou *PaymentOrderUpdate) SetNillableObligationRef(s *string) *PaymentOrderUpdate {
	if s != nil {
		pou.SetObligationRef(*s)
	}
	return pou
}

// SetTokenized sets the "tokenized" field.
func (pou *PaymentOrderUpdate) SetTokenized(b bool) *PaymentOrderUpdate {
	pou.mutation.SetTokenized(b)
	return pou
}

// SetNillableTokenized sets the "tokenized" field if the given value is not nil.
func (pou *PaymentOrderUpdate) SetNillableTokenized(b *bool) *PaymentOrderUpdate {
	if b != nil {
		pou.SetTokenized(*b)
	}
	return pou
}

// SetReleased sets the "released" field.
func (pou *PaymentOrderUpdate) SetReleased(b bool) *PaymentOrderUpdate {
	pou.mutation.SetReleased(b)
	return pou
}

// SetNillableReleased sets the "released" field if the given value is not nil.
func (pou *PaymentOrderUpdate) SetNillableReleased(b *bool) *PaymentOrderUpdate {
	if b != nil {
		pou.SetReleased(*b)
	}
	return pou
}

// SetVersion sets the "version" field.
func (pou *PaymentOrderUpdate) SetVersion(i int) *PaymentOrderUpdate {
	pou.mutation.ResetVersion()
	pou.mutation.SetVersion(i)
	return pou
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (pou *PaymentOrderUpdate) SetNillableVersion(i *int) *PaymentOrderUpdate {
	if i != nil {
		pou.SetVersion(*i)
	}
	return pou
}

// AddVersion adds i to the "version" field.
func (pou *PaymentOrderUpdate) AddVersion(i int) *PaymentOrderUpdate {
	pou.mutation.AddVersion(i)
	return pou
}

// AddEventIDs adds the "events" edge to the OrderEvent entity by IDs.
func (pou *PaymentOrderUpdate) AddEventIDs(ids ...int) *PaymentOrderUpdate {
	pou.mutation.AddEventIDs(ids...)
	return pou
}

// AddEvents adds the "events" edges to the OrderEvent entity.
func (pou *PaymentOrderUpdate) AddEvents(o ...*OrderEvent) *PaymentOrderUpdate {
	ids := make([]int, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return pou.AddEventIDs(ids...)
}

// AddApprovalIDs adds the "approvals" edge to the Approval entity by IDs.
func (pou *PaymentOrderUpdate) AddApprovalIDs(ids ...int) *PaymentOrderUpdate {
	pou.mutation.AddApprovalIDs(ids...)
	return pou
}

// AddApprovals adds the "approvals" edges to the Approval entity.
func (pou *PaymentOrderUpdate) AddApprovals(a ...*Approval) *PaymentOrderUpdate {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return pou.AddApprovalIDs(ids...)
}

// Mutation returns the PaymentOrderMutation object of the builder.
func (pou *PaymentOrderUpdate) Mutation() *PaymentOrderMutation {
	return pou.mutation
}

// ClearEvents clears all "events" edges to the OrderEvent entity.
func (pou *PaymentOrderUpdate) ClearEvents() *PaymentOrderUpdate {
	pou.mutation.ClearEvents()
	return pou
}

// RemoveEventIDs removes the "events" edge to OrderEvent entities by IDs.
func (pou *PaymentOrderUpdate) RemoveEventIDs(ids ...int) *PaymentOrderUpdate {
	pou.mutation.RemoveEventIDs(ids...)
	return pou
}

// RemoveEvents removes "events" edges to OrderEvent entities.
func (pou *PaymentOrderUpdate) RemoveEvents(o ...*OrderEvent) *PaymentOrderUpdate {
	ids := make([]int, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return pou.RemoveEventIDs(ids...)
}

// ClearApprovals clears all "approvals" edges to the Approval entity.
func (pou *PaymentOrderUpdate) ClearApprovals() *PaymentOrderUpdate {
	pou.mutation.ClearApprovals()
	return pou
}

// RemoveApprovalIDs removes the "approvals" edge to Approval entities by IDs.
func (pou *PaymentOrderUpdate) RemoveApprovalIDs(ids ...int) *PaymentOrderUpdate {
	pou.mutation.RemoveApprovalIDs(ids...)
	return pou
}

// RemoveApprovals removes "approvals" edges to Approval entities.
func (pou *PaymentOrderUpdate) RemoveApprovals(a ...*Approval) *PaymentOrderUpdate {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return pou.RemoveApprovalIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pou *PaymentOrderUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, pou.sqlSave, pou.mutation, pou.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pou *PaymentOrderUpdate) SaveX(ctx context.Context) int {
	affected, err := pou.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pou *PaymentOrderUpdate) Exec(ctx context.Context) error {
	_, err := pou.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pou *PaymentOrderUpdate) ExecX(ctx context.Context) {
	if err := pou.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pou *PaymentOrderUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(paymentorder.Table, paymentorder.Columns, sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeString))
	if ps := pou.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if pou.mutation.FileIDCleared() {
		_spec.ClearField(paymentorder.FieldFileID, field.TypeString)
	}
	if pou.mutation.IdempotencyKeyCleared() {
		_spec.ClearField(paymentorder.FieldIdempotencyKey, field.TypeString)
	}
	if value, ok := pou.mutation.Status(); ok {
		_spec.SetField(paymentorder.FieldStatus, field.TypeString, value)
	}
	if value, ok := pou.mutation.IsoStatus(); ok {
		_spec.SetField(paymentorder.FieldIsoStatus, field.TypeString, value)
	}
	if value, ok := pou.mutation.ReasonCode(); ok {
		_spec.SetField(paymentorder.FieldReasonCode, field.TypeString, value)
	}
	if value, ok := pou.mutation.Route(); ok {
		_spec.SetField(paymentorder.FieldRoute, field.TypeString, value)
	}
	if value, ok := pou.mutation.RouteNote(); ok {
		_spec.SetField(paymentorder.FieldRouteNote, field.TypeString, value)
	}
	if value, ok := pou.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentorder.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := pou.mutation.SettledAt(); ok {
		_spec.SetField(paymentorder.FieldSettledAt, field.TypeTime, value)
	}
	if pou.mutation.SettledAtCleared() {
		_spec.ClearField(paymentorder.FieldSettledAt, field.TypeTime)
	}
	if value, ok := pou.mutation.OfacReportDue(); ok {
		_spec.SetField(paymentorder.FieldOfacReportDue, field.TypeTime, value)
	}
	if pou.mutation.OfacReportDueCleared() {
		_spec.ClearField(paymentorder.FieldOfacReportDue, field.TypeTime)
	}
	if value, ok := pou.mutation.SanctionsMatch(); ok {
		_spec.SetField(paymentorder.FieldSanctionsMatch, field.TypeString, value)
	}
	if value, ok := pou.mutation.PaymentRef(); ok {
		_spec.SetField(paymentorder.FieldPaymentRef, field.TypeString, value)
	}
	if value, ok := pou.mutation.ObligationRef(); ok {
		_spec.SetField(paymentorder.FieldObligationRef, field.TypeString, value)
	}
	if value, ok := pou.mutation.Tokenized(); ok {
		_spec.SetField(paymentorder.FieldTokenized, field.TypeBool, value)
	}
	if value, ok := pou.mutation.Released(); ok {
		_spec.SetField(paymentorder.FieldReleased, field.TypeBool, value)
	}
	if value, ok := pou.mutation.Version(); ok {
		_spec.SetField(paymentorder.FieldVersion, field.TypeInt, value)
	}
	if value, ok := pou.mutation.AddedVersion(); ok {
		_spec.AddField(paymentorder.FieldVersion, field.TypeInt, value)
	}
	if pou.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paymentorder.EventsTable,
			Columns: []string{paymentorder.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderevent.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pou.mutation.RemovedEventsIDs(); len(nodes) > 0 && !pou.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paymentorder.EventsTable,
			Columns: []string{paymentorder.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pou.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paymentorder.EventsTable,
			Columns: []string{paymentorder.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if pou.mutation.ApprovalsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paymentorder.ApprovalsTable,
			Columns: []string{paymentorder.ApprovalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(approval.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pou.mutation.RemovedApprovalsIDs(); len(nodes) > 0 && !pou.mutation.ApprovalsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paymentorder.ApprovalsTable,
			Columns: []string{paymentorder.ApprovalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(approval.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pou.mutation.ApprovalsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paymentorder.ApprovalsTable,
			Columns: []string{paymentorder.ApprovalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(approval.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pou.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pou.mutation.done = true
	return n, nil
}

// PaymentOrderUpdateOne is the builder for updating a single PaymentOrder entity.
type PaymentOrderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PaymentOrderMutation
}

// SetStatus sets the "status" field.
func (pouo *PaymentOrderUpdateOne) SetStatus(s string) *PaymentOrderUpdateOne {
	pouo.mutation.SetStatus(s)
	return pouo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (pouo *PaymentOrderUpdateOne) SetNillableStatus(s *string) *PaymentOrderUpdateOne {
	if s != nil {
		pouo.SetStatus(*s)
	}
	return pouo
}

// SetIsoStatus sets the "iso_status" field.
func (pouo *PaymentOrderUpdateOne) SetIsoStatus(s string) *PaymentOrderUpdateOne {
	pouo.mutation.SetIsoStatus(s)
	return pouo
}

// SetNillableIsoStatus sets the "iso_status" field if the given value is not nil.
func (pouo *PaymentOrderUpdateOne) SetNillableIsoStatus(s *string) *PaymentOrderUpdateOne {
	if s != nil {
		pouo.SetIsoStatus(*s)
	}
	return pouo
}

// SetReasonCode sets the "reason_code" field.
func (pouo *PaymentOrderUpdateOne) SetReasonCode(s string) *PaymentOrderUpdateOne {
	pouo.mutation.SetReasonCode(s)
	return pouo
}

// SetNillableReasonCode sets the "reason_code" field if the given value is not nil.
func (pouo *PaymentOrderUpdateOne) SetNillableReasonCode(s *string) *PaymentOrderUpdateOne {
	if s != nil {
		pouo.SetReasonCode(*s)
	}
	return pouo
}

// SetRoute sets the "route" field.
func (pouo *PaymentOrderUpdateOne) SetRoute(s string) *PaymentOrderUpdateOne {
	pouo.mutation.SetRoute(s)
	return pouo
}

// SetNillableRoute sets the "route" field if the given value is not nil.
func (pouo *PaymentOrderUpdateOne) SetNillableRoute(s *string) *PaymentOrderUpdateOne {
	if s != nil {
		pouo.SetRoute(*s)
	}
	return pouo
}

// SetRouteNote sets the "route_note" field.
func (pouo *PaymentOrderUpdateOne) SetRouteNote(s string) *PaymentOrderUpdateOne {
	pouo.mutation.SetRouteNote(s)
	return pouo
}

// SetNillableRouteNote sets the "route_note" field if the given value is not nil.
func (pouo *PaymentOrderUpdateOne) SetNillableRouteNote(s *string) *PaymentOrderUpdateOne {
	if s != nil {
		pouo.SetRouteNote(*s)
	}
	return pouo
}

// SetUpdatedAt sets the "updated_at" field.
func (pouo *PaymentOrderUpdateOne) SetUpdatedAt(t time.Time) *PaymentOrderUpdateOne {
	pouo.mutation.SetUpdatedAt(t)
	return pouo
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (pouo *PaymentOrderUpdateOne) SetNillableUpdatedAt(t *time.Time) *PaymentOrderUpdateOne {
	if t != nil {
		pouo.SetUpdatedAt(*t)
	}
	return pouo
}

// SetSettledAt sets the "settled_at" field.
func (pouo *PaymentOrderUpdateOne) SetSettledAt(t time.Time) *PaymentOrderUpdateOne {
	pouo.mutation.SetSettledAt(t)
	return pouo
}

// SetNillableSettledAt sets the "settled_at" field if the given value is not nil.
func (pouo *PaymentOrderUpdateOne) SetNillableSettledAt(t *time.Time) *PaymentOrderUpdateOne {
	if t != nil {
		pouo.SetSettledAt(*t)
	}
	return pouo
}

// ClearSettledAt clears the value of the "settled_at" field.
func (pouo *PaymentOrderUpdateOne) ClearSettledAt() *PaymentOrderUpdateOne {
	pouo.mutation.ClearSettledAt()
	return pouo
}

// SetOfacReportDue sets the "ofac_report_due" field.
func (pouo *PaymentOrderUpdateOne) SetOfacReportDue(t time.Time) *PaymentOrderUpdateOne {
	pouo.mutation.SetOfacReportDue(t)
	return pouo
}

// SetNillableOfacReportDue sets the "ofac_report_due" field if the given value is not nil.
func (pouo *PaymentOrderUpdateOne) SetNillableOfacReportDue(t *time.Time) *PaymentOrderUpdateOne {
	if t != nil {
		pouo.SetOfacReportDue(*t)
	}
	return pouo
}

// ClearOfacReportDue clears the value of the "ofac_report_due" field.
func (pouo *PaymentOrderUpdateOne) ClearOfacReportDue() *PaymentOrderUpdateOne {
	pouo.mutation.ClearOfacReportDue()
	return pouo
}

// SetSanctionsMatch sets the "sanctions_match" field.
func (pouo *PaymentOrderUpdateOne) SetSanctionsMatch(s string) *PaymentOrderUpdateOne {
	pouo.mutation.SetSanctionsMatch(s)
	return pouo
}

// SetNillableSanctionsMatch sets the "sanctions_match" field if the given value is not nil.
func (pouo *PaymentOrderUpdateOne) SetNillableSanctionsMatch(s *string) *PaymentOrderUpdateOne {
	if s != nil {
		pouo.SetSanctionsMatch(*s)
	}
	return pouo
}

// SetPaymentRef sets the "payment_ref" field.
func (pouo *PaymentOrderUpdateOne) SetPaymentRef(s string) *PaymentOrderUpdateOne {
	pouo.mutation.SetPaymentRef(s)
	return pouo
}

// SetNillablePaymentRef sets the "payment_ref" field if the given value is not nil.
func (pouo *PaymentOrderUpdateOne) SetNillablePaymentRef(s *string) *PaymentOrderUpdateOne {
	if s != nil {
		pouo.SetPaymentRef(*s)
	}
	return pouo
}

// SetObligationRef sets the "obligation_ref" field.
func (pouo *PaymentOrderUpdateOne) SetObligationRef(s string) *PaymentOrderUpdateOne {
	pouo.mutation.SetObligationRef(s)
	return pouo
}

// SetNillableObligationRef sets the "obligation_ref" field if the given value is not nil.
func (pouo *PaymentOrderUpdateOne) SetNillableObligationRef(s *string) *PaymentOrderUpdateOne {
	if s != nil {
		pouo.SetObligationRef(*s)
	}
	return pouo
}

// SetTokenized sets the "tokenized" field.
func (pouo *PaymentOrderUpdateOne) SetTokenized(b bool) *PaymentOrderUpdateOne {
	pouo.mutation.SetTokenized(b)
	return pouo
}

// SetNillableTokenized sets the "tokenized" field if the given value is not nil.
func (pouo *PaymentOrderUpdateOne) SetNillableTokenized(b *bool) *PaymentOrderUpdateOne {
	if b != nil {
		pouo.SetTokenized(*b)
	}
	return pouo
}

// SetReleased sets the "released" field.
func (pouo *PaymentOrderUpdateOne) SetReleased(b bool) *PaymentOrderUpdateOne {
	pouo.mutation.SetReleased(b)
	return pouo
}

// SetNillableReleased sets the "released" field if the given value is not nil.
func (pouo *PaymentOrderUpdateOne) SetNillableReleased(b *bool) *PaymentOrderUpdateOne {
	if b != nil {
		pouo.SetReleased(*b)
	}
	return pouo
}

// SetVersion sets the "version" field.
func (pouo *PaymentOrderUpdateOne) SetVersion(i int) *PaymentOrderUpdateOne {
	pouo.mutation.ResetVersion()
	pouo.mutation.SetVersion(i)
	return pouo
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (pouo *PaymentOrderUpdateOne) SetNillableVersion(i *int) *PaymentOrderUpdateOne {
	if i != nil {
		pouo.SetVersion(*i)
	}
	return pouo
}

// AddVersion adds i to the "version" field.
func (pouo *PaymentOrderUpdateOne) AddVersion(i int) *PaymentOrderUpdateOne {
	pouo.mutation.AddVersion(i)
	return pouo
}

// AddEventIDs adds the "events" edge to the OrderEvent entity by IDs.
func (pouo *PaymentOrderUpdateOne) AddEventIDs(ids ...int) *PaymentOrderUpdateOne {
	pouo.mutation.AddEventIDs(ids...)
	return pouo
}

// AddEvents adds the "events" edges to the OrderEvent entity.
func (pouo *PaymentOrderUpdateOne) AddEvents(o ...*OrderEvent) *PaymentOrderUpdateOne {
	ids := make([]int, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return pouo.AddEventIDs(ids...)
}

// AddApprovalIDs adds the "approvals" edge to the Approval entity by IDs.
func (pouo *PaymentOrderUpdateOne) AddApprovalIDs(ids ...int) *PaymentOrderUpdateOne {
	pouo.mutation.AddApprovalIDs(ids...)
	return pouo
}

// AddApprovals adds the "approvals" edges to the Approval entity.
func (pouo *PaymentOrderUpdateOne) AddApprovals(a ...*Approval) *PaymentOrderUpdateOne {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return pouo.AddApprovalIDs(ids...)
}

// Mutation returns the PaymentOrderMutation object of the builder.
func (pouo *PaymentOrderUpdateOne) Mutation() *PaymentOrderMutation {
	return pouo.mutation
}

// ClearEvents clears all "events" edges to the OrderEvent entity.
func (pouo *PaymentOrderUpdateOne) ClearEvents() *PaymentOrderUpdateOne {
	pouo.mutation.ClearEvents()
	return pouo
}

// RemoveEventIDs removes the "events" edge to OrderEvent entities by IDs.
func (pouo *PaymentOrderUpdateOne) RemoveEventIDs(ids ...int) *PaymentOrderUpdateOne {
	pouo.mutation.RemoveEventIDs(ids...)
	return pouo
}

// RemoveEvents removes "events" edges to OrderEvent entities.
func (pouo *PaymentOrderUpdateOne) RemoveEvents(o ...*OrderEvent) *PaymentOrderUpdateOne {
	ids := make([]int, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return pouo.RemoveEventIDs(ids...)
}

// ClearApprovals clears all "approvals" edges to the Approval entity.
func (pouo *PaymentOrderUpdateOne) ClearApprovals() *PaymentOrderUpdateOne {
	pouo.mutation.ClearApprovals()
	return pouo
}

// RemoveApprovalIDs removes the "approvals" edge to Approval entities by IDs.
func (pouo *PaymentOrderUpdateOne) RemoveApprovalIDs(ids ...int) *PaymentOrderUpdateOne {
	pouo.mutation.RemoveApprovalIDs(ids...)
	return pouo
}

// RemoveApprovals removes "approvals" edges to Approval entities.
func (pouo *PaymentOrderUpdateOne) RemoveApprovals(a ...*Approval) *PaymentOrderUpdateOne {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return pouo.RemoveApprovalIDs(ids...)
}

// Where appends a list predicates to the PaymentOrderUpdate builder.
func (pouo *PaymentOrderUpdateOne) Where(ps ...predicate.PaymentOrder) *PaymentOrderUpdateOne {
	pouo.mutation.Where(ps...)
	return pouo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (pouo *PaymentOrderUpdateOne) Select(field string, fields ...string) *PaymentOrderUpdateOne {
	pouo.fields = append([]string{field}, fields...)
	return pouo
}

// Save executes the query and returns the updated PaymentOrder entity.
func (pouo *PaymentOrderUpdateOne) Save(ctx context.Context) (*PaymentOrder, error) {
	return withHooks(ctx, pouo.sqlSave, pouo.mutation, pouo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pouo *PaymentOrderUpdateOne) SaveX(ctx context.Context) *PaymentOrder {
	node, err := pouo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (pouo *PaymentOrderUpdateOne) Exec(ctx context.Context) error {
	_, err := pouo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pouo *PaymentOrderUpdateOne) ExecX(ctx context.Context) {
	if err := pouo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pouo *PaymentOrderUpdateOne) sqlSave(ctx context.Context) (_node *PaymentOrder, err error) {
	_spec := sqlgraph.NewUpdateSpec(paymentorder.Table, paymentorder.Columns, sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeString))
	id, ok := pouo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PaymentOrder.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := pouo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, paymentorder.FieldID)
		for _, f := range fields {
			if !paymentorder.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != paymentorder.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := pouo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if pouo.mutation.FileIDCleared() {
		_spec.ClearField(paymentorder.FieldFileID, field.TypeString)
	}
	if pouo.mutation.IdempotencyKeyCleared() {
		_spec.ClearField(paymentorder.FieldIdempotencyKey, field.TypeString)
	}
	if value, ok := pouo.mutation.Status(); ok {
		_spec.SetField(paymentorder.FieldStatus, field.TypeString, value)
	}
	if value, ok := pouo.mutation.IsoStatus(); ok {
		_spec.SetField(paymentorder.FieldIsoStatus, field.TypeString, value)
	}
	if value, ok := pouo.mutation.ReasonCode(); ok {
		_spec.SetField(paymentorder.FieldReasonCode, field.TypeString, value)
	}
	if value, ok := pouo.mutation.Route(); ok {
		_spec.SetField(paymentorder.FieldRoute, field.TypeString, value)
	}
	if value, ok := pouo.mutation.RouteNote(); ok {
		_spec.SetField(paymentorder.FieldRouteNote, field.TypeString, value)
	}
	if value, ok := pouo.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentorder.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := pouo.mutation.SettledAt(); ok {
		_spec.SetField(paymentorder.FieldSettledAt, field.TypeTime, value)
	}
	if pouo.mutation.SettledAtCleared() {
		_spec.ClearField(paymentorder.FieldSettledAt, field.TypeTime)
	}
	if value, ok := pouo.mutation.OfacReportDue(); ok {
		_spec.SetField(paymentorder.FieldOfacReportDue, field.TypeTime, value)
	}
	if pouo.mutation.OfacReportDueCleared() {
		_spec.ClearField(paymentorder.FieldOfacReportDue, field.TypeTime)
	}
	if value, ok := pouo.mutation.SanctionsMatch(); ok {
		_spec.SetField(paymentorder.FieldSanctionsMatch, field.TypeString, value)
	}
	if value, ok := pouo.mutation.PaymentRef(); ok {
		_spec.SetField(paymentorder.FieldPaymentRef, field.TypeString, value)
	}
	if value, ok := pouo.mutation.ObligationRef(); ok {
		_spec.SetField(paymentorder.FieldObligationRef, field.TypeString, value)
	}
	if value, ok := pouo.mutation.Tokenized(); ok {
		_spec.SetField(paymentorder.FieldTokenized, field.TypeBool, value)
	}
	if value, ok := pouo.mutation.Released(); ok {
		_spec.SetField(paymentorder.FieldReleased, field.TypeBool, value)
	}
	if value, ok := pouo.mutation.Version(); ok {
		_spec.SetField(paymentorder.FieldVersion, field.TypeInt, value)
	}
	if value, ok := pouo.mutation.AddedVersion(); ok {
		_spec.AddField(paymentorder.FieldVersion, field.TypeInt, value)
	}
	if pouo.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paymentorder.EventsTable,
			Columns: []string{paymentorder.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderevent.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pouo.mutation.RemovedEventsIDs(); len(nodes) > 0 && !pouo.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paymentorder.EventsTable,
			Columns: []string{paymentorder.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pouo.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paymentorder.EventsTable,
			Columns: []string{paymentorder.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if pouo.mutation.ApprovalsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paymentorder.ApprovalsTable,
			Columns: []string{paymentorder.ApprovalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(approval.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pouo.mutation.RemovedApprovalsIDs(); len(nodes) > 0 && !pouo.mutation.ApprovalsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paymentorder.ApprovalsTable,
			Columns: []string{paymentorder.ApprovalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(approval.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pouo.mutation.ApprovalsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paymentorder.ApprovalsTable,
			Columns: []string{paymentorder.ApprovalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(approval.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PaymentOrder{config: pouo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, pouo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	pouo.mutation.done = true
	return _node, nil
}
