// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"reserve-interbank-settlement/services/payments-svc/ent/approval"
	"reserve-interbank-settlement/services/payments-svc/ent/orderevent"
	"reserve-interbank-settlement/services/payments-svc/ent/paymentorder"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PaymentOrderCreate is the builder for creating a PaymentOrder entity.
type PaymentOrderCreate struct {
	config
	mutation *PaymentOrderMutation
	hooks    []Hook
}

// SetOrganizationID sets the "organization_id" field.
func (poc *PaymentOrderCreate) SetOrganizationID(s string) *PaymentOrderCreate {
	poc.mutation.SetOrganizationID(s)
	return poc
}

// SetBankID sets the "bank_id" field.
func (poc *PaymentOrderCreate) SetBankID(s string) *PaymentOrderCreate {
	poc.mutation.SetBankID(s)
	return poc
}

// SetFileID sets the "file_id" field.
func (poc *PaymentOrderCreate) SetFileID(s string) *PaymentOrderCreate {
	poc.mutation.SetFileID(s)
	return poc
}

// SetNillableFileID sets the "file_id" field if the given value is not nil.
func (poc *PaymentOrderCreate) SetNillableFileID(s *string) *PaymentOrderCreate {
	if s != nil {
		poc.SetFileID(*s)
	}
	return poc
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (poc *PaymentOrderCreate) SetIdempotencyKey(s string) *PaymentOrderCreate {
	poc.mutation.SetIdempotencyKey(s)
	return poc
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (poc *PaymentOrderCreate) SetNillableIdempotencyKey(s *string) *PaymentOrderCreate {
	if s != nil {
		poc.SetIdempotencyKey(*s)
	}
	return poc
}

// SetRequestHash sets the "request_hash" field.
func (poc *PaymentOrderCreate) SetRequestHash(s string) *PaymentOrderCreate {
	poc.mutation.SetRequestHash(s)
	return poc
}

// SetEndToEndID sets the "end_to_end_id" field.
func (poc *PaymentOrderCreate) SetEndToEndID(s string) *PaymentOrderCreate {
	poc.mutation.SetEndToEndID(s)
	return poc
}

// SetUetr sets the "uetr" field.
func (poc *PaymentOrderCreate) SetUetr(s string) *PaymentOrderCreate {
	poc.mutation.SetUetr(s)
	return poc
}

// SetDebtorAccount sets the "debtor_account" field.
func (poc *PaymentOrderCreate) SetDebtorAccount(s string) *PaymentOrderCreate {
	poc.mutation.SetDebtorAccount(s)
	return poc
}

// SetCreditorName sets the "creditor_name" field.
func (poc *PaymentOrderCreate) SetCreditorName(s string) *PaymentOrderCreate {
	poc.mutation.SetCreditorName(s)
	return poc
}

// SetCreditorRouting sets the "creditor_routing" field.
func (poc *PaymentOrderCreate) SetCreditorRouting(s string) *PaymentOrderCreate {
	poc.mutation.SetCreditorRouting(s)
	return poc
}

// SetCreditorAccount sets the "creditor_account" field.
func (poc *PaymentOrderCreate) SetCreditorAccount(s string) *PaymentOrderCreate {
	poc.mutation.SetCreditorAccount(s)
	return poc
}

// SetAmount sets the "amount" field.
func (poc *PaymentOrderCreate) SetAmount(i int64) *PaymentOrderCreate {
	poc.mutation.SetAmount(i)
	return poc
}

// SetPriority sets the "priority" field.
func (poc *PaymentOrderCreate) SetPriority(s string) *PaymentOrderCreate {
	poc.mutation.SetPriority(s)
	return poc
}

// SetRemittance sets the "remittance" field.
func (poc *PaymentOrderCreate) SetRemittance(s string) *PaymentOrderCreate {
	poc.mutation.SetRemittance(s)
	return poc
}

// SetNillableRemittance sets the "remittance" field if the given value is not nil.
func (poc *PaymentOrderCreate) SetNillableRemittance(s *string) *PaymentOrderCreate {
	if s != nil {
		poc.SetRemittance(*s)
	}
	return poc
}

// SetStatus sets the "status" field.
func (poc *PaymentOrderCreate) SetStatus(s string) *PaymentOrderCreate {
	poc.mutation.SetStatus(s)
	return poc
}

// SetIsoStatus sets the "iso_status" field.
func (poc *PaymentOrderCreate) SetIsoStatus(s string) *PaymentOrderCreate {
	poc.mutation.SetIsoStatus(s)
	return poc
}

// SetReasonCode sets the "reason_code" field.
func (poc *PaymentOrderCreate) SetReasonCode(s string) *PaymentOrderCreate {
	poc.mutation.SetReasonCode(s)
	return poc
}

// SetNillableReasonCode sets the "reason_code" field if the given value is not nil.
func (poc *PaymentOrderCreate) SetNillableReasonCode(s *string) *PaymentOrderCreate {
	if s != nil {
		poc.SetReasonCode(*s)
	}
	return poc
}

// SetRoute sets the "route" field.
func (poc *PaymentOrderCreate) SetRoute(s string) *PaymentOrderCreate {
	poc.mutation.SetRoute(s)
	return poc
}

// SetNillableRoute sets the "route" field if the given value is not nil.
func (poc *PaymentOrderCreate) SetNillableRoute(s *string) *PaymentOrderCreate {
	if s != nil {
		poc.SetRoute(*s)
	}
	return poc
}

// SetRouteNote sets the "route_note" field.
func (poc *PaymentOrderCreate) SetRouteNote(s string) *PaymentOrderCreate {
	poc.mutation.SetRouteNote(s)
	return poc
}

// SetNillableRouteNote sets the "route_note" field if the given value is not nil.
func (poc *PaymentOrderCreate) SetNillableRouteNote(s *string) *PaymentOrderCreate {
	if s != nil {
		poc.SetRouteNote(*s)
	}
	return poc
}

// SetPayeeAccountStatus sets the "payee_account_status" field.
func (poc *PaymentOrderCreate) SetPayeeAccountStatus(s string) *PaymentOrderCreate {
	poc.mutation.SetPayeeAccountStatus(s)
	return poc
}

// SetPayeeNameMatch sets the "payee_name_match" field.
func (poc *PaymentOrderCreate) SetPayeeNameMatch(s string) *PaymentOrderCreate {
	poc.mutation.SetPayeeNameMatch(s)
	return poc
}

// SetPayeeRegisteredName sets the "payee_registered_name" field.
func (poc *PaymentOrderCreate) SetPayeeRegisteredName(s string) *PaymentOrderCreate {
	poc.mutation.SetPayeeRegisteredName(s)
	return poc
}

// SetNillablePayeeRegisteredName sets the "payee_registered_name" field if the given value is not nil.
func (poc *PaymentOrderCreate) SetNillablePayeeRegisteredName(s *string) *PaymentOrderCreate {
	if s != nil {
		poc.SetPayeeRegisteredName(*s)
	}
	return poc
}

// SetApprovalsRequired sets the "approvals_required" field.
func (poc *PaymentOrderCreate) SetApprovalsRequired(i int) *PaymentOrderCreate {
	poc.mutation.SetApprovalsRequired(i)
	return poc
}

// SetCreatedBy sets the "created_by" field.
func (poc *PaymentOrderCreate) SetCreatedBy(s string) *PaymentOrderCreate {
	poc.mutation.SetCreatedBy(s)
	return poc
}

// SetCreatedAt sets the "created_at" field.
func (poc *PaymentOrderCreate) SetCreatedAt(t time.Time) *PaymentOrderCreate {
	poc.mutation.SetCreatedAt(t)
	return poc
}

// SetUpdatedAt sets the "updated_at" field.
func (poc *PaymentOrderCreate) SetUpdatedAt(t time.Time) *PaymentOrderCreate {
	poc.mutation.SetUpdatedAt(t)
	return poc
}

// SetSettledAt sets the "settled_at" field.
func (poc *PaymentOrderCreate) SetSettledAt(t time.Time) *PaymentOrderCreate {
	poc.mutation.SetSettledAt(t)
	return poc
}

// SetNillableSettledAt sets the "settled_at" field if the given value is not nil.
func (poc *PaymentOrderCreate) SetNillableSettledAt(t *time.Time) *PaymentOrderCreate {
	if t != nil {
		poc.SetSettledAt(*t)
	}
	return poc
}

// SetOfacReportDue sets the "ofac_report_due" field.
func (poc *PaymentOrderCreate) SetOfacReportDue(t time.Time) *PaymentOrderCreate {
	poc.mutation.SetOfacReportDue(t)
	return poc
}

// SetNillableOfacReportDue sets the "ofac_report_due" field if the given value is not nil.
func (poc *PaymentOrderCreate) SetNillableOfacReportDue(t *time.Time) *PaymentOrderCreate {
	if t != nil {
		poc.SetOfacReportDue(*t)
	}
	return poc
}

// SetSanctionsMatch sets the "sanctions_match" field.
func (poc *PaymentOrderCreate) SetSanctionsMatch(s string) *PaymentOrderCreate {
	poc.mutation.SetSanctionsMatch(s)
	return poc
}

// SetNillableSanctionsMatch sets the "sanctions_match" field if the given value is not nil.
func (poc *PaymentOrderCreate) SetNillableSanctionsMatch(s *string) *PaymentOrderCreate {
	if s != nil {
		poc.SetSanctionsMatch(*s)
	}
	return poc
}

// SetPaymentRef sets the "payment_ref" field.
func (poc *PaymentOrderCreate) SetPaymentRef(s string) *PaymentOrderCreate {
	poc.mutation.SetPaymentRef(s)
	return poc
}

// SetNillablePaymentRef sets the "payment_ref" field if the given value is not nil.
func (poc *PaymentOrderCreate) SetNillablePaymentRef(s *string) *PaymentOrderCreate {
	if s != nil {
		poc.SetPaymentRef(*s)
	}
	return poc
}

// SetObligationRef sets the "obligation_ref" field.
func (poc *PaymentOrderCreate) SetObligationRef(s string) *PaymentOrderCreate {
	poc.mutation.SetObligationRef(s)
	return poc
}

// SetNillableObligationRef sets the "obligation_ref" field if the given value is not nil.
func (poc *PaymentOrderCreate) SetNillableObligationRef(s *string) *PaymentOrderCreate {
	if s != nil {
		poc.SetObligationRef(*s)
	}
	return poc
}

// SetTokenized sets the "tokenized" field.
func (poc *PaymentOrderCreate) SetTokenized(b bool) *PaymentOrderCreate {
	poc.mutation.SetTokenized(b)
	return poc
}

// SetNillableTokenized sets the "tokenized" field if the given value is not nil.
func (poc *PaymentOrderCreate) SetNillableTokenized(b *bool) *PaymentOrderCreate {
	if b != nil {
		poc.SetTokenized(*b)
	}
	return poc
}

// SetReleased sets the "released" field.
func (poc *PaymentOrderCreate) SetReleased(b bool) *PaymentOrderCreate {
	poc.mutation.SetReleased(b)
	return poc
}

// SetNillableReleased sets the "released" field if the given value is not nil.
func (poc *PaymentOrderCreate) SetNillableReleased(b *bool) *PaymentOrderCreate {
	if b != nil {
		poc.SetReleased(*b)
	}
	return poc
}

// SetVersion sets the "version" field.
func (poc *PaymentOrderCreate) SetVersion(i int) *PaymentOrderCreate {
	poc.mutation.SetVersion(i)
	return poc
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (poc *PaymentOrderCreate) SetNillableVersion(i *int) *PaymentOrderCreate {
	if i != nil {
		poc.SetVersion(*i)
	}
	return poc
}

// SetID sets the "id" field.
func (poc *PaymentOrderCreate) SetID(s string) *PaymentOrderCreate {
	poc.mutation.SetID(s)
	return poc
}

// AddEventIDs adds the "events" edge to the OrderEvent entity by IDs.
func (poc *PaymentOrderCreate) AddEventIDs(ids ...int) *PaymentOrderCreate {
	poc.mutation.AddEventIDs(ids...)
	return poc
}

// AddEvents adds the "events" edges to the OrderEvent entity.
func (poc *PaymentOrderCreate) AddEvents(o ...*OrderEvent) *PaymentOrderCreate {
	ids := make([]int, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return poc.AddEventIDs(ids...)
}

// AddApprovalIDs adds the "approvals" edge to the Approval entity by IDs.
func (poc *PaymentOrderCreate) AddApprovalIDs(ids ...int) *PaymentOrderCreate {
	poc.mutation.AddApprovalIDs(ids...)
	return poc
}

// AddApprovals adds the "approvals" edges to the Approval entity.
func (poc *PaymentOrderCreate) AddApprovals(a ...*Approval) *PaymentOrderCreate {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return poc.AddApprovalIDs(ids...)
}

// Mutation returns the PaymentOrderMutation object of the builder.
func (poc *PaymentOrderCreate) Mutation() *PaymentOrderMutation {
	return poc.mutation
}

// Save creates the PaymentOrder in the database.
func (poc *PaymentOrderCreate) Save(ctx context.Context) (*PaymentOrder, error) {
	poc.defaults()
	return withHooks(ctx, poc.sqlSave, poc.mutation, poc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (poc *PaymentOrderCreate) SaveX(ctx context.Context) *PaymentOrder {
	v, err := poc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (poc *PaymentOrderCreate) Exec(ctx context.Context) error {
	_, err := poc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (poc *PaymentOrderCreate) ExecX(ctx context.Context) {
	if err := poc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (poc *PaymentOrderCreate) defaults() {
	if _, ok := poc.mutation.Remittance(); !ok {
		v := paymentorder.DefaultRemittance
		poc.mutation.SetRemittance(v)
	}
	if _, ok := poc.mutation.ReasonCode(); !ok {
		v := paymentorder.DefaultReasonCode
		poc.mutation.SetReasonCode(v)
	}
	if _, ok := poc.mutation.Route(); !ok {
		v := paymentorder.DefaultRoute
		poc.mutation.SetRoute(v)
	}
	if _, ok := poc.mutation.RouteNote(); !ok {
		v := paymentorder.DefaultRouteNote
		poc.mutation.SetRouteNote(v)
	}
	if _, ok := poc.mutation.PayeeRegisteredName(); !ok {
		v := paymentorder.DefaultPayeeRegisteredName
		poc.mutation.SetPayeeRegisteredName(v)
	}
	if _, ok := poc.mutation.SanctionsMatch(); !ok {
		v := paymentorder.DefaultSanctionsMatch
		poc.mutation.SetSanctionsMatch(v)
	}
	if _, ok := poc.mutation.PaymentRef(); !ok {
		v := paymentorder.DefaultPaymentRef
		poc.mutation.SetPaymentRef(v)
	}
	if _, ok := poc.mutation.ObligationRef(); !ok {
		v := paymentorder.DefaultObligationRef
		poc.mutation.SetObligationRef(v)
	}
	if _, ok := poc.mutation.Tokenized(); !ok {
		v := paymentorder.DefaultTokenized
		poc.mutation.SetTokenized(v)
	}
	if _, ok := poc.mutation.Released(); !ok {
		v := paymentorder.DefaultReleased
		poc.mutation.SetReleased(v)
	}
	if _, ok := poc.mutation.Version(); !ok {
		v := paymentorder.DefaultVersion
		poc.mutation.SetVersion(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (poc *PaymentOrderCreate) check() error {
	if _, ok := poc.mutation.OrganizationID(); !ok {
		return &ValidationError{Name: "organization_id", err: errors.New(`ent: missing required field "PaymentOrder.organization_id"`)}
	}
	if v, ok := poc.mutation.OrganizationID(); ok {
		if err := paymentorder.OrganizationIDValidator(v); err != nil {
			return &ValidationError{Name: "organization_id", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.organization_id": %w`, err)}
		}
	}
	if _, ok := poc.mutation.BankID(); !ok {
		return &ValidationError{Name: "bank_id", err: errors.New(`ent: missing required field "PaymentOrder.bank_id"`)}
	}
	if v, ok := poc.mutation.BankID(); ok {
		if err := paymentorder.BankIDValidator(v); err != nil {
			return &ValidationError{Name: "bank_id", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.bank_id": %w`, err)}
		}
	}
	if _, ok := poc.mutation.RequestHash(); !ok {
		return &ValidationError{Name: "request_hash", err: errors.New(`ent: missing required field "PaymentOrder.request_hash"`)}
	}
	if _, ok := poc.mutation.EndToEndID(); !ok {
		return &ValidationError{Name: "end_to_end_id", err: errors.New(`ent: missing required field "PaymentOrder.end_to_end_id"`)}
	}
	if v, ok := poc.mutation.EndToEndID(); ok {
		if err := paymentorder.EndToEndIDValidator(v); err != nil {
			return &ValidationError{Name: "end_to_end_id", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.end_to_end_id": %w`, err)}
		}
	}
	if _, ok := poc.mutation.Uetr(); !ok {
		return &ValidationError{Name: "uetr", err: errors.New(`ent: missing required field "PaymentOrder.uetr"`)}
	}
	if v, ok := poc.mutation.Uetr(); ok {
		if err := paymentorder.UetrValidator(v); err != nil {
			return &ValidationError{Name: "uetr", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.uetr": %w`, err)}
		}
	}
	if _, ok := poc.mutation.DebtorAccount(); !ok {
		return &ValidationError{Name: "debtor_account", err: errors.New(`ent: missing required field "PaymentOrder.debtor_account"`)}
	}
	if v, ok := poc.mutation.DebtorAccount(); ok {
		if err := paymentorder.DebtorAccountValidator(v); err != nil {
			return &ValidationError{Name: "debtor_account", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.debtor_account": %w`, err)}
		}
	}
	if _, ok := poc.mutation.CreditorName(); !ok {
		return &ValidationError{Name: "creditor_name", err: errors.New(`ent: missing required field "PaymentOrder.creditor_name"`)}
	}
	if v, ok := poc.mutation.CreditorName(); ok {
		if err := paymentorder.CreditorNameValidator(v); err != nil {
			return &ValidationError{Name: "creditor_name", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.creditor_name": %w`, err)}
		}
	}
	if _, ok := poc.mutation.CreditorRouting(); !ok {
		return &ValidationError{Name: "creditor_routing", err: errors.New(`ent: missing required field "PaymentOrder.creditor_routing"`)}
	}
	if v, ok := poc.mutation.CreditorRouting(); ok {
		if err := paymentorder.CreditorRoutingValidator(v); err != nil {
			return &ValidationError{Name: "creditor_routing", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.creditor_routing": %w`, err)}
		}
	}
	if _, ok := poc.mutation.CreditorAccount(); !ok {
		return &ValidationError{Name: "creditor_account", err: errors.New(`ent: missing required field "PaymentOrder.creditor_account"`)}
	}
	if v, ok := poc.mutation.CreditorAccount(); ok {
		if err := paymentorder.CreditorAccountValidator(v); err != nil {
			return &ValidationError{Name: "creditor_account", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.creditor_account": %w`, err)}
		}
	}
	if _, ok := poc.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "PaymentOrder.amount"`)}
	}
	if v, ok := poc.mutation.Amount(); ok {
		if err := paymentorder.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.amount": %w`, err)}
		}
	}
	if _, ok := poc.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "PaymentOrder.priority"`)}
	}
	if _, ok := poc.mutation.Remittance(); !ok {
		return &ValidationError{Name: "remittance", err: errors.New(`ent: missing required field "PaymentOrder.remittance"`)}
	}
	if _, ok := poc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "PaymentOrder.status"`)}
	}
	if _, ok := poc.mutation.IsoStatus(); !ok {
		return &ValidationError{Name: "iso_status", err: errors.New(`ent: missing required field "PaymentOrder.iso_status"`)}
	}
	if _, ok := poc.mutation.ReasonCode(); !ok {
		return &ValidationError{Name: "reason_code", err: errors.New(`ent: missing required field "PaymentOrder.reason_code"`)}
	}
	if _, ok := poc.mutation.Route(); !ok {
		return &ValidationError{Name: "route", err: errors.New(`ent: missing required field "PaymentOrder.route"`)}
	}
	if _, ok := poc.mutation.RouteNote(); !ok {
		return &ValidationError{Name: "route_note", err: errors.New(`ent: missing required field "PaymentOrder.route_note"`)}
	}
	if _, ok := poc.mutation.PayeeAccountStatus(); !ok {
		return &ValidationError{Name: "payee_account_status", err: errors.New(`ent: missing required field "PaymentOrder.payee_account_status"`)}
	}
	if _, ok := poc.mutation.PayeeNameMatch(); !ok {
		return &ValidationError{Name: "payee_name_match", err: errors.New(`ent: missing required field "PaymentOrder.payee_name_match"`)}
	}
	if _, ok := poc.mutation.PayeeRegisteredName(); !ok {
		return &ValidationError{Name: "payee_registered_name", err: errors.New(`ent: missing required field "PaymentOrder.payee_registered_name"`)}
	}
	if _, ok := poc.mutation.ApprovalsRequired(); !ok {
		return &ValidationError{Name: "approvals_required", err: errors.New(`ent: missing required field "PaymentOrder.approvals_required"`)}
	}
	if _, ok := poc.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "PaymentOrder.created_by"`)}
	}
	if _, ok := poc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PaymentOrder.created_at"`)}
	}
	if _, ok := poc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PaymentOrder.updated_at"`)}
	}
	if _, ok := poc.mutation.SanctionsMatch(); !ok {
		return &ValidationError{Name: "sanctions_match", err: errors.New(`ent: missing required field "PaymentOrder.sanctions_match"`)}
	}
	if _, ok := poc.mutation.PaymentRef(); !ok {
		return &ValidationError{Name: "payment_ref", err: errors.New(`ent: missing required field "PaymentOrder.payment_ref"`)}
	}
	if _, ok := poc.mutation.ObligationRef(); !ok {
		return &ValidationError{Name: "obligation_ref", err: errors.New(`ent: missing required field "PaymentOrder.obligation_ref"`)}
	}
	if _, ok := poc.mutation.Tokenized(); !ok {
		return &ValidationError{Name: "tokenized", err: errors.New(`ent: missing required field "PaymentOrder.tokenized"`)}
	}
	if _, ok := poc.mutation.Released(); !ok {
		return &ValidationError{Name: "released", err: errors.New(`ent: missing required field "PaymentOrder.released"`)}
	}
	if _, ok := poc.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "PaymentOrder.version"`)}
	}
	return nil
}

func (poc *PaymentOrderCreate) sqlSave(ctx context.Context) (*PaymentOrder, error) {
	if err := poc.check(); err != nil {
		return nil, err
	}
	_node, _spec := poc.createSpec()
	if err := sqlgraph.CreateNode(ctx, poc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected PaymentOrder.ID type: %T", _spec.ID.Value)
		}
	}
	poc.mutation.id = &_node.ID
	poc.mutation.done = true
	return _node, nil
}

func (poc *PaymentOrderCreate) createSpec() (*PaymentOrder, *sqlgraph.CreateSpec) {
	var (
		_node = &PaymentOrder{config: poc.config}
		_spec = sqlgraph.NewCreateSpec(paymentorder.Table, sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeString))
	)
	if id, ok := poc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := poc.mutation.OrganizationID(); ok {
		_spec.SetField(paymentorder.FieldOrganizationID, field.TypeString, value)
		_node.OrganizationID = value
	}
	if value, ok := poc.mutation.BankID(); ok {
		_spec.SetField(paymentorder.FieldBankID, field.TypeString, value)
		_node.BankID = value
	}
	if value, ok := poc.mutation.FileID(); ok {
		_spec.SetField(paymentorder.FieldFileID, field.TypeString, value)
		_node.FileID = &value
	}
	if value, ok := poc.mutation.IdempotencyKey(); ok {
		_spec.SetField(paymentorder.FieldIdempotencyKey, field.TypeString, value)
		_node.IdempotencyKey = &value
	}
	if value, ok := poc.mutation.RequestHash(); ok {
		_spec.SetField(paymentorder.FieldRequestHash, field.TypeString, value)
		_node.RequestHash = value
	}
	if value, ok := poc.mutation.EndToEndID(); ok {
		_spec.SetField(paymentorder.FieldEndToEndID, field.TypeString, value)
		_node.EndToEndID = value
	}
	if value, ok := poc.mutation.Uetr(); ok {
		_spec.SetField(paymentorder.FieldUetr, field.TypeString, value)
		_node.Uetr = value
	}
	if value, ok := poc.mutation.DebtorAccount(); ok {
		_spec.SetField(paymentorder.FieldDebtorAccount, field.TypeString, value)
		_node.DebtorAccount = value
	}
	if value, ok := poc.mutation.CreditorName(); ok {
		_spec.SetField(paymentorder.FieldCreditorName, field.TypeString, value)
		_node.CreditorName = value
	}
	if value, ok := poc.mutation.CreditorRouting(); ok {
		_spec.SetField(paymentorder.FieldCreditorRouting, field.TypeString, value)
		_node.CreditorRouting = value
	}
	if value, ok := poc.mutation.CreditorAccount(); ok {
		_spec.SetField(paymentorder.FieldCreditorAccount, field.TypeString, value)
		_node.CreditorAccount = value
	}
	if value, ok := poc.mutation.Amount(); ok {
		_spec.SetField(paymentorder.FieldAmount, field.TypeInt64, value)
		_node.Amount = value
	}
	if value, ok := poc.mutation.Priority(); ok {
		_spec.SetField(paymentorder.FieldPriority, field.TypeString, value)
		_node.Priority = value
	}
	if value, ok := poc.mutation.Remittance(); ok {
		_spec.SetField(paymentorder.FieldRemittance, field.TypeString, value)
		_node.Remittance = value
	}
	if value, ok := poc.mutation.Status(); ok {
		_spec.SetField(paymentorder.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := poc.mutation.IsoStatus(); ok {
		_spec.SetField(paymentorder.FieldIsoStatus, field.TypeString, value)
		_node.IsoStatus = value
	}
	if value, ok := poc.mutation.ReasonCode(); ok {
		_spec.SetField(paymentorder.FieldReasonCode, field.TypeString, value)
		_node.ReasonCode = value
	}
	if value, ok := poc.mutation.Route(); ok {
		_spec.SetField(paymentorder.FieldRoute, field.TypeString, value)
		_node.Route = value
	}
	if value, ok := poc.mutation.RouteNote(); ok {
		_spec.SetField(paymentorder.FieldRouteNote, field.TypeString, value)
		_node.RouteNote = value
	}
	if value, ok := poc.mutation.PayeeAccountStatus(); ok {
		_spec.SetField(paymentorder.FieldPayeeAccountStatus, field.TypeString, value)
		_node.PayeeAccountStatus = value
	}
	if value, ok := poc.mutation.PayeeNameMatch(); ok {
		_spec.SetField(paymentorder.FieldPayeeNameMatch, field.TypeString, value)
		_node.PayeeNameMatch = value
	}
	if value, ok := poc.mutation.PayeeRegisteredName(); ok {
		_spec.SetField(paymentorder.FieldPayeeRegisteredName, field.TypeString, value)
		_node.PayeeRegisteredName = value
	}
	if value, ok := poc.mutation.ApprovalsRequired(); ok {
		_spec.SetField(paymentorder.FieldApprovalsRequired, field.TypeInt, value)
		_node.ApprovalsRequired = value
	}
	if value, ok := poc.mutation.CreatedBy(); ok {
		_spec.SetField(paymentorder.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := poc.mutation.CreatedAt(); ok {
		_spec.SetField(paymentorder.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := poc.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentorder.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := poc.mutation.SettledAt(); ok {
		_spec.SetField(paymentorder.FieldSettledAt, field.TypeTime, value)
		_node.SettledAt = &value
	}
	if value, ok := poc.mutation.OfacReportDue(); ok {
		_spec.SetField(paymentorder.FieldOfacReportDue, field.TypeTime, value)
		_node.OfacReportDue = &value
	}
	if value, ok := poc.mutation.SanctionsMatch(); ok {
		_spec.SetField(paymentorder.FieldSanctionsMatch, field.TypeString, value)
		_node.SanctionsMatch = value
	}
	if value, ok := poc.mutation.PaymentRef(); ok {
		_spec.SetField(paymentorder.FieldPaymentRef, field.TypeString, value)
		_node.PaymentRef = value
	}
	if value, ok := poc.mutation.ObligationRef(); ok {
		_spec.SetField(paymentorder.FieldObligationRef, field.TypeString, value)
		_node.ObligationRef = value
	}
	if value, ok := poc.mutation.Tokenized(); ok {
		_spec.SetField(paymentorder.FieldTokenized, field.TypeBool, value)
		_node.Tokenized = value
	}
	if value, ok := poc.mutation.Released(); ok {
		_spec.SetField(paymentorder.FieldReleased, field.TypeBool, value)
		_node.Released = value
	}
	if value, ok := poc.mutation.Version(); ok {
		_spec.SetField(paymentorder.FieldVersion, field.TypeInt, value)
		_node.Version = value
	}
	if nodes := poc.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paymentorder.EventsTable,
			Columns: []string{paymentorder.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := poc.mutation.ApprovalsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paymentorder.ApprovalsTable,
			Columns: []string{paymentorder.ApprovalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(approval.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PaymentOrderCreateBulk is the builder for creating many PaymentOrder entities in bulk.
type PaymentOrderCreateBulk struct {
	config
	err      error
	builders []*PaymentOrderCreate
}

// Save creates the PaymentOrder entities in the database.
func (pocb *PaymentOrderCreateBulk) Save(ctx context.Context) ([]*PaymentOrder, error) {
	if pocb.err != nil {
		return nil, pocb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(pocb.builders))
	nodes := make([]*PaymentOrder, len(pocb.builders))
	mutators := make([]Mutator, len(pocb.builders))
	for i := range pocb.builders {
		func(i int, root context.Context) {
			builder := pocb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PaymentOrderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pocb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pocb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pocb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pocb *PaymentOrderCreateBulk) SaveX(ctx context.Context) []*PaymentOrder {
	v, err := pocb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pocb *PaymentOrderCreateBulk) Exec(ctx context.Context) error {
	_, err := pocb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pocb *PaymentOrderCreateBulk) ExecX(ctx context.Context) {
	if err := pocb.Exec(ctx); err != nil {
		panic(err)
	}
}
