// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"reserve-interbank-settlement/services/payments-svc/ent/paymentfile"
	"reserve-interbank-settlement/services/payments-svc/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PaymentFileDelete is the builder for deleting a PaymentFile entity.
type PaymentFileDelete struct {
	config
	hooks    []Hook
	mutation *PaymentFileMutation
}

// Where appends a list predicates to the PaymentFileDelete builder.
func (pfd *PaymentFileDelete) Where(ps ...predicate.PaymentFile) *PaymentFileDelete {
	pfd.mutation.Where(ps...)
	return pfd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pfd *PaymentFileDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, pfd.sqlExec, pfd.mutation, pfd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (pfd *PaymentFileDelete) ExecX(ctx context.Context) int {
	n, err := pfd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pfd *PaymentFileDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(paymentfile.Table, sqlgraph.NewFieldSpec(paymentfile.FieldID, field.TypeString))
	if ps := pfd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, pfd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	pfd.mutation.done = true
	return affected, err
}

// PaymentFileDeleteOne is the builder for deleting a single PaymentFile entity.
type PaymentFileDeleteOne struct {
	pfd *PaymentFileDelete
}

// Where appends a list predicates to the PaymentFileDelete builder.
func (pfdo *PaymentFileDeleteOne) Where(ps ...predicate.PaymentFile) *PaymentFileDeleteOne {
	pfdo.pfd.mutation.Where(ps...)
	return pfdo
}

// Exec executes the deletion query.
func (pfdo *PaymentFileDeleteOne) Exec(ctx context.Context) error {
	n, err := pfdo.pfd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{paymentfile.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pfdo *PaymentFileDeleteOne) ExecX(ctx context.Context) {
	if err := pfdo.Exec(ctx); err != nil {
		panic(err)
	}
}
