// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"reserve-interbank-settlement/services/payments-svc/ent/paymentfile"
	"reserve-interbank-settlement/services/payments-svc/ent/predicate"
	"reserve-interbank-settlement/services/payments-svc/ent/schema"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// PaymentFileUpdate is the builder for updating PaymentFile entities.
type PaymentFileUpdate struct {
	config
	hooks    []Hook
	mutation *PaymentFileMutation
}

// Where appends a list predicates to the PaymentFileUpdate builder.
func (pfu *PaymentFileUpdate) Where(ps ...predicate.PaymentFile) *PaymentFileUpdate {
	pfu.mutation.Where(ps...)
	return pfu
}

// SetRejections sets the "rejections" field.
func (pfu *PaymentFileUpdate) SetRejections(s []schema.Rejection) *PaymentFileUpdate {
	pfu.mutation.SetRejections(s)
	return pfu
}

// AppendRejections appends s to the "rejections" field.
func (pfu *PaymentFileUpdate) AppendRejections(s []schema.Rejection) *PaymentFileUpdate {
	pfu.mutation.AppendRejections(s)
	return pfu
}

// ClearRejections clears the value of the "rejections" field.
func (pfu *PaymentFileUpdate) ClearRejections() *PaymentFileUpdate {
	pfu.mutation.ClearRejections()
	return pfu
}

// Mutation returns the PaymentFileMutation object of the builder.
func (pfu *PaymentFileUpdate) Mutation() *PaymentFileMutation {
	return pfu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pfu *PaymentFileUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, pfu.sqlSave, pfu.mutation, pfu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pfu *PaymentFileUpdate) SaveX(ctx context.Context) int {
	affected, err := pfu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pfu *PaymentFileUpdate) Exec(ctx context.Context) error {
	_, err := pfu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pfu *PaymentFileUpdate) ExecX(ctx context.Context) {
	if err := pfu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pfu *PaymentFileUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(paymentfile.Table, paymentfile.Columns, sqlgraph.NewFieldSpec(paymentfile.FieldID, field.TypeString))
	if ps := pfu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pfu.mutation.Rejections(); ok {
		_spec.SetField(paymentfile.FieldRejections, field.TypeJSON, value)
	}
	if value, ok := pfu.mutation.AppendedRejections(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, paymentfile.FieldRejections, value)
		})
	}
	if pfu.mutation.RejectionsCleared() {
		_spec.ClearField(paymentfile.FieldRejections, field.TypeJSON)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pfu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentfile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pfu.mutation.done = true
	return n, nil
}

// PaymentFileUpdateOne is the builder for updating a single PaymentFile entity.
type PaymentFileUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PaymentFileMutation
}

// SetRejections sets the "rejections" field.
func (pfuo *PaymentFileUpdateOne) SetRejections(s []schema.Rejection) *PaymentFileUpdateOne {
	pfuo.mutation.SetRejections(s)
	return pfuo
}

// AppendRejections appends s to the "rejections" field.
func (pfuo *PaymentFileUpdateOne) AppendRejections(s []schema.Rejection) *PaymentFileUpdateOne {
	pfuo.mutation.AppendRejections(s)
	return pfuo
}

// ClearRejections clears the value of the "rejections" field.
func (pfuo *PaymentFileUpdateOne) ClearRejections() *PaymentFileUpdateOne {
	pfuo.mutation.ClearRejections()
	return pfuo
}

// Mutation returns the PaymentFileMutation object of the builder.
func (pfuo *PaymentFileUpdateOne) Mutation() *PaymentFileMutation {
	return pfuo.mutation
}

// Where appends a list predicates to the PaymentFileUpdate builder.
func (pfuo *PaymentFileUpdateOne) Where(ps ...predicate.PaymentFile) *PaymentFileUpdateOne {
	pfuo.mutation.Where(ps...)
	return pfuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (pfuo *PaymentFileUpdateOne) Select(field string, fields ...string) *PaymentFileUpdateOne {
	pfuo.fields = append([]string{field}, fields...)
	return pfuo
}

// Save executes the query and returns the updated PaymentFile entity.
func (pfuo *PaymentFileUpdateOne) Save(ctx context.Context) (*PaymentFile, error) {
	return withHooks(ctx, pfuo.sqlSave, pfuo.mutation, pfuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pfuo *PaymentFileUpdateOne) SaveX(ctx context.Context) *PaymentFile {
	node, err := pfuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (pfuo *PaymentFileUpdateOne) Exec(ctx context.Context) error {
	_, err := pfuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pfuo *PaymentFileUpdateOne) ExecX(ctx context.Context) {
	if err := pfuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pfuo *PaymentFileUpdateOne) sqlSave(ctx context.Context) (_node *PaymentFile, err error) {
	_spec := sqlgraph.NewUpdateSpec(paymentfile.Table, paymentfile.Columns, sqlgraph.NewFieldSpec(paymentfile.FieldID, field.TypeString))
	id, ok := pfuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PaymentFile.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := pfuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, paymentfile.FieldID)
		for _, f := range fields {
			if !paymentfile.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != paymentfile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := pfuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pfuo.mutation.Rejections(); ok {
		_spec.SetField(paymentfile.FieldRejections, field.TypeJSON, value)
	}
	if value, ok := pfuo.mutation.AppendedRejections(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, paymentfile.FieldRejections, value)
		})
	}
	if pfuo.mutation.RejectionsCleared() {
		_spec.ClearField(paymentfile.FieldRejections, field.TypeJSON)
	}
	_node = &PaymentFile{config: pfuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, pfuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentfile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	pfuo.mutation.done = true
	return _node, nil
}
