// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"reserve-interbank-settlement/services/payments-svc/ent/predicate"
	"reserve-interbank-settlement/services/payments-svc/ent/reconciliation"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ReconciliationDelete is the builder for deleting a Reconciliation entity.
type ReconciliationDelete struct {
	config
	hooks    []Hook
	mutation *ReconciliationMutation
}

// Where appends a list predicates to the ReconciliationDelete builder.
func (rd *ReconciliationDelete) Where(ps ...predicate.Reconciliation) *ReconciliationDelete {
	rd.mutation.Where(ps...)
	return rd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (rd *ReconciliationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, rd.sqlExec, rd.mutation, rd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (rd *ReconciliationDelete) ExecX(ctx context.Context) int {
	n, err := rd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (rd *ReconciliationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(reconciliation.Table, sqlgraph.NewFieldSpec(reconciliation.FieldID, field.TypeString))
	if ps := rd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, rd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	rd.mutation.done = true
	return affected, err
}

// ReconciliationDeleteOne is the builder for deleting a single Reconciliation entity.
type ReconciliationDeleteOne struct {
	rd *ReconciliationDelete
}

// Where appends a list predicates to the ReconciliationDelete builder.
func (rdo *ReconciliationDeleteOne) Where(ps ...predicate.Reconciliation) *ReconciliationDeleteOne {
	rdo.rd.mutation.Where(ps...)
	return rdo
}

// Exec executes the deletion query.
func (rdo *ReconciliationDeleteOne) Exec(ctx context.Context) error {
	n, err := rdo.rd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{reconciliation.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (rdo *ReconciliationDeleteOne) ExecX(ctx context.Context) {
	if err := rdo.Exec(ctx); err != nil {
		panic(err)
	}
}
