// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"reserve-interbank-settlement/services/payments-svc/ent/reconciliation"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ReconciliationCreate is the builder for creating a Reconciliation entity.
type ReconciliationCreate struct {
	config
	mutation *ReconciliationMutation
	hooks    []Hook
}

// SetAt sets the "at" field.
func (rc *ReconciliationCreate) SetAt(t time.Time) *ReconciliationCreate {
	rc.mutation.SetAt(t)
	return rc
}

// SetFedBalance sets the "fed_balance" field.
func (rc *ReconciliationCreate) SetFedBalance(i int64) *ReconciliationCreate {
	rc.mutation.SetFedBalance(i)
	return rc
}

// SetReservePool sets the "reserve_pool" field.
func (rc *ReconciliationCreate) SetReservePool(i int64) *ReconciliationCreate {
	rc.mutation.SetReservePool(i)
	return rc
}

// SetReconciliationBreak sets the "reconciliation_break" field.
func (rc *ReconciliationCreate) SetReconciliationBreak(b bool) *ReconciliationCreate {
	rc.mutation.SetReconciliationBreak(b)
	return rc
}

// SetInvariants sets the "invariants" field.
func (rc *ReconciliationCreate) SetInvariants(b bool) *ReconciliationCreate {
	rc.mutation.SetInvariants(b)
	return rc
}

// SetID sets the "id" field.
func (rc *ReconciliationCreate) SetID(s string) *ReconciliationCreate {
	rc.mutation.SetID(s)
	return rc
}

// Mutation returns the ReconciliationMutation object of the builder.
func (rc *ReconciliationCreate) Mutation() *ReconciliationMutation {
	return rc.mutation
}

// Save creates the Reconciliation in the database.
func (rc *ReconciliationCreate) Save(ctx context.Context) (*Reconciliation, error) {
	return withHooks(ctx, rc.sqlSave, rc.mutation, rc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (rc *ReconciliationCreate) SaveX(ctx context.Context) *Reconciliation {
	v, err := rc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rc *ReconciliationCreate) Exec(ctx context.Context) error {
	_, err := rc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rc *ReconciliationCreate) ExecX(ctx context.Context) {
	if err := rc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rc *ReconciliationCreate) check() error {
	if _, ok := rc.mutation.At(); !ok {
		return &ValidationError{Name: "at", err: errors.New(`ent: missing required field "Reconciliation.at"`)}
	}
	if _, ok := rc.mutation.FedBalance(); !ok {
		return &ValidationError{Name: "fed_balance", err: errors.New(`ent: missing required field "Reconciliation.fed_balance"`)}
	}
	if _, ok := rc.mutation.ReservePool(); !ok {
		return &ValidationError{Name: "reserve_pool", err: errors.New(`ent: missing required field "Reconciliation.reserve_pool"`)}
	}
	if _, ok := rc.mutation.ReconciliationBreak(); !ok {
		return &ValidationError{Name: "reconciliation_break", err: errors.New(`ent: missing required field "Reconciliation.reconciliation_break"`)}
	}
	if _, ok := rc.mutation.Invariants(); !ok {
		return &ValidationError{Name: "invariants", err: errors.New(`ent: missing required field "Reconciliation.invariants"`)}
	}
	return nil
}

func (rc *ReconciliationCreate) sqlSave(ctx context.Context) (*Reconciliation, error) {
	if err := rc.check(); err != nil {
		return nil, err
	}
	_node, _spec := rc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Reconciliation.ID type: %T", _spec.ID.Value)
		}
	}
	rc.mutation.id = &_node.ID
	rc.mutation.done = true
	return _node, nil
}

func (rc *ReconciliationCreate) createSpec() (*Reconciliation, *sqlgraph.CreateSpec) {
	var (
		_node = &Reconciliation{config: rc.config}
		_spec = sqlgraph.NewCreateSpec(reconciliation.Table, sqlgraph.NewFieldSpec(reconciliation.FieldID, field.TypeString))
	)
	if id, ok := rc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := rc.mutation.At(); ok {
		_spec.SetField(reconciliation.FieldAt, field.TypeTime, value)
		_node.At = value
	}
	if value, ok := rc.mutation.FedBalance(); ok {
		_spec.SetField(reconciliation.FieldFedBalance, field.TypeInt64, value)
		_node.FedBalance = value
	}
	if value, ok := rc.mutation.ReservePool(); ok {
		_spec.SetField(reconciliation.FieldReservePool, field.TypeInt64, value)
		_node.ReservePool = value
	}
	if value, ok := rc.mutation.ReconciliationBreak(); ok {
		_spec.SetField(reconciliation.FieldReconciliationBreak, field.TypeBool, value)
		_node.ReconciliationBreak = value
	}
	if value, ok := rc.mutation.Invariants(); ok {
		_spec.SetField(reconciliation.FieldInvariants, field.TypeBool, value)
		_node.Invariants = value
	}
	return _node, _spec
}

// ReconciliationCreateBulk is the builder for creating many Reconciliation entities in bulk.
type ReconciliationCreateBulk struct {
	config
	err      error
	builders []*ReconciliationCreate
}

// Save creates the Reconciliation entities in the database.
func (rcb *ReconciliationCreateBulk) Save(ctx context.Context) ([]*Reconciliation, error) {
	if rcb.err != nil {
		return nil, rcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(rcb.builders))
	nodes := make([]*Reconciliation, len(rcb.builders))
	mutators := make([]Mutator, len(rcb.builders))
	for i := range rcb.builders {
		func(i int, root context.Context) {
			builder := rcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ReconciliationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rcb *ReconciliationCreateBulk) SaveX(ctx context.Context) []*Reconciliation {
	v, err := rcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rcb *ReconciliationCreateBulk) Exec(ctx context.Context) error {
	_, err := rcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rcb *ReconciliationCreateBulk) ExecX(ctx context.Context) {
	if err := rcb.Exec(ctx); err != nil {
		panic(err)
	}
}
