// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"reserve-interbank-settlement/services/payments-svc/ent/reconciliation"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Reconciliation is the model entity for the Reconciliation schema.
type Reconciliation struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// At holds the value of the "at" field.
	At time.Time `json:"at,omitempty"`
	// FedBalance holds the value of the "fed_balance" field.
	FedBalance int64 `json:"fed_balance,omitempty"`
	// ReservePool holds the value of the "reserve_pool" field.
	ReservePool int64 `json:"reserve_pool,omitempty"`
	// ReconciliationBreak holds the value of the "reconciliation_break" field.
	ReconciliationBreak bool `json:"reconciliation_break,omitempty"`
	// Invariants holds the value of the "invariants" field.
	Invariants   bool `json:"invariants,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Reconciliation) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case reconciliation.FieldReconciliationBreak, reconciliation.FieldInvariants:
			values[i] = new(sql.NullBool)
		case reconciliation.FieldFedBalance, reconciliation.FieldReservePool:
			values[i] = new(sql.NullInt64)
		case reconciliation.FieldID:
			values[i] = new(sql.NullString)
		case reconciliation.FieldAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Reconciliation fields.
func (r *Reconciliation) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case reconciliation.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				r.ID = value.String
			}
		case reconciliation.FieldAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field at", values[i])
			} else if value.Valid {
				r.At = value.Time
			}
		case reconciliation.FieldFedBalance:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field fed_balance", values[i])
			} else if value.Valid {
				r.FedBalance = value.Int64
			}
		case reconciliation.FieldReservePool:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reserve_pool", values[i])
			} else if value.Valid {
				r.ReservePool = value.Int64
			}
		case reconciliation.FieldReconciliationBreak:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field reconciliation_break", values[i])
			} else if value.Valid {
				r.ReconciliationBreak = value.Bool
			}
		case reconciliation.FieldInvariants:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field invariants", values[i])
			} else if value.Valid {
				r.Invariants = value.Bool
			}
		default:
			r.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Reconciliation.
// This includes values selected through modifiers, order, etc.
func (r *Reconciliation) Value(name string) (ent.Value, error) {
	return r.selectValues.Get(name)
}

// Update returns a builder for updating this Reconciliation.
// Note that you need to call Reconciliation.Unwrap() before calling this method if this Reconciliation
// was returned from a transaction, and the transaction was committed or rolled back.
func (r *Reconciliation) Update() *ReconciliationUpdateOne {
	return NewReconciliationClient(r.config).UpdateOne(r)
}

// Unwrap unwraps the Reconciliation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (r *Reconciliation) Unwrap() *Reconciliation {
	_tx, ok := r.config.driver.(*txDriver)
	if !ok {
		panic("ent: Reconciliation is not a transactional entity")
	}
	r.config.driver = _tx.drv
	return r
}

// String implements the fmt.Stringer.
func (r *Reconciliation) String() string {
	var builder strings.Builder
	builder.WriteString("Reconciliation(")
	builder.WriteString(fmt.Sprintf("id=%v, ", r.ID))
	builder.WriteString("at=")
	builder.WriteString(r.At.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("fed_balance=")
	builder.WriteString(fmt.Sprintf("%v", r.FedBalance))
	builder.WriteString(", ")
	builder.WriteString("reserve_pool=")
	builder.WriteString(fmt.Sprintf("%v", r.ReservePool))
	builder.WriteString(", ")
	builder.WriteString("reconciliation_break=")
	builder.WriteString(fmt.Sprintf("%v", r.ReconciliationBreak))
	builder.WriteString(", ")
	builder.WriteString("invariants=")
	builder.WriteString(fmt.Sprintf("%v", r.Invariants))
	builder.WriteByte(')')
	return builder.String()
}

// Reconciliations is a parsable slice of Reconciliation.
type Reconciliations []*Reconciliation
