// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"reserve-interbank-settlement/services/payments-svc/ent/webhooksubscription"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// WebhookSubscription is the model entity for the WebhookSubscription schema.
type WebhookSubscription struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// OrganizationID holds the value of the "organization_id" field.
	OrganizationID string `json:"organization_id,omitempty"`
	// URL holds the value of the "url" field.
	URL string `json:"url,omitempty"`
	// SecretSealed holds the value of the "secret_sealed" field.
	SecretSealed []byte `json:"-"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy string `json:"created_by,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WebhookSubscription) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case webhooksubscription.FieldSecretSealed:
			values[i] = new([]byte)
		case webhooksubscription.FieldID, webhooksubscription.FieldOrganizationID, webhooksubscription.FieldURL, webhooksubscription.FieldCreatedBy:
			values[i] = new(sql.NullString)
		case webhooksubscription.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WebhookSubscription fields.
func (ws *WebhookSubscription) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case webhooksubscription.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				ws.ID = value.String
			}
		case webhooksubscription.FieldOrganizationID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field organization_id", values[i])
			} else if value.Valid {
				ws.OrganizationID = value.String
			}
		case webhooksubscription.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				ws.URL = value.String
			}
		case webhooksubscription.FieldSecretSealed:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field secret_sealed", values[i])
			} else if value != nil {
				ws.SecretSealed = *value
			}
		case webhooksubscription.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				ws.CreatedBy = value.String
			}
		case webhooksubscription.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ws.CreatedAt = value.Time
			}
		default:
			ws.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the WebhookSubscription.
// This includes values selected through modifiers, order, etc.
func (ws *WebhookSubscription) Value(name string) (ent.Value, error) {
	return ws.selectValues.Get(name)
}

// Update returns a builder for updating this WebhookSubscription.
// Note that you need to call WebhookSubscription.Unwrap() before calling this method if this WebhookSubscription
// was returned from a transaction, and the transaction was committed or rolled back.
func (ws *WebhookSubscription) Update() *WebhookSubscriptionUpdateOne {
	return NewWebhookSubscriptionClient(ws.config).UpdateOne(ws)
}

// Unwrap unwraps the WebhookSubscription entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ws *WebhookSubscription) Unwrap() *WebhookSubscription {
	_tx, ok := ws.config.driver.(*txDriver)
	if !ok {
		panic("ent: WebhookSubscription is not a transactional entity")
	}
	ws.config.driver = _tx.drv
	return ws
}

// String implements the fmt.Stringer.
func (ws *WebhookSubscription) String() string {
	var builder strings.Builder
	builder.WriteString("WebhookSubscription(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ws.ID))
	builder.WriteString("organization_id=")
	builder.WriteString(ws.OrganizationID)
	builder.WriteString(", ")
	builder.WriteString("url=")
	builder.WriteString(ws.URL)
	builder.WriteString(", ")
	builder.WriteString("secret_sealed=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(ws.CreatedBy)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(ws.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// WebhookSubscriptions is a parsable slice of WebhookSubscription.
type WebhookSubscriptions []*WebhookSubscription
