// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"reserve-interbank-settlement/services/payments-svc/ent/webhookdelivery"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// WebhookDelivery is the model entity for the WebhookDelivery schema.
type WebhookDelivery struct {
	config `json:"-"`
	// ID of the ent.
	// msg_<UUIDv7>: the webhook-id, ordered
	ID string `json:"id,omitempty"`
	// SubscriptionID holds the value of the "subscription_id" field.
	SubscriptionID string `json:"subscription_id,omitempty"`
	// OrganizationID holds the value of the "organization_id" field.
	OrganizationID string `json:"organization_id,omitempty"`
	// EventType holds the value of the "event_type" field.
	EventType string `json:"event_type,omitempty"`
	// Payload holds the value of the "payload" field.
	Payload []byte `json:"payload,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Attempts holds the value of the "attempts" field.
	Attempts int `json:"attempts,omitempty"`
	// LastCode holds the value of the "last_code" field.
	LastCode int `json:"last_code,omitempty"`
	// LastError holds the value of the "last_error" field.
	LastError string `json:"last_error,omitempty"`
	// NextAttemptAt holds the value of the "next_attempt_at" field.
	NextAttemptAt time.Time `json:"next_attempt_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WebhookDelivery) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case webhookdelivery.FieldPayload:
			values[i] = new([]byte)
		case webhookdelivery.FieldAttempts, webhookdelivery.FieldLastCode:
			values[i] = new(sql.NullInt64)
		case webhookdelivery.FieldID, webhookdelivery.FieldSubscriptionID, webhookdelivery.FieldOrganizationID, webhookdelivery.FieldEventType, webhookdelivery.FieldStatus, webhookdelivery.FieldLastError:
			values[i] = new(sql.NullString)
		case webhookdelivery.FieldNextAttemptAt, webhookdelivery.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WebhookDelivery fields.
func (wd *WebhookDelivery) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case webhookdelivery.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				wd.ID = value.String
			}
		case webhookdelivery.FieldSubscriptionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subscription_id", values[i])
			} else if value.Valid {
				wd.SubscriptionID = value.String
			}
		case webhookdelivery.FieldOrganizationID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field organization_id", values[i])
			} else if value.Valid {
				wd.OrganizationID = value.String
			}
		case webhookdelivery.FieldEventType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_type", values[i])
			} else if value.Valid {
				wd.EventType = value.String
			}
		case webhookdelivery.FieldPayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field payload", values[i])
			} else if value != nil {
				wd.Payload = *value
			}
		case webhookdelivery.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				wd.Status = value.String
			}
		case webhookdelivery.FieldAttempts:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attempts", values[i])
			} else if value.Valid {
				wd.Attempts = int(value.Int64)
			}
		case webhookdelivery.FieldLastCode:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field last_code", values[i])
			} else if value.Valid {
				wd.LastCode = int(value.Int64)
			}
		case webhookdelivery.FieldLastError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error", values[i])
			} else if value.Valid {
				wd.LastError = value.String
			}
		case webhookdelivery.FieldNextAttemptAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field next_attempt_at", values[i])
			} else if value.Valid {
				wd.NextAttemptAt = value.Time
			}
		case webhookdelivery.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				wd.CreatedAt = value.Time
			}
		default:
			wd.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the WebhookDelivery.
// This includes values selected through modifiers, order, etc.
func (wd *WebhookDelivery) Value(name string) (ent.Value, error) {
	return wd.selectValues.Get(name)
}

// Update returns a builder for updating this WebhookDelivery.
// Note that you need to call WebhookDelivery.Unwrap() before calling this method if this WebhookDelivery
// was returned from a transaction, and the transaction was committed or rolled back.
func (wd *WebhookDelivery) Update() *WebhookDeliveryUpdateOne {
	return NewWebhookDeliveryClient(wd.config).UpdateOne(wd)
}

// Unwrap unwraps the WebhookDelivery entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (wd *WebhookDelivery) Unwrap() *WebhookDelivery {
	_tx, ok := wd.config.driver.(*txDriver)
	if !ok {
		panic("ent: WebhookDelivery is not a transactional entity")
	}
	wd.config.driver = _tx.drv
	return wd
}

// String implements the fmt.Stringer.
func (wd *WebhookDelivery) String() string {
	var builder strings.Builder
	builder.WriteString("WebhookDelivery(")
	builder.WriteString(fmt.Sprintf("id=%v, ", wd.ID))
	builder.WriteString("subscription_id=")
	builder.WriteString(wd.SubscriptionID)
	builder.WriteString(", ")
	builder.WriteString("organization_id=")
	builder.WriteString(wd.OrganizationID)
	builder.WriteString(", ")
	builder.WriteString("event_type=")
	builder.WriteString(wd.EventType)
	builder.WriteString(", ")
	builder.WriteString("payload=")
	builder.WriteString(fmt.Sprintf("%v", wd.Payload))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(wd.Status)
	builder.WriteString(", ")
	builder.WriteString("attempts=")
	builder.WriteString(fmt.Sprintf("%v", wd.Attempts))
	builder.WriteString(", ")
	builder.WriteString("last_code=")
	builder.WriteString(fmt.Sprintf("%v", wd.LastCode))
	builder.WriteString(", ")
	builder.WriteString("last_error=")
	builder.WriteString(wd.LastError)
	builder.WriteString(", ")
	builder.WriteString("next_attempt_at=")
	builder.WriteString(wd.NextAttemptAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(wd.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// WebhookDeliveries is a parsable slice of WebhookDelivery.
type WebhookDeliveries []*WebhookDelivery
