// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"reserve-interbank-settlement/services/payments-svc/ent/predicate"
	"reserve-interbank-settlement/services/payments-svc/ent/webhookdelivery"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WebhookDeliveryQuery is the builder for querying WebhookDelivery entities.
type WebhookDeliveryQuery struct {
	config
	ctx        *QueryContext
	order      []webhookdelivery.OrderOption
	inters     []Interceptor
	predicates []predicate.WebhookDelivery
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the WebhookDeliveryQuery builder.
func (wdq *WebhookDeliveryQuery) Where(ps ...predicate.WebhookDelivery) *WebhookDeliveryQuery {
	wdq.predicates = append(wdq.predicates, ps...)
	return wdq
}

// Limit the number of records to be returned by this query.
func (wdq *WebhookDeliveryQuery) Limit(limit int) *WebhookDeliveryQuery {
	wdq.ctx.Limit = &limit
	return wdq
}

// Offset to start from.
func (wdq *WebhookDeliveryQuery) Offset(offset int) *WebhookDeliveryQuery {
	wdq.ctx.Offset = &offset
	return wdq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (wdq *WebhookDeliveryQuery) Unique(unique bool) *WebhookDeliveryQuery {
	wdq.ctx.Unique = &unique
	return wdq
}

// Order specifies how the records should be ordered.
func (wdq *WebhookDeliveryQuery) Order(o ...webhookdelivery.OrderOption) *WebhookDeliveryQuery {
	wdq.order = append(wdq.order, o...)
	return wdq
}

// First returns the first WebhookDelivery entity from the query.
// Returns a *NotFoundError when no WebhookDelivery was found.
func (wdq *WebhookDeliveryQuery) First(ctx context.Context) (*WebhookDelivery, error) {
	nodes, err := wdq.Limit(1).All(setContextOp(ctx, wdq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{webhookdelivery.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (wdq *WebhookDeliveryQuery) FirstX(ctx context.Context) *WebhookDelivery {
	node, err := wdq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first WebhookDelivery ID from the query.
// Returns a *NotFoundError when no WebhookDelivery ID was found.
func (wdq *WebhookDeliveryQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = wdq.Limit(1).IDs(setContextOp(ctx, wdq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{webhookdelivery.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (wdq *WebhookDeliveryQuery) FirstIDX(ctx context.Context) string {
	id, err := wdq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single WebhookDelivery entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one WebhookDelivery entity is found.
// Returns a *NotFoundError when no WebhookDelivery entities are found.
func (wdq *WebhookDeliveryQuery) Only(ctx context.Context) (*WebhookDelivery, error) {
	nodes, err := wdq.Limit(2).All(setContextOp(ctx, wdq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{webhookdelivery.Label}
	default:
		return nil, &NotSingularError{webhookdelivery.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (wdq *WebhookDeliveryQuery) OnlyX(ctx context.Context) *WebhookDelivery {
	node, err := wdq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only WebhookDelivery ID in the query.
// Returns a *NotSingularError when more than one WebhookDelivery ID is found.
// Returns a *NotFoundError when no entities are found.
func (wdq *WebhookDeliveryQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = wdq.Limit(2).IDs(setContextOp(ctx, wdq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{webhookdelivery.Label}
	default:
		err = &NotSingularError{webhookdelivery.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (wdq *WebhookDeliveryQuery) OnlyIDX(ctx context.Context) string {
	id, err := wdq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of WebhookDeliveries.
func (wdq *WebhookDeliveryQuery) All(ctx context.Context) ([]*WebhookDelivery, error) {
	ctx = setContextOp(ctx, wdq.ctx, ent.OpQueryAll)
	if err := wdq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*WebhookDelivery, *WebhookDeliveryQuery]()
	return withInterceptors[[]*WebhookDelivery](ctx, wdq, qr, wdq.inters)
}

// AllX is like All, but panics if an error occurs.
func (wdq *WebhookDeliveryQuery) AllX(ctx context.Context) []*WebhookDelivery {
	nodes, err := wdq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of WebhookDelivery IDs.
func (wdq *WebhookDeliveryQuery) IDs(ctx context.Context) (ids []string, err error) {
	if wdq.ctx.Unique == nil && wdq.path != nil {
		wdq.Unique(true)
	}
	ctx = setContextOp(ctx, wdq.ctx, ent.OpQueryIDs)
	if err = wdq.Select(webhookdelivery.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (wdq *WebhookDeliveryQuery) IDsX(ctx context.Context) []string {
	ids, err := wdq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (wdq *WebhookDeliveryQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, wdq.ctx, ent.OpQueryCount)
	if err := wdq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, wdq, querierCount[*WebhookDeliveryQuery](), wdq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (wdq *WebhookDeliveryQuery) CountX(ctx context.Context) int {
	count, err := wdq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (wdq *WebhookDeliveryQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, wdq.ctx, ent.OpQueryExist)
	switch _, err := wdq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (wdq *WebhookDeliveryQuery) ExistX(ctx context.Context) bool {
	exist, err := wdq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the WebhookDeliveryQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (wdq *WebhookDeliveryQuery) Clone() *WebhookDeliveryQuery {
	if wdq == nil {
		return nil
	}
	return &WebhookDeliveryQuery{
		config:     wdq.config,
		ctx:        wdq.ctx.Clone(),
		order:      append([]webhookdelivery.OrderOption{}, wdq.order...),
		inters:     append([]Interceptor{}, wdq.inters...),
		predicates: append([]predicate.WebhookDelivery{}, wdq.predicates...),
		// clone intermediate query.
		sql:  wdq.sql.Clone(),
		path: wdq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		SubscriptionID string `json:"subscription_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.WebhookDelivery.Query().
//		GroupBy(webhookdelivery.FieldSubscriptionID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (wdq *WebhookDeliveryQuery) GroupBy(field string, fields ...string) *WebhookDeliveryGroupBy {
	wdq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &WebhookDeliveryGroupBy{build: wdq}
	grbuild.flds = &wdq.ctx.Fields
	grbuild.label = webhookdelivery.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		SubscriptionID string `json:"subscription_id,omitempty"`
//	}
//
//	client.WebhookDelivery.Query().
//		Select(webhookdelivery.FieldSubscriptionID).
//		Scan(ctx, &v)
func (wdq *WebhookDeliveryQuery) Select(fields ...string) *WebhookDeliverySelect {
	wdq.ctx.Fields = append(wdq.ctx.Fields, fields...)
	sbuild := &WebhookDeliverySelect{WebhookDeliveryQuery: wdq}
	sbuild.label = webhookdelivery.Label
	sbuild.flds, sbuild.scan = &wdq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a WebhookDeliverySelect configured with the given aggregations.
func (wdq *WebhookDeliveryQuery) Aggregate(fns ...AggregateFunc) *WebhookDeliverySelect {
	return wdq.Select().Aggregate(fns...)
}

func (wdq *WebhookDeliveryQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range wdq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, wdq); err != nil {
				return err
			}
		}
	}
	for _, f := range wdq.ctx.Fields {
		if !webhookdelivery.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if wdq.path != nil {
		prev, err := wdq.path(ctx)
		if err != nil {
			return err
		}
		wdq.sql = prev
	}
	return nil
}

func (wdq *WebhookDeliveryQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*WebhookDelivery, error) {
	var (
		nodes = []*WebhookDelivery{}
		_spec = wdq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*WebhookDelivery).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &WebhookDelivery{config: wdq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(wdq.modifiers) > 0 {
		_spec.Modifiers = wdq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, wdq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (wdq *WebhookDeliveryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := wdq.querySpec()
	if len(wdq.modifiers) > 0 {
		_spec.Modifiers = wdq.modifiers
	}
	_spec.Node.Columns = wdq.ctx.Fields
	if len(wdq.ctx.Fields) > 0 {
		_spec.Unique = wdq.ctx.Unique != nil && *wdq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, wdq.driver, _spec)
}

func (wdq *WebhookDeliveryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(webhookdelivery.Table, webhookdelivery.Columns, sqlgraph.NewFieldSpec(webhookdelivery.FieldID, field.TypeString))
	_spec.From = wdq.sql
	if unique := wdq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if wdq.path != nil {
		_spec.Unique = true
	}
	if fields := wdq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, webhookdelivery.FieldID)
		for i := range fields {
			if fields[i] != webhookdelivery.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := wdq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := wdq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := wdq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := wdq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (wdq *WebhookDeliveryQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(wdq.driver.Dialect())
	t1 := builder.Table(webhookdelivery.Table)
	columns := wdq.ctx.Fields
	if len(columns) == 0 {
		columns = webhookdelivery.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if wdq.sql != nil {
		selector = wdq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if wdq.ctx.Unique != nil && *wdq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range wdq.modifiers {
		m(selector)
	}
	for _, p := range wdq.predicates {
		p(selector)
	}
	for _, p := range wdq.order {
		p(selector)
	}
	if offset := wdq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := wdq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (wdq *WebhookDeliveryQuery) ForUpdate(opts ...sql.LockOption) *WebhookDeliveryQuery {
	if wdq.driver.Dialect() == dialect.Postgres {
		wdq.Unique(false)
	}
	wdq.modifiers = append(wdq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return wdq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (wdq *WebhookDeliveryQuery) ForShare(opts ...sql.LockOption) *WebhookDeliveryQuery {
	if wdq.driver.Dialect() == dialect.Postgres {
		wdq.Unique(false)
	}
	wdq.modifiers = append(wdq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return wdq
}

// WebhookDeliveryGroupBy is the group-by builder for WebhookDelivery entities.
type WebhookDeliveryGroupBy struct {
	selector
	build *WebhookDeliveryQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (wdgb *WebhookDeliveryGroupBy) Aggregate(fns ...AggregateFunc) *WebhookDeliveryGroupBy {
	wdgb.fns = append(wdgb.fns, fns...)
	return wdgb
}

// Scan applies the selector query and scans the result into the given value.
func (wdgb *WebhookDeliveryGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, wdgb.build.ctx, ent.OpQueryGroupBy)
	if err := wdgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WebhookDeliveryQuery, *WebhookDeliveryGroupBy](ctx, wdgb.build, wdgb, wdgb.build.inters, v)
}

func (wdgb *WebhookDeliveryGroupBy) sqlScan(ctx context.Context, root *WebhookDeliveryQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(wdgb.fns))
	for _, fn := range wdgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*wdgb.flds)+len(wdgb.fns))
		for _, f := range *wdgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*wdgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := wdgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// WebhookDeliverySelect is the builder for selecting fields of WebhookDelivery entities.
type WebhookDeliverySelect struct {
	*WebhookDeliveryQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (wds *WebhookDeliverySelect) Aggregate(fns ...AggregateFunc) *WebhookDeliverySelect {
	wds.fns = append(wds.fns, fns...)
	return wds
}

// Scan applies the selector query and scans the result into the given value.
func (wds *WebhookDeliverySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, wds.ctx, ent.OpQuerySelect)
	if err := wds.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WebhookDeliveryQuery, *WebhookDeliverySelect](ctx, wds.WebhookDeliveryQuery, wds, wds.inters, v)
}

func (wds *WebhookDeliverySelect) sqlScan(ctx context.Context, root *WebhookDeliveryQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(wds.fns))
	for _, fn := range wds.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*wds.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := wds.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
