// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"reserve-interbank-settlement/services/payments-svc/ent/predicate"
	"reserve-interbank-settlement/services/payments-svc/ent/webhooksubscription"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WebhookSubscriptionUpdate is the builder for updating WebhookSubscription entities.
type WebhookSubscriptionUpdate struct {
	config
	hooks    []Hook
	mutation *WebhookSubscriptionMutation
}

// Where appends a list predicates to the WebhookSubscriptionUpdate builder.
func (wsu *WebhookSubscriptionUpdate) Where(ps ...predicate.WebhookSubscription) *WebhookSubscriptionUpdate {
	wsu.mutation.Where(ps...)
	return wsu
}

// Mutation returns the WebhookSubscriptionMutation object of the builder.
func (wsu *WebhookSubscriptionUpdate) Mutation() *WebhookSubscriptionMutation {
	return wsu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (wsu *WebhookSubscriptionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, wsu.sqlSave, wsu.mutation, wsu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wsu *WebhookSubscriptionUpdate) SaveX(ctx context.Context) int {
	affected, err := wsu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (wsu *WebhookSubscriptionUpdate) Exec(ctx context.Context) error {
	_, err := wsu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wsu *WebhookSubscriptionUpdate) ExecX(ctx context.Context) {
	if err := wsu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (wsu *WebhookSubscriptionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(webhooksubscription.Table, webhooksubscription.Columns, sqlgraph.NewFieldSpec(webhooksubscription.FieldID, field.TypeString))
	if ps := wsu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if n, err = sqlgraph.UpdateNodes(ctx, wsu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{webhooksubscription.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	wsu.mutation.done = true
	return n, nil
}

// WebhookSubscriptionUpdateOne is the builder for updating a single WebhookSubscription entity.
type WebhookSubscriptionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WebhookSubscriptionMutation
}

// Mutation returns the WebhookSubscriptionMutation object of the builder.
func (wsuo *WebhookSubscriptionUpdateOne) Mutation() *WebhookSubscriptionMutation {
	return wsuo.mutation
}

// Where appends a list predicates to the WebhookSubscriptionUpdate builder.
func (wsuo *WebhookSubscriptionUpdateOne) Where(ps ...predicate.WebhookSubscription) *WebhookSubscriptionUpdateOne {
	wsuo.mutation.Where(ps...)
	return wsuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (wsuo *WebhookSubscriptionUpdateOne) Select(field string, fields ...string) *WebhookSubscriptionUpdateOne {
	wsuo.fields = append([]string{field}, fields...)
	return wsuo
}

// Save executes the query and returns the updated WebhookSubscription entity.
func (wsuo *WebhookSubscriptionUpdateOne) Save(ctx context.Context) (*WebhookSubscription, error) {
	return withHooks(ctx, wsuo.sqlSave, wsuo.mutation, wsuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wsuo *WebhookSubscriptionUpdateOne) SaveX(ctx context.Context) *WebhookSubscription {
	node, err := wsuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (wsuo *WebhookSubscriptionUpdateOne) Exec(ctx context.Context) error {
	_, err := wsuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wsuo *WebhookSubscriptionUpdateOne) ExecX(ctx context.Context) {
	if err := wsuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (wsuo *WebhookSubscriptionUpdateOne) sqlSave(ctx context.Context) (_node *WebhookSubscription, err error) {
	_spec := sqlgraph.NewUpdateSpec(webhooksubscription.Table, webhooksubscription.Columns, sqlgraph.NewFieldSpec(webhooksubscription.FieldID, field.TypeString))
	id, ok := wsuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WebhookSubscription.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := wsuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, webhooksubscription.FieldID)
		for _, f := range fields {
			if !webhooksubscription.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != webhooksubscription.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := wsuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &WebhookSubscription{config: wsuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, wsuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{webhooksubscription.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	wsuo.mutation.done = true
	return _node, nil
}
