// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"reserve-interbank-settlement/services/payments-svc/ent/predicate"
	"reserve-interbank-settlement/services/payments-svc/ent/webhooksubscription"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WebhookSubscriptionQuery is the builder for querying WebhookSubscription entities.
type WebhookSubscriptionQuery struct {
	config
	ctx        *QueryContext
	order      []webhooksubscription.OrderOption
	inters     []Interceptor
	predicates []predicate.WebhookSubscription
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the WebhookSubscriptionQuery builder.
func (wsq *WebhookSubscriptionQuery) Where(ps ...predicate.WebhookSubscription) *WebhookSubscriptionQuery {
	wsq.predicates = append(wsq.predicates, ps...)
	return wsq
}

// Limit the number of records to be returned by this query.
func (wsq *WebhookSubscriptionQuery) Limit(limit int) *WebhookSubscriptionQuery {
	wsq.ctx.Limit = &limit
	return wsq
}

// Offset to start from.
func (wsq *WebhookSubscriptionQuery) Offset(offset int) *WebhookSubscriptionQuery {
	wsq.ctx.Offset = &offset
	return wsq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (wsq *WebhookSubscriptionQuery) Unique(unique bool) *WebhookSubscriptionQuery {
	wsq.ctx.Unique = &unique
	return wsq
}

// Order specifies how the records should be ordered.
func (wsq *WebhookSubscriptionQuery) Order(o ...webhooksubscription.OrderOption) *WebhookSubscriptionQuery {
	wsq.order = append(wsq.order, o...)
	return wsq
}

// First returns the first WebhookSubscription entity from the query.
// Returns a *NotFoundError when no WebhookSubscription was found.
func (wsq *WebhookSubscriptionQuery) First(ctx context.Context) (*WebhookSubscription, error) {
	nodes, err := wsq.Limit(1).All(setContextOp(ctx, wsq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{webhooksubscription.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (wsq *WebhookSubscriptionQuery) FirstX(ctx context.Context) *WebhookSubscription {
	node, err := wsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first WebhookSubscription ID from the query.
// Returns a *NotFoundError when no WebhookSubscription ID was found.
func (wsq *WebhookSubscriptionQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = wsq.Limit(1).IDs(setContextOp(ctx, wsq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{webhooksubscription.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (wsq *WebhookSubscriptionQuery) FirstIDX(ctx context.Context) string {
	id, err := wsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single WebhookSubscription entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one WebhookSubscription entity is found.
// Returns a *NotFoundError when no WebhookSubscription entities are found.
func (wsq *WebhookSubscriptionQuery) Only(ctx context.Context) (*WebhookSubscription, error) {
	nodes, err := wsq.Limit(2).All(setContextOp(ctx, wsq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{webhooksubscription.Label}
	default:
		return nil, &NotSingularError{webhooksubscription.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (wsq *WebhookSubscriptionQuery) OnlyX(ctx context.Context) *WebhookSubscription {
	node, err := wsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only WebhookSubscription ID in the query.
// Returns a *NotSingularError when more than one WebhookSubscription ID is found.
// Returns a *NotFoundError when no entities are found.
func (wsq *WebhookSubscriptionQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = wsq.Limit(2).IDs(setContextOp(ctx, wsq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{webhooksubscription.Label}
	default:
		err = &NotSingularError{webhooksubscription.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (wsq *WebhookSubscriptionQuery) OnlyIDX(ctx context.Context) string {
	id, err := wsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of WebhookSubscriptions.
func (wsq *WebhookSubscriptionQuery) All(ctx context.Context) ([]*WebhookSubscription, error) {
	ctx = setContextOp(ctx, wsq.ctx, ent.OpQueryAll)
	if err := wsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*WebhookSubscription, *WebhookSubscriptionQuery]()
	return withInterceptors[[]*WebhookSubscription](ctx, wsq, qr, wsq.inters)
}

// AllX is like All, but panics if an error occurs.
func (wsq *WebhookSubscriptionQuery) AllX(ctx context.Context) []*WebhookSubscription {
	nodes, err := wsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of WebhookSubscription IDs.
func (wsq *WebhookSubscriptionQuery) IDs(ctx context.Context) (ids []string, err error) {
	if wsq.ctx.Unique == nil && wsq.path != nil {
		wsq.Unique(true)
	}
	ctx = setContextOp(ctx, wsq.ctx, ent.OpQueryIDs)
	if err = wsq.Select(webhooksubscription.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (wsq *WebhookSubscriptionQuery) IDsX(ctx context.Context) []string {
	ids, err := wsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (wsq *WebhookSubscriptionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, wsq.ctx, ent.OpQueryCount)
	if err := wsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, wsq, querierCount[*WebhookSubscriptionQuery](), wsq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (wsq *WebhookSubscriptionQuery) CountX(ctx context.Context) int {
	count, err := wsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (wsq *WebhookSubscriptionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, wsq.ctx, ent.OpQueryExist)
	switch _, err := wsq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (wsq *WebhookSubscriptionQuery) ExistX(ctx context.Context) bool {
	exist, err := wsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the WebhookSubscriptionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (wsq *WebhookSubscriptionQuery) Clone() *WebhookSubscriptionQuery {
	if wsq == nil {
		return nil
	}
	return &WebhookSubscriptionQuery{
		config:     wsq.config,
		ctx:        wsq.ctx.Clone(),
		order:      append([]webhooksubscription.OrderOption{}, wsq.order...),
		inters:     append([]Interceptor{}, wsq.inters...),
		predicates: append([]predicate.WebhookSubscription{}, wsq.predicates...),
		// clone intermediate query.
		sql:  wsq.sql.Clone(),
		path: wsq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		OrganizationID string `json:"organization_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.WebhookSubscription.Query().
//		GroupBy(webhooksubscription.FieldOrganizationID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (wsq *WebhookSubscriptionQuery) GroupBy(field string, fields ...string) *WebhookSubscriptionGroupBy {
	wsq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &WebhookSubscriptionGroupBy{build: wsq}
	grbuild.flds = &wsq.ctx.Fields
	grbuild.label = webhooksubscription.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		OrganizationID string `json:"organization_id,omitempty"`
//	}
//
//	client.WebhookSubscription.Query().
//		Select(webhooksubscription.FieldOrganizationID).
//		Scan(ctx, &v)
func (wsq *WebhookSubscriptionQuery) Select(fields ...string) *WebhookSubscriptionSelect {
	wsq.ctx.Fields = append(wsq.ctx.Fields, fields...)
	sbuild := &WebhookSubscriptionSelect{WebhookSubscriptionQuery: wsq}
	sbuild.label = webhooksubscription.Label
	sbuild.flds, sbuild.scan = &wsq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a WebhookSubscriptionSelect configured with the given aggregations.
func (wsq *WebhookSubscriptionQuery) Aggregate(fns ...AggregateFunc) *WebhookSubscriptionSelect {
	return wsq.Select().Aggregate(fns...)
}

func (wsq *WebhookSubscriptionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range wsq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, wsq); err != nil {
				return err
			}
		}
	}
	for _, f := range wsq.ctx.Fields {
		if !webhooksubscription.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if wsq.path != nil {
		prev, err := wsq.path(ctx)
		if err != nil {
			return err
		}
		wsq.sql = prev
	}
	return nil
}

func (wsq *WebhookSubscriptionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*WebhookSubscription, error) {
	var (
		nodes = []*WebhookSubscription{}
		_spec = wsq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*WebhookSubscription).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &WebhookSubscription{config: wsq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(wsq.modifiers) > 0 {
		_spec.Modifiers = wsq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, wsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (wsq *WebhookSubscriptionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := wsq.querySpec()
	if len(wsq.modifiers) > 0 {
		_spec.Modifiers = wsq.modifiers
	}
	_spec.Node.Columns = wsq.ctx.Fields
	if len(wsq.ctx.Fields) > 0 {
		_spec.Unique = wsq.ctx.Unique != nil && *wsq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, wsq.driver, _spec)
}

func (wsq *WebhookSubscriptionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(webhooksubscription.Table, webhooksubscription.Columns, sqlgraph.NewFieldSpec(webhooksubscription.FieldID, field.TypeString))
	_spec.From = wsq.sql
	if unique := wsq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if wsq.path != nil {
		_spec.Unique = true
	}
	if fields := wsq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, webhooksubscription.FieldID)
		for i := range fields {
			if fields[i] != webhooksubscription.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := wsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := wsq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := wsq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := wsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (wsq *WebhookSubscriptionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(wsq.driver.Dialect())
	t1 := builder.Table(webhooksubscription.Table)
	columns := wsq.ctx.Fields
	if len(columns) == 0 {
		columns = webhooksubscription.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if wsq.sql != nil {
		selector = wsq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if wsq.ctx.Unique != nil && *wsq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range wsq.modifiers {
		m(selector)
	}
	for _, p := range wsq.predicates {
		p(selector)
	}
	for _, p := range wsq.order {
		p(selector)
	}
	if offset := wsq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := wsq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (wsq *WebhookSubscriptionQuery) ForUpdate(opts ...sql.LockOption) *WebhookSubscriptionQuery {
	if wsq.driver.Dialect() == dialect.Postgres {
		wsq.Unique(false)
	}
	wsq.modifiers = append(wsq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return wsq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (wsq *WebhookSubscriptionQuery) ForShare(opts ...sql.LockOption) *WebhookSubscriptionQuery {
	if wsq.driver.Dialect() == dialect.Postgres {
		wsq.Unique(false)
	}
	wsq.modifiers = append(wsq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return wsq
}

// WebhookSubscriptionGroupBy is the group-by builder for WebhookSubscription entities.
type WebhookSubscriptionGroupBy struct {
	selector
	build *WebhookSubscriptionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (wsgb *WebhookSubscriptionGroupBy) Aggregate(fns ...AggregateFunc) *WebhookSubscriptionGroupBy {
	wsgb.fns = append(wsgb.fns, fns...)
	return wsgb
}

// Scan applies the selector query and scans the result into the given value.
func (wsgb *WebhookSubscriptionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, wsgb.build.ctx, ent.OpQueryGroupBy)
	if err := wsgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WebhookSubscriptionQuery, *WebhookSubscriptionGroupBy](ctx, wsgb.build, wsgb, wsgb.build.inters, v)
}

func (wsgb *WebhookSubscriptionGroupBy) sqlScan(ctx context.Context, root *WebhookSubscriptionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(wsgb.fns))
	for _, fn := range wsgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*wsgb.flds)+len(wsgb.fns))
		for _, f := range *wsgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*wsgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := wsgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// WebhookSubscriptionSelect is the builder for selecting fields of WebhookSubscription entities.
type WebhookSubscriptionSelect struct {
	*WebhookSubscriptionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (wss *WebhookSubscriptionSelect) Aggregate(fns ...AggregateFunc) *WebhookSubscriptionSelect {
	wss.fns = append(wss.fns, fns...)
	return wss
}

// Scan applies the selector query and scans the result into the given value.
func (wss *WebhookSubscriptionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, wss.ctx, ent.OpQuerySelect)
	if err := wss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WebhookSubscriptionQuery, *WebhookSubscriptionSelect](ctx, wss.WebhookSubscriptionQuery, wss, wss.inters, v)
}

func (wss *WebhookSubscriptionSelect) sqlScan(ctx context.Context, root *WebhookSubscriptionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(wss.fns))
	for _, fn := range wss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*wss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := wss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
