// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"reserve-interbank-settlement/services/payments-svc/ent/webhookdelivery"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WebhookDeliveryCreate is the builder for creating a WebhookDelivery entity.
type WebhookDeliveryCreate struct {
	config
	mutation *WebhookDeliveryMutation
	hooks    []Hook
}

// SetSubscriptionID sets the "subscription_id" field.
func (wdc *WebhookDeliveryCreate) SetSubscriptionID(s string) *WebhookDeliveryCreate {
	wdc.mutation.SetSubscriptionID(s)
	return wdc
}

// SetOrganizationID sets the "organization_id" field.
func (wdc *WebhookDeliveryCreate) SetOrganizationID(s string) *WebhookDeliveryCreate {
	wdc.mutation.SetOrganizationID(s)
	return wdc
}

// SetEventType sets the "event_type" field.
func (wdc *WebhookDeliveryCreate) SetEventType(s string) *WebhookDeliveryCreate {
	wdc.mutation.SetEventType(s)
	return wdc
}

// SetPayload sets the "payload" field.
func (wdc *WebhookDeliveryCreate) SetPayload(b []byte) *WebhookDeliveryCreate {
	wdc.mutation.SetPayload(b)
	return wdc
}

// SetStatus sets the "status" field.
func (wdc *WebhookDeliveryCreate) SetStatus(s string) *WebhookDeliveryCreate {
	wdc.mutation.SetStatus(s)
	return wdc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (wdc *WebhookDeliveryCreate) SetNillableStatus(s *string) *WebhookDeliveryCreate {
	if s != nil {
		wdc.SetStatus(*s)
	}
	return wdc
}

// SetAttempts sets the "attempts" field.
func (wdc *WebhookDeliveryCreate) SetAttempts(i int) *WebhookDeliveryCreate {
	wdc.mutation.SetAttempts(i)
	return wdc
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (wdc *WebhookDeliveryCreate) SetNillableAttempts(i *int) *WebhookDeliveryCreate {
	if i != nil {
		wdc.SetAttempts(*i)
	}
	return wdc
}

// SetLastCode sets the "last_code" field.
func (wdc *WebhookDeliveryCreate) SetLastCode(i int) *WebhookDeliveryCreate {
	wdc.mutation.SetLastCode(i)
	return wdc
}

// SetNillableLastCode sets the "last_code" field if the given value is not nil.
func (wdc *WebhookDeliveryCreate) SetNillableLastCode(i *int) *WebhookDeliveryCreate {
	if i != nil {
		wdc.SetLastCode(*i)
	}
	return wdc
}

// SetLastError sets the "last_error" field.
func (wdc *WebhookDeliveryCreate) SetLastError(s string) *WebhookDeliveryCreate {
	wdc.mutation.SetLastError(s)
	return wdc
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (wdc *WebhookDeliveryCreate) SetNillableLastError(s *string) *WebhookDeliveryCreate {
	if s != nil {
		wdc.SetLastError(*s)
	}
	return wdc
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (wdc *WebhookDeliveryCreate) SetNextAttemptAt(t time.Time) *WebhookDeliveryCreate {
	wdc.mutation.SetNextAttemptAt(t)
	return wdc
}

// SetCreatedAt sets the "created_at" field.
func (wdc *WebhookDeliveryCreate) SetCreatedAt(t time.Time) *WebhookDeliveryCreate {
	wdc.mutation.SetCreatedAt(t)
	return wdc
}

// SetID sets the "id" field.
func (wdc *WebhookDeliveryCreate) SetID(s string) *WebhookDeliveryCreate {
	wdc.mutation.SetID(s)
	return wdc
}

// Mutation returns the WebhookDeliveryMutation object of the builder.
func (wdc *WebhookDeliveryCreate) Mutation() *WebhookDeliveryMutation {
	return wdc.mutation
}

// Save creates the WebhookDelivery in the database.
func (wdc *WebhookDeliveryCreate) Save(ctx context.Context) (*WebhookDelivery, error) {
	wdc.defaults()
	return withHooks(ctx, wdc.sqlSave, wdc.mutation, wdc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (wdc *WebhookDeliveryCreate) SaveX(ctx context.Context) *WebhookDelivery {
	v, err := wdc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (wdc *WebhookDeliveryCreate) Exec(ctx context.Context) error {
	_, err := wdc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wdc *WebhookDeliveryCreate) ExecX(ctx context.Context) {
	if err := wdc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (wdc *WebhookDeliveryCreate) defaults() {
	if _, ok := wdc.mutation.Status(); !ok {
		v := webhookdelivery.DefaultStatus
		wdc.mutation.SetStatus(v)
	}
	if _, ok := wdc.mutation.Attempts(); !ok {
		v := webhookdelivery.DefaultAttempts
		wdc.mutation.SetAttempts(v)
	}
	if _, ok := wdc.mutation.LastCode(); !ok {
		v := webhookdelivery.DefaultLastCode
		wdc.mutation.SetLastCode(v)
	}
	if _, ok := wdc.mutation.LastError(); !ok {
		v := webhookdelivery.DefaultLastError
		wdc.mutation.SetLastError(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wdc *WebhookDeliveryCreate) check() error {
	if _, ok := wdc.mutation.SubscriptionID(); !ok {
		return &ValidationError{Name: "subscription_id", err: errors.New(`ent: missing required field "WebhookDelivery.subscription_id"`)}
	}
	if _, ok := wdc.mutation.OrganizationID(); !ok {
		return &ValidationError{Name: "organization_id", err: errors.New(`ent: missing required field "WebhookDelivery.organization_id"`)}
	}
	if _, ok := wdc.mutation.EventType(); !ok {
		return &ValidationError{Name: "event_type", err: errors.New(`ent: missing required field "WebhookDelivery.event_type"`)}
	}
	if _, ok := wdc.mutation.Payload(); !ok {
		return &ValidationError{Name: "payload", err: errors.New(`ent: missing required field "WebhookDelivery.payload"`)}
	}
	if _, ok := wdc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "WebhookDelivery.status"`)}
	}
	if _, ok := wdc.mutation.Attempts(); !ok {
		return &ValidationError{Name: "attempts", err: errors.New(`ent: missing required field "WebhookDelivery.attempts"`)}
	}
	if _, ok := wdc.mutation.LastCode(); !ok {
		return &ValidationError{Name: "last_code", err: errors.New(`ent: missing required field "WebhookDelivery.last_code"`)}
	}
	if _, ok := wdc.mutation.LastError(); !ok {
		return &ValidationError{Name: "last_error", err: errors.New(`ent: missing required field "WebhookDelivery.last_error"`)}
	}
	if _, ok := wdc.mutation.NextAttemptAt(); !ok {
		return &ValidationError{Name: "next_attempt_at", err: errors.New(`ent: missing required field "WebhookDelivery.next_attempt_at"`)}
	}
	if _, ok := wdc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "WebhookDelivery.created_at"`)}
	}
	return nil
}

func (wdc *WebhookDeliveryCreate) sqlSave(ctx context.Context) (*WebhookDelivery, error) {
	if err := wdc.check(); err != nil {
		return nil, err
	}
	_node, _spec := wdc.createSpec()
	if err := sqlgraph.CreateNode(ctx, wdc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected WebhookDelivery.ID type: %T", _spec.ID.Value)
		}
	}
	wdc.mutation.id = &_node.ID
	wdc.mutation.done = true
	return _node, nil
}

func (wdc *WebhookDeliveryCreate) createSpec() (*WebhookDelivery, *sqlgraph.CreateSpec) {
	var (
		_node = &WebhookDelivery{config: wdc.config}
		_spec = sqlgraph.NewCreateSpec(webhookdelivery.Table, sqlgraph.NewFieldSpec(webhookdelivery.FieldID, field.TypeString))
	)
	if id, ok := wdc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := wdc.mutation.SubscriptionID(); ok {
		_spec.SetField(webhookdelivery.FieldSubscriptionID, field.TypeString, value)
		_node.SubscriptionID = value
	}
	if value, ok := wdc.mutation.OrganizationID(); ok {
		_spec.SetField(webhookdelivery.FieldOrganizationID, field.TypeString, value)
		_node.OrganizationID = value
	}
	if value, ok := wdc.mutation.EventType(); ok {
		_spec.SetField(webhookdelivery.FieldEventType, field.TypeString, value)
		_node.EventType = value
	}
	if value, ok := wdc.mutation.Payload(); ok {
		_spec.SetField(webhookdelivery.FieldPayload, field.TypeBytes, value)
		_node.Payload = value
	}
	if value, ok := wdc.mutation.Status(); ok {
		_spec.SetField(webhookdelivery.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := wdc.mutation.Attempts(); ok {
		_spec.SetField(webhookdelivery.FieldAttempts, field.TypeInt, value)
		_node.Attempts = value
	}
	if value, ok := wdc.mutation.LastCode(); ok {
		_spec.SetField(webhookdelivery.FieldLastCode, field.TypeInt, value)
		_node.LastCode = value
	}
	if value, ok := wdc.mutation.LastError(); ok {
		_spec.SetField(webhookdelivery.FieldLastError, field.TypeString, value)
		_node.LastError = value
	}
	if value, ok := wdc.mutation.NextAttemptAt(); ok {
		_spec.SetField(webhookdelivery.FieldNextAttemptAt, field.TypeTime, value)
		_node.NextAttemptAt = value
	}
	if value, ok := wdc.mutation.CreatedAt(); ok {
		_spec.SetField(webhookdelivery.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// WebhookDeliveryCreateBulk is the builder for creating many WebhookDelivery entities in bulk.
type WebhookDeliveryCreateBulk struct {
	config
	err      error
	builders []*WebhookDeliveryCreate
}

// Save creates the WebhookDelivery entities in the database.
func (wdcb *WebhookDeliveryCreateBulk) Save(ctx context.Context) ([]*WebhookDelivery, error) {
	if wdcb.err != nil {
		return nil, wdcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(wdcb.builders))
	nodes := make([]*WebhookDelivery, len(wdcb.builders))
	mutators := make([]Mutator, len(wdcb.builders))
	for i := range wdcb.builders {
		func(i int, root context.Context) {
			builder := wdcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WebhookDeliveryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, wdcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, wdcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, wdcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (wdcb *WebhookDeliveryCreateBulk) SaveX(ctx context.Context) []*WebhookDelivery {
	v, err := wdcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (wdcb *WebhookDeliveryCreateBulk) Exec(ctx context.Context) error {
	_, err := wdcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wdcb *WebhookDeliveryCreateBulk) ExecX(ctx context.Context) {
	if err := wdcb.Exec(ctx); err != nil {
		panic(err)
	}
}
