// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AlertsColumns holds the columns for the "alerts" table.
	AlertsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "bank_id", Type: field.TypeString},
		{Name: "kind", Type: field.TypeString},
		{Name: "message", Type: field.TypeString, Size: 2147483647},
		{Name: "open", Type: field.TypeBool, Default: true},
		{Name: "at", Type: field.TypeTime},
		{Name: "closed_at", Type: field.TypeTime, Nullable: true},
	}
	// AlertsTable holds the schema information for the "alerts" table.
	AlertsTable = &schema.Table{
		Name:       "alerts",
		Columns:    AlertsColumns,
		PrimaryKey: []*schema.Column{AlertsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "alert_bank_id_kind_open",
				Unique:  false,
				Columns: []*schema.Column{AlertsColumns[1], AlertsColumns[2], AlertsColumns[4]},
			},
		},
	}
	// ApprovalsColumns holds the columns for the "approvals" table.
	ApprovalsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "approver_id", Type: field.TypeString},
		{Name: "approver_name", Type: field.TypeString},
		{Name: "at", Type: field.TypeTime},
		{Name: "order_id", Type: field.TypeString},
	}
	// ApprovalsTable holds the schema information for the "approvals" table.
	ApprovalsTable = &schema.Table{
		Name:       "approvals",
		Columns:    ApprovalsColumns,
		PrimaryKey: []*schema.Column{ApprovalsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "approvals_payment_orders_approvals",
				Columns:    []*schema.Column{ApprovalsColumns[4]},
				RefColumns: []*schema.Column{PaymentOrdersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "approval_order_id_approver_id",
				Unique:  true,
				Columns: []*schema.Column{ApprovalsColumns[4], ApprovalsColumns[1]},
			},
		},
	}
	// DefundsColumns holds the columns for the "defunds" table.
	DefundsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "bank_id", Type: field.TypeString},
		{Name: "amount", Type: field.TypeInt64},
		{Name: "requested_by_id", Type: field.TypeString},
		{Name: "requested_by", Type: field.TypeString},
		{Name: "approved_by", Type: field.TypeString, Default: ""},
		{Name: "status", Type: field.TypeString},
		{Name: "ledger_ref", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// DefundsTable holds the schema information for the "defunds" table.
	DefundsTable = &schema.Table{
		Name:       "defunds",
		Columns:    DefundsColumns,
		PrimaryKey: []*schema.Column{DefundsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "defund_bank_id",
				Unique:  false,
				Columns: []*schema.Column{DefundsColumns[1]},
			},
			{
				Name:    "defund_status",
				Unique:  false,
				Columns: []*schema.Column{DefundsColumns[6]},
			},
		},
	}
	// InterestDistributionsColumns holds the columns for the "interest_distributions" table.
	InterestDistributionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "at", Type: field.TypeTime},
		{Name: "run_by", Type: field.TypeString},
		{Name: "amount", Type: field.TypeInt64},
		{Name: "paid", Type: field.TypeInt64},
		{Name: "retained", Type: field.TypeInt64},
		{Name: "shares", Type: field.TypeJSON},
	}
	// InterestDistributionsTable holds the schema information for the "interest_distributions" table.
	InterestDistributionsTable = &schema.Table{
		Name:       "interest_distributions",
		Columns:    InterestDistributionsColumns,
		PrimaryKey: []*schema.Column{InterestDistributionsColumns[0]},
	}
	// NettingCyclesColumns holds the columns for the "netting_cycles" table.
	NettingCyclesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "cycle_ref", Type: field.TypeString, Default: ""},
		{Name: "at", Type: field.TypeTime},
		{Name: "trigger", Type: field.TypeString},
		{Name: "discharged", Type: field.TypeInt},
		{Name: "deferred", Type: field.TypeInt},
		{Name: "gross", Type: field.TypeInt64},
		{Name: "net", Type: field.TypeInt64},
	}
	// NettingCyclesTable holds the schema information for the "netting_cycles" table.
	NettingCyclesTable = &schema.Table{
		Name:       "netting_cycles",
		Columns:    NettingCyclesColumns,
		PrimaryKey: []*schema.Column{NettingCyclesColumns[0]},
	}
	// OrderEventsColumns holds the columns for the "order_events" table.
	OrderEventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "seq", Type: field.TypeInt},
		{Name: "at", Type: field.TypeTime},
		{Name: "actor", Type: field.TypeString},
		{Name: "status", Type: field.TypeString},
		{Name: "iso_status", Type: field.TypeString},
		{Name: "note", Type: field.TypeString, Size: 2147483647},
		{Name: "detail", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "order_id", Type: field.TypeString},
	}
	// OrderEventsTable holds the schema information for the "order_events" table.
	OrderEventsTable = &schema.Table{
		Name:       "order_events",
		Columns:    OrderEventsColumns,
		PrimaryKey: []*schema.Column{OrderEventsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "order_events_payment_orders_events",
				Columns:    []*schema.Column{OrderEventsColumns[8]},
				RefColumns: []*schema.Column{PaymentOrdersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "orderevent_order_id_seq",
				Unique:  true,
				Columns: []*schema.Column{OrderEventsColumns[8], OrderEventsColumns[1]},
			},
		},
	}
	// PaymentFilesColumns holds the columns for the "payment_files" table.
	PaymentFilesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "organization_id", Type: field.TypeString},
		{Name: "message_id", Type: field.TypeString},
		{Name: "request_hash", Type: field.TypeString},
		{Name: "idempotency_key", Type: field.TypeString},
		{Name: "transactions", Type: field.TypeInt},
		{Name: "control_sum", Type: field.TypeInt64},
		{Name: "created_by", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "rejections", Type: field.TypeJSON, Nullable: true},
	}
	// PaymentFilesTable holds the schema information for the "payment_files" table.
	PaymentFilesTable = &schema.Table{
		Name:       "payment_files",
		Columns:    PaymentFilesColumns,
		PrimaryKey: []*schema.Column{PaymentFilesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "paymentfile_organization_id_message_id",
				Unique:  true,
				Columns: []*schema.Column{PaymentFilesColumns[1], PaymentFilesColumns[2]},
			},
			{
				Name:    "paymentfile_organization_id_idempotency_key",
				Unique:  true,
				Columns: []*schema.Column{PaymentFilesColumns[1], PaymentFilesColumns[4]},
			},
		},
	}
	// PaymentOrdersColumns holds the columns for the "payment_orders" table.
	PaymentOrdersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "organization_id", Type: field.TypeString},
		{Name: "bank_id", Type: field.TypeString},
		{Name: "file_id", Type: field.TypeString, Nullable: true},
		{Name: "idempotency_key", Type: field.TypeString, Nullable: true},
		{Name: "request_hash", Type: field.TypeString},
		{Name: "end_to_end_id", Type: field.TypeString},
		{Name: "uetr", Type: field.TypeString},
		{Name: "debtor_account", Type: field.TypeString},
		{Name: "creditor_name", Type: field.TypeString},
		{Name: "creditor_routing", Type: field.TypeString},
		{Name: "creditor_account", Type: field.TypeString},
		{Name: "amount", Type: field.TypeInt64},
		{Name: "priority", Type: field.TypeString},
		{Name: "remittance", Type: field.TypeString, Default: ""},
		{Name: "status", Type: field.TypeString},
		{Name: "iso_status", Type: field.TypeString},
		{Name: "reason_code", Type: field.TypeString, Default: ""},
		{Name: "route", Type: field.TypeString, Default: ""},
		{Name: "route_note", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "payee_account_status", Type: field.TypeString},
		{Name: "payee_name_match", Type: field.TypeString},
		{Name: "payee_registered_name", Type: field.TypeString, Default: ""},
		{Name: "approvals_required", Type: field.TypeInt},
		{Name: "created_by", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "settled_at", Type: field.TypeTime, Nullable: true},
		{Name: "ofac_report_due", Type: field.TypeTime, Nullable: true},
		{Name: "sanctions_match", Type: field.TypeString, Default: ""},
		{Name: "payment_ref", Type: field.TypeString, Default: ""},
		{Name: "obligation_ref", Type: field.TypeString, Default: ""},
		{Name: "tokenized", Type: field.TypeBool, Default: false},
		{Name: "released", Type: field.TypeBool, Default: false},
		{Name: "version", Type: field.TypeInt, Default: 0},
	}
	// PaymentOrdersTable holds the schema information for the "payment_orders" table.
	PaymentOrdersTable = &schema.Table{
		Name:       "payment_orders",
		Columns:    PaymentOrdersColumns,
		PrimaryKey: []*schema.Column{PaymentOrdersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "paymentorder_organization_id_idempotency_key",
				Unique:  true,
				Columns: []*schema.Column{PaymentOrdersColumns[1], PaymentOrdersColumns[4]},
			},
			{
				Name:    "paymentorder_organization_id_end_to_end_id",
				Unique:  true,
				Columns: []*schema.Column{PaymentOrdersColumns[1], PaymentOrdersColumns[6]},
			},
			{
				Name:    "paymentorder_organization_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{PaymentOrdersColumns[1], PaymentOrdersColumns[25]},
			},
			{
				Name:    "paymentorder_bank_id_status",
				Unique:  false,
				Columns: []*schema.Column{PaymentOrdersColumns[2], PaymentOrdersColumns[15]},
			},
			{
				Name:    "paymentorder_status",
				Unique:  false,
				Columns: []*schema.Column{PaymentOrdersColumns[15]},
			},
			{
				Name:    "paymentorder_file_id",
				Unique:  false,
				Columns: []*schema.Column{PaymentOrdersColumns[3]},
			},
		},
	}
	// ReconciliationsColumns holds the columns for the "reconciliations" table.
	ReconciliationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "at", Type: field.TypeTime},
		{Name: "fed_balance", Type: field.TypeInt64},
		{Name: "reserve_pool", Type: field.TypeInt64},
		{Name: "reconciliation_break", Type: field.TypeBool},
		{Name: "invariants", Type: field.TypeBool},
	}
	// ReconciliationsTable holds the schema information for the "reconciliations" table.
	ReconciliationsTable = &schema.Table{
		Name:       "reconciliations",
		Columns:    ReconciliationsColumns,
		PrimaryKey: []*schema.Column{ReconciliationsColumns[0]},
	}
	// WebhookDeliveriesColumns holds the columns for the "webhook_deliveries" table.
	WebhookDeliveriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "subscription_id", Type: field.TypeString},
		{Name: "organization_id", Type: field.TypeString},
		{Name: "event_type", Type: field.TypeString},
		{Name: "payload", Type: field.TypeBytes},
		{Name: "status", Type: field.TypeString, Default: "PENDING"},
		{Name: "attempts", Type: field.TypeInt, Default: 0},
		{Name: "last_code", Type: field.TypeInt, Default: 0},
		{Name: "last_error", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "next_attempt_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
	}
	// WebhookDeliveriesTable holds the schema information for the "webhook_deliveries" table.
	WebhookDeliveriesTable = &schema.Table{
		Name:       "webhook_deliveries",
		Columns:    WebhookDeliveriesColumns,
		PrimaryKey: []*schema.Column{WebhookDeliveriesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "webhookdelivery_status_id",
				Unique:  false,
				Columns: []*schema.Column{WebhookDeliveriesColumns[5], WebhookDeliveriesColumns[0]},
			},
			{
				Name:    "webhookdelivery_subscription_id_id",
				Unique:  false,
				Columns: []*schema.Column{WebhookDeliveriesColumns[1], WebhookDeliveriesColumns[0]},
			},
		},
	}
	// WebhookSubscriptionsColumns holds the columns for the "webhook_subscriptions" table.
	WebhookSubscriptionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "organization_id", Type: field.TypeString},
		{Name: "url", Type: field.TypeString},
		{Name: "secret_sealed", Type: field.TypeBytes},
		{Name: "created_by", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
	}
	// WebhookSubscriptionsTable holds the schema information for the "webhook_subscriptions" table.
	WebhookSubscriptionsTable = &schema.Table{
		Name:       "webhook_subscriptions",
		Columns:    WebhookSubscriptionsColumns,
		PrimaryKey: []*schema.Column{WebhookSubscriptionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "webhooksubscription_organization_id",
				Unique:  false,
				Columns: []*schema.Column{WebhookSubscriptionsColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AlertsTable,
		ApprovalsTable,
		DefundsTable,
		InterestDistributionsTable,
		NettingCyclesTable,
		OrderEventsTable,
		PaymentFilesTable,
		PaymentOrdersTable,
		ReconciliationsTable,
		WebhookDeliveriesTable,
		WebhookSubscriptionsTable,
	}
)

func init() {
	ApprovalsTable.ForeignKeys[0].RefTable = PaymentOrdersTable
	OrderEventsTable.ForeignKeys[0].RefTable = PaymentOrdersTable
}
