// Code generated by ent, DO NOT EDIT.

package approval

import (
	"reserve-interbank-settlement/services/payments-svc/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Approval {
	return predicate.Approval(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Approval {
	return predicate.Approval(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Approval {
	return predicate.Approval(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Approval {
	return predicate.Approval(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Approval {
	return predicate.Approval(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Approval {
	return predicate.Approval(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Approval {
	return predicate.Approval(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Approval {
	return predicate.Approval(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Approval {
	return predicate.Approval(sql.FieldLTE(FieldID, id))
}

// OrderID applies equality check predicate on the "order_id" field. It's identical to OrderIDEQ.
func OrderID(v string) predicate.Approval {
	return predicate.Approval(sql.FieldEQ(FieldOrderID, v))
}

// ApproverID applies equality check predicate on the "approver_id" field. It's identical to ApproverIDEQ.
func ApproverID(v string) predicate.Approval {
	return predicate.Approval(sql.FieldEQ(FieldApproverID, v))
}

// ApproverName applies equality check predicate on the "approver_name" field. It's identical to ApproverNameEQ.
func ApproverName(v string) predicate.Approval {
	return predicate.Approval(sql.FieldEQ(FieldApproverName, v))
}

// At applies equality check predicate on the "at" field. It's identical to AtEQ.
func At(v time.Time) predicate.Approval {
	return predicate.Approval(sql.FieldEQ(FieldAt, v))
}

// OrderIDEQ applies the EQ predicate on the "order_id" field.
func OrderIDEQ(v string) predicate.Approval {
	return predicate.Approval(sql.FieldEQ(FieldOrderID, v))
}

// OrderIDNEQ applies the NEQ predicate on the "order_id" field.
func OrderIDNEQ(v string) predicate.Approval {
	return predicate.Approval(sql.FieldNEQ(FieldOrderID, v))
}

// OrderIDIn applies the In predicate on the "order_id" field.
func OrderIDIn(vs ...string) predicate.Approval {
	return predicate.Approval(sql.FieldIn(FieldOrderID, vs...))
}

// OrderIDNotIn applies the NotIn predicate on the "order_id" field.
func OrderIDNotIn(vs ...string) predicate.Approval {
	return predicate.Approval(sql.FieldNotIn(FieldOrderID, vs...))
}

// OrderIDGT applies the GT predicate on the "order_id" field.
func OrderIDGT(v string) predicate.Approval {
	return predicate.Approval(sql.FieldGT(FieldOrderID, v))
}

// OrderIDGTE applies the GTE predicate on the "order_id" field.
func OrderIDGTE(v string) predicate.Approval {
	return predicate.Approval(sql.FieldGTE(FieldOrderID, v))
}

// OrderIDLT applies the LT predicate on the "order_id" field.
func OrderIDLT(v string) predicate.Approval {
	return predicate.Approval(sql.FieldLT(FieldOrderID, v))
}

// OrderIDLTE applies the LTE predicate on the "order_id" field.
func OrderIDLTE(v string) predicate.Approval {
	return predicate.Approval(sql.FieldLTE(FieldOrderID, v))
}

// OrderIDContains applies the Contains predicate on the "order_id" field.
func OrderIDContains(v string) predicate.Approval {
	return predicate.Approval(sql.FieldContains(FieldOrderID, v))
}

// OrderIDHasPrefix applies the HasPrefix predicate on the "order_id" field.
func OrderIDHasPrefix(v string) predicate.Approval {
	return predicate.Approval(sql.FieldHasPrefix(FieldOrderID, v))
}

// OrderIDHasSuffix applies the HasSuffix predicate on the "order_id" field.
func OrderIDHasSuffix(v string) predicate.Approval {
	return predicate.Approval(sql.FieldHasSuffix(FieldOrderID, v))
}

// OrderIDEqualFold applies the EqualFold predicate on the "order_id" field.
func OrderIDEqualFold(v string) predicate.Approval {
	return predicate.Approval(sql.FieldEqualFold(FieldOrderID, v))
}

// OrderIDContainsFold applies the ContainsFold predicate on the "order_id" field.
func OrderIDContainsFold(v string) predicate.Approval {
	return predicate.Approval(sql.FieldContainsFold(FieldOrderID, v))
}

// ApproverIDEQ applies the EQ predicate on the "approver_id" field.
func ApproverIDEQ(v string) predicate.Approval {
	return predicate.Approval(sql.FieldEQ(FieldApproverID, v))
}

// ApproverIDNEQ applies the NEQ predicate on the "approver_id" field.
func ApproverIDNEQ(v string) predicate.Approval {
	return predicate.Approval(sql.FieldNEQ(FieldApproverID, v))
}

// ApproverIDIn applies the In predicate on the "approver_id" field.
func ApproverIDIn(vs ...string) predicate.Approval {
	return predicate.Approval(sql.FieldIn(FieldApproverID, vs...))
}

// ApproverIDNotIn applies the NotIn predicate on the "approver_id" field.
func ApproverIDNotIn(vs ...string) predicate.Approval {
	return predicate.Approval(sql.FieldNotIn(FieldApproverID, vs...))
}

// ApproverIDGT applies the GT predicate on the "approver_id" field.
func ApproverIDGT(v string) predicate.Approval {
	return predicate.Approval(sql.FieldGT(FieldApproverID, v))
}

// ApproverIDGTE applies the GTE predicate on the "approver_id" field.
func ApproverIDGTE(v string) predicate.Approval {
	return predicate.Approval(sql.FieldGTE(FieldApproverID, v))
}

// ApproverIDLT applies the LT predicate on the "approver_id" field.
func ApproverIDLT(v string) predicate.Approval {
	return predicate.Approval(sql.FieldLT(FieldApproverID, v))
}

// ApproverIDLTE applies the LTE predicate on the "approver_id" field.
func ApproverIDLTE(v string) predicate.Approval {
	return predicate.Approval(sql.FieldLTE(FieldApproverID, v))
}

// ApproverIDContains applies the Contains predicate on the "approver_id" field.
func ApproverIDContains(v string) predicate.Approval {
	return predicate.Approval(sql.FieldContains(FieldApproverID, v))
}

// ApproverIDHasPrefix applies the HasPrefix predicate on the "approver_id" field.
func ApproverIDHasPrefix(v string) predicate.Approval {
	return predicate.Approval(sql.FieldHasPrefix(FieldApproverID, v))
}

// ApproverIDHasSuffix applies the HasSuffix predicate on the "approver_id" field.
func ApproverIDHasSuffix(v string) predicate.Approval {
	return predicate.Approval(sql.FieldHasSuffix(FieldApproverID, v))
}

// ApproverIDEqualFold applies the EqualFold predicate on the "approver_id" field.
func ApproverIDEqualFold(v string) predicate.Approval {
	return predicate.Approval(sql.FieldEqualFold(FieldApproverID, v))
}

// ApproverIDContainsFold applies the ContainsFold predicate on the "approver_id" field.
func ApproverIDContainsFold(v string) predicate.Approval {
	return predicate.Approval(sql.FieldContainsFold(FieldApproverID, v))
}

// ApproverNameEQ applies the EQ predicate on the "approver_name" field.
func ApproverNameEQ(v string) predicate.Approval {
	return predicate.Approval(sql.FieldEQ(FieldApproverName, v))
}

// ApproverNameNEQ applies the NEQ predicate on the "approver_name" field.
func ApproverNameNEQ(v string) predicate.Approval {
	return predicate.Approval(sql.FieldNEQ(FieldApproverName, v))
}

// ApproverNameIn applies the In predicate on the "approver_name" field.
func ApproverNameIn(vs ...string) predicate.Approval {
	return predicate.Approval(sql.FieldIn(FieldApproverName, vs...))
}

// ApproverNameNotIn applies the NotIn predicate on the "approver_name" field.
func ApproverNameNotIn(vs ...string) predicate.Approval {
	return predicate.Approval(sql.FieldNotIn(FieldApproverName, vs...))
}

// ApproverNameGT applies the GT predicate on the "approver_name" field.
func ApproverNameGT(v string) predicate.Approval {
	return predicate.Approval(sql.FieldGT(FieldApproverName, v))
}

// ApproverNameGTE applies the GTE predicate on the "approver_name" field.
func ApproverNameGTE(v string) predicate.Approval {
	return predicate.Approval(sql.FieldGTE(FieldApproverName, v))
}

// ApproverNameLT applies the LT predicate on the "approver_name" field.
func ApproverNameLT(v string) predicate.Approval {
	return predicate.Approval(sql.FieldLT(FieldApproverName, v))
}

// ApproverNameLTE applies the LTE predicate on the "approver_name" field.
func ApproverNameLTE(v string) predicate.Approval {
	return predicate.Approval(sql.FieldLTE(FieldApproverName, v))
}

// ApproverNameContains applies the Contains predicate on the "approver_name" field.
func ApproverNameContains(v string) predicate.Approval {
	return predicate.Approval(sql.FieldContains(FieldApproverName, v))
}

// ApproverNameHasPrefix applies the HasPrefix predicate on the "approver_name" field.
func ApproverNameHasPrefix(v string) predicate.Approval {
	return predicate.Approval(sql.FieldHasPrefix(FieldApproverName, v))
}

// ApproverNameHasSuffix applies the HasSuffix predicate on the "approver_name" field.
func ApproverNameHasSuffix(v string) predicate.Approval {
	return predicate.Approval(sql.FieldHasSuffix(FieldApproverName, v))
}

// ApproverNameEqualFold applies the EqualFold predicate on the "approver_name" field.
func ApproverNameEqualFold(v string) predicate.Approval {
	return predicate.Approval(sql.FieldEqualFold(FieldApproverName, v))
}

// ApproverNameContainsFold applies the ContainsFold predicate on the "approver_name" field.
func ApproverNameContainsFold(v string) predicate.Approval {
	return predicate.Approval(sql.FieldContainsFold(FieldApproverName, v))
}

// AtEQ applies the EQ predicate on the "at" field.
func AtEQ(v time.Time) predicate.Approval {
	return predicate.Approval(sql.FieldEQ(FieldAt, v))
}

// AtNEQ applies the NEQ predicate on the "at" field.
func AtNEQ(v time.Time) predicate.Approval {
	return predicate.Approval(sql.FieldNEQ(FieldAt, v))
}

// AtIn applies the In predicate on the "at" field.
func AtIn(vs ...time.Time) predicate.Approval {
	return predicate.Approval(sql.FieldIn(FieldAt, vs...))
}

// AtNotIn applies the NotIn predicate on the "at" field.
func AtNotIn(vs ...time.Time) predicate.Approval {
	return predicate.Approval(sql.FieldNotIn(FieldAt, vs...))
}

// AtGT applies the GT predicate on the "at" field.
func AtGT(v time.Time) predicate.Approval {
	return predicate.Approval(sql.FieldGT(FieldAt, v))
}

// AtGTE applies the GTE predicate on the "at" field.
func AtGTE(v time.Time) predicate.Approval {
	return predicate.Approval(sql.FieldGTE(FieldAt, v))
}

// AtLT applies the LT predicate on the "at" field.
func AtLT(v time.Time) predicate.Approval {
	return predicate.Approval(sql.FieldLT(FieldAt, v))
}

// AtLTE applies the LTE predicate on the "at" field.
func AtLTE(v time.Time) predicate.Approval {
	return predicate.Approval(sql.FieldLTE(FieldAt, v))
}

// HasOrder applies the HasEdge predicate on the "order" edge.
func HasOrder() predicate.Approval {
	return predicate.Approval(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OrderTable, OrderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOrderWith applies the HasEdge predicate on the "order" edge with a given conditions (other predicates).
func HasOrderWith(preds ...predicate.PaymentOrder) predicate.Approval {
	return predicate.Approval(func(s *sql.Selector) {
		step := newOrderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Approval) predicate.Approval {
	return predicate.Approval(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Approval) predicate.Approval {
	return predicate.Approval(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Approval) predicate.Approval {
	return predicate.Approval(sql.NotPredicates(p))
}
