// Code generated by ent, DO NOT EDIT.

package reconciliation

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the reconciliation type in the database.
	Label = "reconciliation"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAt holds the string denoting the at field in the database.
	FieldAt = "at"
	// FieldFedBalance holds the string denoting the fed_balance field in the database.
	FieldFedBalance = "fed_balance"
	// FieldReservePool holds the string denoting the reserve_pool field in the database.
	FieldReservePool = "reserve_pool"
	// FieldReconciliationBreak holds the string denoting the reconciliation_break field in the database.
	FieldReconciliationBreak = "reconciliation_break"
	// FieldInvariants holds the string denoting the invariants field in the database.
	FieldInvariants = "invariants"
	// Table holds the table name of the reconciliation in the database.
	Table = "reconciliations"
)

// Columns holds all SQL columns for reconciliation fields.
var Columns = []string{
	FieldID,
	FieldAt,
	FieldFedBalance,
	FieldReservePool,
	FieldReconciliationBreak,
	FieldInvariants,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Reconciliation queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAt orders the results by the at field.
func ByAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAt, opts...).ToFunc()
}

// ByFedBalance orders the results by the fed_balance field.
func ByFedBalance(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFedBalance, opts...).ToFunc()
}

// ByReservePool orders the results by the reserve_pool field.
func ByReservePool(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReservePool, opts...).ToFunc()
}

// ByReconciliationBreak orders the results by the reconciliation_break field.
func ByReconciliationBreak(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReconciliationBreak, opts...).ToFunc()
}

// ByInvariants orders the results by the invariants field.
func ByInvariants(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInvariants, opts...).ToFunc()
}
