// Code generated by ent, DO NOT EDIT.

package orderevent

import (
	"reserve-interbank-settlement/services/payments-svc/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldLTE(FieldID, id))
}

// OrderID applies equality check predicate on the "order_id" field. It's identical to OrderIDEQ.
func OrderID(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldEQ(FieldOrderID, v))
}

// Seq applies equality check predicate on the "seq" field. It's identical to SeqEQ.
func Seq(v int) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldEQ(FieldSeq, v))
}

// At applies equality check predicate on the "at" field. It's identical to AtEQ.
func At(v time.Time) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldEQ(FieldAt, v))
}

// Actor applies equality check predicate on the "actor" field. It's identical to ActorEQ.
func Actor(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldEQ(FieldActor, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldEQ(FieldStatus, v))
}

// IsoStatus applies equality check predicate on the "iso_status" field. It's identical to IsoStatusEQ.
func IsoStatus(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldEQ(FieldIsoStatus, v))
}

// Note applies equality check predicate on the "note" field. It's identical to NoteEQ.
func Note(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldEQ(FieldNote, v))
}

// Detail applies equality check predicate on the "detail" field. It's identical to DetailEQ.
func Detail(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldEQ(FieldDetail, v))
}

// OrderIDEQ applies the EQ predicate on the "order_id" field.
func OrderIDEQ(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldEQ(FieldOrderID, v))
}

// OrderIDNEQ applies the NEQ predicate on the "order_id" field.
func OrderIDNEQ(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldNEQ(FieldOrderID, v))
}

// OrderIDIn applies the In predicate on the "order_id" field.
func OrderIDIn(vs ...string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldIn(FieldOrderID, vs...))
}

// OrderIDNotIn applies the NotIn predicate on the "order_id" field.
func OrderIDNotIn(vs ...string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldNotIn(FieldOrderID, vs...))
}

// OrderIDGT applies the GT predicate on the "order_id" field.
func OrderIDGT(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldGT(FieldOrderID, v))
}

// OrderIDGTE applies the GTE predicate on the "order_id" field.
func OrderIDGTE(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldGTE(FieldOrderID, v))
}

// OrderIDLT applies the LT predicate on the "order_id" field.
func OrderIDLT(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldLT(FieldOrderID, v))
}

// OrderIDLTE applies the LTE predicate on the "order_id" field.
func OrderIDLTE(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldLTE(FieldOrderID, v))
}

// OrderIDContains applies the Contains predicate on the "order_id" field.
func OrderIDContains(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldContains(FieldOrderID, v))
}

// OrderIDHasPrefix applies the HasPrefix predicate on the "order_id" field.
func OrderIDHasPrefix(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldHasPrefix(FieldOrderID, v))
}

// OrderIDHasSuffix applies the HasSuffix predicate on the "order_id" field.
func OrderIDHasSuffix(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldHasSuffix(FieldOrderID, v))
}

// OrderIDEqualFold applies the EqualFold predicate on the "order_id" field.
func OrderIDEqualFold(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldEqualFold(FieldOrderID, v))
}

// OrderIDContainsFold applies the ContainsFold predicate on the "order_id" field.
func OrderIDContainsFold(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldContainsFold(FieldOrderID, v))
}

// SeqEQ applies the EQ predicate on the "seq" field.
func SeqEQ(v int) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldEQ(FieldSeq, v))
}

// SeqNEQ applies the NEQ predicate on the "seq" field.
func SeqNEQ(v int) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldNEQ(FieldSeq, v))
}

// SeqIn applies the In predicate on the "seq" field.
func SeqIn(vs ...int) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldIn(FieldSeq, vs...))
}

// SeqNotIn applies the NotIn predicate on the "seq" field.
func SeqNotIn(vs ...int) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldNotIn(FieldSeq, vs...))
}

// SeqGT applies the GT predicate on the "seq" field.
func SeqGT(v int) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldGT(FieldSeq, v))
}

// SeqGTE applies the GTE predicate on the "seq" field.
func SeqGTE(v int) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldGTE(FieldSeq, v))
}

// SeqLT applies the LT predicate on the "seq" field.
func SeqLT(v int) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldLT(FieldSeq, v))
}

// SeqLTE applies the LTE predicate on the "seq" field.
func SeqLTE(v int) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldLTE(FieldSeq, v))
}

// AtEQ applies the EQ predicate on the "at" field.
func AtEQ(v time.Time) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldEQ(FieldAt, v))
}

// AtNEQ applies the NEQ predicate on the "at" field.
func AtNEQ(v time.Time) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldNEQ(FieldAt, v))
}

// AtIn applies the In predicate on the "at" field.
func AtIn(vs ...time.Time) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldIn(FieldAt, vs...))
}

// AtNotIn applies the NotIn predicate on the "at" field.
func AtNotIn(vs ...time.Time) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldNotIn(FieldAt, vs...))
}

// AtGT applies the GT predicate on the "at" field.
func AtGT(v time.Time) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldGT(FieldAt, v))
}

// AtGTE applies the GTE predicate on the "at" field.
func AtGTE(v time.Time) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldGTE(FieldAt, v))
}

// AtLT applies the LT predicate on the "at" field.
func AtLT(v time.Time) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldLT(FieldAt, v))
}

// AtLTE applies the LTE predicate on the "at" field.
func AtLTE(v time.Time) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldLTE(FieldAt, v))
}

// ActorEQ applies the EQ predicate on the "actor" field.
func ActorEQ(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldEQ(FieldActor, v))
}

// ActorNEQ applies the NEQ predicate on the "actor" field.
func ActorNEQ(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldNEQ(FieldActor, v))
}

// ActorIn applies the In predicate on the "actor" field.
func ActorIn(vs ...string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldIn(FieldActor, vs...))
}

// ActorNotIn applies the NotIn predicate on the "actor" field.
func ActorNotIn(vs ...string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldNotIn(FieldActor, vs...))
}

// ActorGT applies the GT predicate on the "actor" field.
func ActorGT(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldGT(FieldActor, v))
}

// ActorGTE applies the GTE predicate on the "actor" field.
func ActorGTE(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldGTE(FieldActor, v))
}

// ActorLT applies the LT predicate on the "actor" field.
func ActorLT(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldLT(FieldActor, v))
}

// ActorLTE applies the LTE predicate on the "actor" field.
func ActorLTE(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldLTE(FieldActor, v))
}

// ActorContains applies the Contains predicate on the "actor" field.
func ActorContains(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldContains(FieldActor, v))
}

// ActorHasPrefix applies the HasPrefix predicate on the "actor" field.
func ActorHasPrefix(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldHasPrefix(FieldActor, v))
}

// ActorHasSuffix applies the HasSuffix predicate on the "actor" field.
func ActorHasSuffix(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldHasSuffix(FieldActor, v))
}

// ActorEqualFold applies the EqualFold predicate on the "actor" field.
func ActorEqualFold(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldEqualFold(FieldActor, v))
}

// ActorContainsFold applies the ContainsFold predicate on the "actor" field.
func ActorContainsFold(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldContainsFold(FieldActor, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldContainsFold(FieldStatus, v))
}

// IsoStatusEQ applies the EQ predicate on the "iso_status" field.
func IsoStatusEQ(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldEQ(FieldIsoStatus, v))
}

// IsoStatusNEQ applies the NEQ predicate on the "iso_status" field.
func IsoStatusNEQ(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldNEQ(FieldIsoStatus, v))
}

// IsoStatusIn applies the In predicate on the "iso_status" field.
func IsoStatusIn(vs ...string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldIn(FieldIsoStatus, vs...))
}

// IsoStatusNotIn applies the NotIn predicate on the "iso_status" field.
func IsoStatusNotIn(vs ...string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldNotIn(FieldIsoStatus, vs...))
}

// IsoStatusGT applies the GT predicate on the "iso_status" field.
func IsoStatusGT(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldGT(FieldIsoStatus, v))
}

// IsoStatusGTE applies the GTE predicate on the "iso_status" field.
func IsoStatusGTE(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldGTE(FieldIsoStatus, v))
}

// IsoStatusLT applies the LT predicate on the "iso_status" field.
func IsoStatusLT(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldLT(FieldIsoStatus, v))
}

// IsoStatusLTE applies the LTE predicate on the "iso_status" field.
func IsoStatusLTE(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldLTE(FieldIsoStatus, v))
}

// IsoStatusContains applies the Contains predicate on the "iso_status" field.
func IsoStatusContains(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldContains(FieldIsoStatus, v))
}

// IsoStatusHasPrefix applies the HasPrefix predicate on the "iso_status" field.
func IsoStatusHasPrefix(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldHasPrefix(FieldIsoStatus, v))
}

// IsoStatusHasSuffix applies the HasSuffix predicate on the "iso_status" field.
func IsoStatusHasSuffix(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldHasSuffix(FieldIsoStatus, v))
}

// IsoStatusEqualFold applies the EqualFold predicate on the "iso_status" field.
func IsoStatusEqualFold(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldEqualFold(FieldIsoStatus, v))
}

// IsoStatusContainsFold applies the ContainsFold predicate on the "iso_status" field.
func IsoStatusContainsFold(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldContainsFold(FieldIsoStatus, v))
}

// NoteEQ applies the EQ predicate on the "note" field.
func NoteEQ(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldEQ(FieldNote, v))
}

// NoteNEQ applies the NEQ predicate on the "note" field.
func NoteNEQ(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldNEQ(FieldNote, v))
}

// NoteIn applies the In predicate on the "note" field.
func NoteIn(vs ...string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldIn(FieldNote, vs...))
}

// NoteNotIn applies the NotIn predicate on the "note" field.
func NoteNotIn(vs ...string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldNotIn(FieldNote, vs...))
}

// NoteGT applies the GT predicate on the "note" field.
func NoteGT(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldGT(FieldNote, v))
}

// NoteGTE applies the GTE predicate on the "note" field.
func NoteGTE(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldGTE(FieldNote, v))
}

// NoteLT applies the LT predicate on the "note" field.
func NoteLT(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldLT(FieldNote, v))
}

// NoteLTE applies the LTE predicate on the "note" field.
func NoteLTE(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldLTE(FieldNote, v))
}

// NoteContains applies the Contains predicate on the "note" field.
func NoteContains(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldContains(FieldNote, v))
}

// NoteHasPrefix applies the HasPrefix predicate on the "note" field.
func NoteHasPrefix(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldHasPrefix(FieldNote, v))
}

// NoteHasSuffix applies the HasSuffix predicate on the "note" field.
func NoteHasSuffix(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldHasSuffix(FieldNote, v))
}

// NoteEqualFold applies the EqualFold predicate on the "note" field.
func NoteEqualFold(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldEqualFold(FieldNote, v))
}

// NoteContainsFold applies the ContainsFold predicate on the "note" field.
func NoteContainsFold(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldContainsFold(FieldNote, v))
}

// DetailEQ applies the EQ predicate on the "detail" field.
func DetailEQ(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldEQ(FieldDetail, v))
}

// DetailNEQ applies the NEQ predicate on the "detail" field.
func DetailNEQ(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldNEQ(FieldDetail, v))
}

// DetailIn applies the In predicate on the "detail" field.
func DetailIn(vs ...string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldIn(FieldDetail, vs...))
}

// DetailNotIn applies the NotIn predicate on the "detail" field.
func DetailNotIn(vs ...string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldNotIn(FieldDetail, vs...))
}

// DetailGT applies the GT predicate on the "detail" field.
func DetailGT(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldGT(FieldDetail, v))
}

// DetailGTE applies the GTE predicate on the "detail" field.
func DetailGTE(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldGTE(FieldDetail, v))
}

// DetailLT applies the LT predicate on the "detail" field.
func DetailLT(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldLT(FieldDetail, v))
}

// DetailLTE applies the LTE predicate on the "detail" field.
func DetailLTE(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldLTE(FieldDetail, v))
}

// DetailContains applies the Contains predicate on the "detail" field.
func DetailContains(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldContains(FieldDetail, v))
}

// DetailHasPrefix applies the HasPrefix predicate on the "detail" field.
func DetailHasPrefix(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldHasPrefix(FieldDetail, v))
}

// DetailHasSuffix applies the HasSuffix predicate on the "detail" field.
func DetailHasSuffix(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldHasSuffix(FieldDetail, v))
}

// DetailEqualFold applies the EqualFold predicate on the "detail" field.
func DetailEqualFold(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldEqualFold(FieldDetail, v))
}

// DetailContainsFold applies the ContainsFold predicate on the "detail" field.
func DetailContainsFold(v string) predicate.OrderEvent {
	return predicate.OrderEvent(sql.FieldContainsFold(FieldDetail, v))
}

// HasOrder applies the HasEdge predicate on the "order" edge.
func HasOrder() predicate.OrderEvent {
	return predicate.OrderEvent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OrderTable, OrderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOrderWith applies the HasEdge predicate on the "order" edge with a given conditions (other predicates).
func HasOrderWith(preds ...predicate.PaymentOrder) predicate.OrderEvent {
	return predicate.OrderEvent(func(s *sql.Selector) {
		step := newOrderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OrderEvent) predicate.OrderEvent {
	return predicate.OrderEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OrderEvent) predicate.OrderEvent {
	return predicate.OrderEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OrderEvent) predicate.OrderEvent {
	return predicate.OrderEvent(sql.NotPredicates(p))
}
