// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.0
// source: api/payments/v1/operations.proto

package paymentsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BankOperationsService_ListBankPayments_FullMethodName = "/api.payments.v1.BankOperationsService/ListBankPayments"
	BankOperationsService_GetBankPayment_FullMethodName   = "/api.payments.v1.BankOperationsService/GetBankPayment"
	BankOperationsService_ListHolds_FullMethodName        = "/api.payments.v1.BankOperationsService/ListHolds"
	BankOperationsService_ReleaseHold_FullMethodName      = "/api.payments.v1.BankOperationsService/ReleaseHold"
	BankOperationsService_BlockHold_FullMethodName        = "/api.payments.v1.BankOperationsService/BlockHold"
	BankOperationsService_RejectHold_FullMethodName       = "/api.payments.v1.BankOperationsService/RejectHold"
	BankOperationsService_GetLiquidity_FullMethodName     = "/api.payments.v1.BankOperationsService/GetLiquidity"
	BankOperationsService_FundSettlement_FullMethodName   = "/api.payments.v1.BankOperationsService/FundSettlement"
	BankOperationsService_DrawIntraday_FullMethodName     = "/api.payments.v1.BankOperationsService/DrawIntraday"
	BankOperationsService_RepayIntraday_FullMethodName    = "/api.payments.v1.BankOperationsService/RepayIntraday"
	BankOperationsService_RequestDefund_FullMethodName    = "/api.payments.v1.BankOperationsService/RequestDefund"
	BankOperationsService_ApproveDefund_FullMethodName    = "/api.payments.v1.BankOperationsService/ApproveDefund"
)

// BankOperationsServiceClient is the client API for BankOperationsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BankOperationsServiceClient interface {
	// ListBankPayments lists the bank's clients' payments, with staff detail.
	ListBankPayments(ctx context.Context, in *ListBankPaymentsRequest, opts ...grpc.CallOption) (*ListBankPaymentsResponse, error)
	// GetBankPayment returns one of the bank's clients' payments, with staff detail.
	GetBankPayment(ctx context.Context, in *GetBankPaymentRequest, opts ...grpc.CallOption) (*Payment, error)
	// ListHolds lists payments held for sanctions review, and blocked or
	// rejected cases with their OFAC report dates.
	ListHolds(ctx context.Context, in *ListHoldsRequest, opts ...grpc.CallOption) (*ListHoldsResponse, error)
	// ReleaseHold clears a false positive; the payment proceeds.
	ReleaseHold(ctx context.Context, in *HoldDecisionRequest, opts ...grpc.CallOption) (*Payment, error)
	// BlockHold: a sanctioned party has an interest in the funds. They move to
	// the bank's blocked account (BLCK) and a report is due to OFAC within 10
	// business days (31 CFR 501.603).
	BlockHold(ctx context.Context, in *HoldDecisionRequest, opts ...grpc.CallOption) (*Payment, error)
	// RejectHold: prohibited, but no sanctioned party has an interest. Nothing
	// moves (RR04); reported within 10 business days (31 CFR 501.604).
	RejectHold(ctx context.Context, in *HoldDecisionRequest, opts ...grpc.CallOption) (*Payment, error)
	// GetLiquidity returns the bank's settlement money, intraday draws,
	// alerts, payments waiting for liquidity and defunds.
	GetLiquidity(ctx context.Context, in *GetLiquidityRequest, opts ...grpc.CallOption) (*Liquidity, error)
	// FundSettlement sends reserves into the reserve account and the operator
	// issues settlement money against them: Fedwire BTRC while Fedwire is open,
	// FedNow LMT1 while it is closed.
	FundSettlement(ctx context.Context, in *FundSettlementRequest, opts ...grpc.CallOption) (*FundSettlementResponse, error)
	// DrawIntraday borrows settlement money from the intraday pool against
	// collateral at the pool's advance rate; payments waiting for liquidity
	// then proceed.
	DrawIntraday(ctx context.Context, in *DrawIntradayRequest, opts ...grpc.CallOption) (*DrawIntradayResponse, error)
	// RepayIntraday repays a draw with its interest; the collateral returns.
	RepayIntraday(ctx context.Context, in *RepayIntradayRequest, opts ...grpc.CallOption) (*IntradayDraw, error)
	// RequestDefund asks for settlement money back to the master account as
	// reserves (maker); the amount is earmarked at once.
	RequestDefund(ctx context.Context, in *RequestDefundRequest, opts ...grpc.CallOption) (*Defund, error)
	// ApproveDefund is the checker; never the requester, always the same bank.
	ApproveDefund(ctx context.Context, in *ApproveDefundRequest, opts ...grpc.CallOption) (*Defund, error)
}

type bankOperationsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBankOperationsServiceClient(cc grpc.ClientConnInterface) BankOperationsServiceClient {
	return &bankOperationsServiceClient{cc}
}

func (c *bankOperationsServiceClient) ListBankPayments(ctx context.Context, in *ListBankPaymentsRequest, opts ...grpc.CallOption) (*ListBankPaymentsResponse, error) {
	out := new(ListBankPaymentsResponse)
	err := c.cc.Invoke(ctx, BankOperationsService_ListBankPayments_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankOperationsServiceClient) GetBankPayment(ctx context.Context, in *GetBankPaymentRequest, opts ...grpc.CallOption) (*Payment, error) {
	out := new(Payment)
	err := c.cc.Invoke(ctx, BankOperationsService_GetBankPayment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankOperationsServiceClient) ListHolds(ctx context.Context, in *ListHoldsRequest, opts ...grpc.CallOption) (*ListHoldsResponse, error) {
	out := new(ListHoldsResponse)
	err := c.cc.Invoke(ctx, BankOperationsService_ListHolds_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankOperationsServiceClient) ReleaseHold(ctx context.Context, in *HoldDecisionRequest, opts ...grpc.CallOption) (*Payment, error) {
	out := new(Payment)
	err := c.cc.Invoke(ctx, BankOperationsService_ReleaseHold_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankOperationsServiceClient) BlockHold(ctx context.Context, in *HoldDecisionRequest, opts ...grpc.CallOption) (*Payment, error) {
	out := new(Payment)
	err := c.cc.Invoke(ctx, BankOperationsService_BlockHold_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankOperationsServiceClient) RejectHold(ctx context.Context, in *HoldDecisionRequest, opts ...grpc.CallOption) (*Payment, error) {
	out := new(Payment)
	err := c.cc.Invoke(ctx, BankOperationsService_RejectHold_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankOperationsServiceClient) GetLiquidity(ctx context.Context, in *GetLiquidityRequest, opts ...grpc.CallOption) (*Liquidity, error) {
	out := new(Liquidity)
	err := c.cc.Invoke(ctx, BankOperationsService_GetLiquidity_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankOperationsServiceClient) FundSettlement(ctx context.Context, in *FundSettlementRequest, opts ...grpc.CallOption) (*FundSettlementResponse, error) {
	out := new(FundSettlementResponse)
	err := c.cc.Invoke(ctx, BankOperationsService_FundSettlement_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankOperationsServiceClient) DrawIntraday(ctx context.Context, in *DrawIntradayRequest, opts ...grpc.CallOption) (*DrawIntradayResponse, error) {
	out := new(DrawIntradayResponse)
	err := c.cc.Invoke(ctx, BankOperationsService_DrawIntraday_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankOperationsServiceClient) RepayIntraday(ctx context.Context, in *RepayIntradayRequest, opts ...grpc.CallOption) (*IntradayDraw, error) {
	out := new(IntradayDraw)
	err := c.cc.Invoke(ctx, BankOperationsService_RepayIntraday_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankOperationsServiceClient) RequestDefund(ctx context.Context, in *RequestDefundRequest, opts ...grpc.CallOption) (*Defund, error) {
	out := new(Defund)
	err := c.cc.Invoke(ctx, BankOperationsService_RequestDefund_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankOperationsServiceClient) ApproveDefund(ctx context.Context, in *ApproveDefundRequest, opts ...grpc.CallOption) (*Defund, error) {
	out := new(Defund)
	err := c.cc.Invoke(ctx, BankOperationsService_ApproveDefund_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BankOperationsServiceServer is the server API for BankOperationsService service.
// All implementations must embed UnimplementedBankOperationsServiceServer
// for forward compatibility
type BankOperationsServiceServer interface {
	// ListBankPayments lists the bank's clients' payments, with staff detail.
	ListBankPayments(context.Context, *ListBankPaymentsRequest) (*ListBankPaymentsResponse, error)
	// GetBankPayment returns one of the bank's clients' payments, with staff detail.
	GetBankPayment(context.Context, *GetBankPaymentRequest) (*Payment, error)
	// ListHolds lists payments held for sanctions review, and blocked or
	// rejected cases with their OFAC report dates.
	ListHolds(context.Context, *ListHoldsRequest) (*ListHoldsResponse, error)
	// ReleaseHold clears a false positive; the payment proceeds.
	ReleaseHold(context.Context, *HoldDecisionRequest) (*Payment, error)
	// BlockHold: a sanctioned party has an interest in the funds. They move to
	// the bank's blocked account (BLCK) and a report is due to OFAC within 10
	// business days (31 CFR 501.603).
	BlockHold(context.Context, *HoldDecisionRequest) (*Payment, error)
	// RejectHold: prohibited, but no sanctioned party has an interest. Nothing
	// moves (RR04); reported within 10 business days (31 CFR 501.604).
	RejectHold(context.Context, *HoldDecisionRequest) (*Payment, error)
	// GetLiquidity returns the bank's settlement money, intraday draws,
	// alerts, payments waiting for liquidity and defunds.
	GetLiquidity(context.Context, *GetLiquidityRequest) (*Liquidity, error)
	// FundSettlement sends reserves into the reserve account and the operator
	// issues settlement money against them: Fedwire BTRC while Fedwire is open,
	// FedNow LMT1 while it is closed.
	FundSettlement(context.Context, *FundSettlementRequest) (*FundSettlementResponse, error)
	// DrawIntraday borrows settlement money from the intraday pool against
	// collateral at the pool's advance rate; payments waiting for liquidity
	// then proceed.
	DrawIntraday(context.Context, *DrawIntradayRequest) (*DrawIntradayResponse, error)
	// RepayIntraday repays a draw with its interest; the collateral returns.
	RepayIntraday(context.Context, *RepayIntradayRequest) (*IntradayDraw, error)
	// RequestDefund asks for settlement money back to the master account as
	// reserves (maker); the amount is earmarked at once.
	RequestDefund(context.Context, *RequestDefundRequest) (*Defund, error)
	// ApproveDefund is the checker; never the requester, always the same bank.
	ApproveDefund(context.Context, *ApproveDefundRequest) (*Defund, error)
	mustEmbedUnimplementedBankOperationsServiceServer()
}

// UnimplementedBankOperationsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBankOperationsServiceServer struct {
}

func (UnimplementedBankOperationsServiceServer) ListBankPayments(context.Context, *ListBankPaymentsRequest) (*ListBankPaymentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBankPayments not implemented")
}
func (UnimplementedBankOperationsServiceServer) GetBankPayment(context.Context, *GetBankPaymentRequest) (*Payment, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBankPayment not implemented")
}
func (UnimplementedBankOperationsServiceServer) ListHolds(context.Context, *ListHoldsRequest) (*ListHoldsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListHolds not implemented")
}
func (UnimplementedBankOperationsServiceServer) ReleaseHold(context.Context, *HoldDecisionRequest) (*Payment, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseHold not implemented")
}
func (UnimplementedBankOperationsServiceServer) BlockHold(context.Context, *HoldDecisionRequest) (*Payment, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BlockHold not implemented")
}
func (UnimplementedBankOperationsServiceServer) RejectHold(context.Context, *HoldDecisionRequest) (*Payment, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RejectHold not implemented")
}
func (UnimplementedBankOperationsServiceServer) GetLiquidity(context.Context, *GetLiquidityRequest) (*Liquidity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLiquidity not implemented")
}
func (UnimplementedBankOperationsServiceServer) FundSettlement(context.Context, *FundSettlementRequest) (*FundSettlementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FundSettlement not implemented")
}
func (UnimplementedBankOperationsServiceServer) DrawIntraday(context.Context, *DrawIntradayRequest) (*DrawIntradayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DrawIntraday not implemented")
}
func (UnimplementedBankOperationsServiceServer) RepayIntraday(context.Context, *RepayIntradayRequest) (*IntradayDraw, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RepayIntraday not implemented")
}
func (UnimplementedBankOperationsServiceServer) RequestDefund(context.Context, *RequestDefundRequest) (*Defund, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestDefund not implemented")
}
func (UnimplementedBankOperationsServiceServer) ApproveDefund(context.Context, *ApproveDefundRequest) (*Defund, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApproveDefund not implemented")
}
func (UnimplementedBankOperationsServiceServer) mustEmbedUnimplementedBankOperationsServiceServer() {}

// UnsafeBankOperationsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BankOperationsServiceServer will
// result in compilation errors.
type UnsafeBankOperationsServiceServer interface {
	mustEmbedUnimplementedBankOperationsServiceServer()
}

func RegisterBankOperationsServiceServer(s grpc.ServiceRegistrar, srv BankOperationsServiceServer) {
	s.RegisterService(&BankOperationsService_ServiceDesc, srv)
}

func _BankOperationsService_ListBankPayments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBankPaymentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankOperationsServiceServer).ListBankPayments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankOperationsService_ListBankPayments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankOperationsServiceServer).ListBankPayments(ctx, req.(*ListBankPaymentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankOperationsService_GetBankPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBankPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankOperationsServiceServer).GetBankPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankOperationsService_GetBankPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankOperationsServiceServer).GetBankPayment(ctx, req.(*GetBankPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankOperationsService_ListHolds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHoldsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankOperationsServiceServer).ListHolds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankOperationsService_ListHolds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankOperationsServiceServer).ListHolds(ctx, req.(*ListHoldsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankOperationsService_ReleaseHold_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HoldDecisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankOperationsServiceServer).ReleaseHold(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankOperationsService_ReleaseHold_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankOperationsServiceServer).ReleaseHold(ctx, req.(*HoldDecisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankOperationsService_BlockHold_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HoldDecisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankOperationsServiceServer).BlockHold(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankOperationsService_BlockHold_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankOperationsServiceServer).BlockHold(ctx, req.(*HoldDecisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankOperationsService_RejectHold_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HoldDecisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankOperationsServiceServer).RejectHold(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankOperationsService_RejectHold_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankOperationsServiceServer).RejectHold(ctx, req.(*HoldDecisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankOperationsService_GetLiquidity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLiquidityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankOperationsServiceServer).GetLiquidity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankOperationsService_GetLiquidity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankOperationsServiceServer).GetLiquidity(ctx, req.(*GetLiquidityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankOperationsService_FundSettlement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FundSettlementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankOperationsServiceServer).FundSettlement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankOperationsService_FundSettlement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankOperationsServiceServer).FundSettlement(ctx, req.(*FundSettlementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankOperationsService_DrawIntraday_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DrawIntradayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankOperationsServiceServer).DrawIntraday(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankOperationsService_DrawIntraday_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankOperationsServiceServer).DrawIntraday(ctx, req.(*DrawIntradayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankOperationsService_RepayIntraday_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepayIntradayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankOperationsServiceServer).RepayIntraday(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankOperationsService_RepayIntraday_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankOperationsServiceServer).RepayIntraday(ctx, req.(*RepayIntradayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankOperationsService_RequestDefund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestDefundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankOperationsServiceServer).RequestDefund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankOperationsService_RequestDefund_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankOperationsServiceServer).RequestDefund(ctx, req.(*RequestDefundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankOperationsService_ApproveDefund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveDefundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankOperationsServiceServer).ApproveDefund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankOperationsService_ApproveDefund_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankOperationsServiceServer).ApproveDefund(ctx, req.(*ApproveDefundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BankOperationsService_ServiceDesc is the grpc.ServiceDesc for BankOperationsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BankOperationsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.payments.v1.BankOperationsService",
	HandlerType: (*BankOperationsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListBankPayments",
			Handler:    _BankOperationsService_ListBankPayments_Handler,
		},
		{
			MethodName: "GetBankPayment",
			Handler:    _BankOperationsService_GetBankPayment_Handler,
		},
		{
			MethodName: "ListHolds",
			Handler:    _BankOperationsService_ListHolds_Handler,
		},
		{
			MethodName: "ReleaseHold",
			Handler:    _BankOperationsService_ReleaseHold_Handler,
		},
		{
			MethodName: "BlockHold",
			Handler:    _BankOperationsService_BlockHold_Handler,
		},
		{
			MethodName: "RejectHold",
			Handler:    _BankOperationsService_RejectHold_Handler,
		},
		{
			MethodName: "GetLiquidity",
			Handler:    _BankOperationsService_GetLiquidity_Handler,
		},
		{
			MethodName: "FundSettlement",
			Handler:    _BankOperationsService_FundSettlement_Handler,
		},
		{
			MethodName: "DrawIntraday",
			Handler:    _BankOperationsService_DrawIntraday_Handler,
		},
		{
			MethodName: "RepayIntraday",
			Handler:    _BankOperationsService_RepayIntraday_Handler,
		},
		{
			MethodName: "RequestDefund",
			Handler:    _BankOperationsService_RequestDefund_Handler,
		},
		{
			MethodName: "ApproveDefund",
			Handler:    _BankOperationsService_ApproveDefund_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/payments/v1/operations.proto",
}
