// Code generated by ent, DO NOT EDIT.

package nettingcycle

import (
	"reserve-interbank-settlement/services/payments-svc/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldContainsFold(FieldID, id))
}

// CycleRef applies equality check predicate on the "cycle_ref" field. It's identical to CycleRefEQ.
func CycleRef(v string) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldEQ(FieldCycleRef, v))
}

// At applies equality check predicate on the "at" field. It's identical to AtEQ.
func At(v time.Time) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldEQ(FieldAt, v))
}

// Trigger applies equality check predicate on the "trigger" field. It's identical to TriggerEQ.
func Trigger(v string) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldEQ(FieldTrigger, v))
}

// Discharged applies equality check predicate on the "discharged" field. It's identical to DischargedEQ.
func Discharged(v int) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldEQ(FieldDischarged, v))
}

// Deferred applies equality check predicate on the "deferred" field. It's identical to DeferredEQ.
func Deferred(v int) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldEQ(FieldDeferred, v))
}

// Gross applies equality check predicate on the "gross" field. It's identical to GrossEQ.
func Gross(v int64) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldEQ(FieldGross, v))
}

// Net applies equality check predicate on the "net" field. It's identical to NetEQ.
func Net(v int64) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldEQ(FieldNet, v))
}

// CycleRefEQ applies the EQ predicate on the "cycle_ref" field.
func CycleRefEQ(v string) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldEQ(FieldCycleRef, v))
}

// CycleRefNEQ applies the NEQ predicate on the "cycle_ref" field.
func CycleRefNEQ(v string) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldNEQ(FieldCycleRef, v))
}

// CycleRefIn applies the In predicate on the "cycle_ref" field.
func CycleRefIn(vs ...string) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldIn(FieldCycleRef, vs...))
}

// CycleRefNotIn applies the NotIn predicate on the "cycle_ref" field.
func CycleRefNotIn(vs ...string) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldNotIn(FieldCycleRef, vs...))
}

// CycleRefGT applies the GT predicate on the "cycle_ref" field.
func CycleRefGT(v string) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldGT(FieldCycleRef, v))
}

// CycleRefGTE applies the GTE predicate on the "cycle_ref" field.
func CycleRefGTE(v string) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldGTE(FieldCycleRef, v))
}

// CycleRefLT applies the LT predicate on the "cycle_ref" field.
func CycleRefLT(v string) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldLT(FieldCycleRef, v))
}

// CycleRefLTE applies the LTE predicate on the "cycle_ref" field.
func CycleRefLTE(v string) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldLTE(FieldCycleRef, v))
}

// CycleRefContains applies the Contains predicate on the "cycle_ref" field.
func CycleRefContains(v string) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldContains(FieldCycleRef, v))
}

// CycleRefHasPrefix applies the HasPrefix predicate on the "cycle_ref" field.
func CycleRefHasPrefix(v string) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldHasPrefix(FieldCycleRef, v))
}

// CycleRefHasSuffix applies the HasSuffix predicate on the "cycle_ref" field.
func CycleRefHasSuffix(v string) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldHasSuffix(FieldCycleRef, v))
}

// CycleRefEqualFold applies the EqualFold predicate on the "cycle_ref" field.
func CycleRefEqualFold(v string) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldEqualFold(FieldCycleRef, v))
}

// CycleRefContainsFold applies the ContainsFold predicate on the "cycle_ref" field.
func CycleRefContainsFold(v string) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldContainsFold(FieldCycleRef, v))
}

// AtEQ applies the EQ predicate on the "at" field.
func AtEQ(v time.Time) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldEQ(FieldAt, v))
}

// AtNEQ applies the NEQ predicate on the "at" field.
func AtNEQ(v time.Time) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldNEQ(FieldAt, v))
}

// AtIn applies the In predicate on the "at" field.
func AtIn(vs ...time.Time) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldIn(FieldAt, vs...))
}

// AtNotIn applies the NotIn predicate on the "at" field.
func AtNotIn(vs ...time.Time) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldNotIn(FieldAt, vs...))
}

// AtGT applies the GT predicate on the "at" field.
func AtGT(v time.Time) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldGT(FieldAt, v))
}

// AtGTE applies the GTE predicate on the "at" field.
func AtGTE(v time.Time) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldGTE(FieldAt, v))
}

// AtLT applies the LT predicate on the "at" field.
func AtLT(v time.Time) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldLT(FieldAt, v))
}

// AtLTE applies the LTE predicate on the "at" field.
func AtLTE(v time.Time) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldLTE(FieldAt, v))
}

// TriggerEQ applies the EQ predicate on the "trigger" field.
func TriggerEQ(v string) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldEQ(FieldTrigger, v))
}

// TriggerNEQ applies the NEQ predicate on the "trigger" field.
func TriggerNEQ(v string) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldNEQ(FieldTrigger, v))
}

// TriggerIn applies the In predicate on the "trigger" field.
func TriggerIn(vs ...string) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldIn(FieldTrigger, vs...))
}

// TriggerNotIn applies the NotIn predicate on the "trigger" field.
func TriggerNotIn(vs ...string) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldNotIn(FieldTrigger, vs...))
}

// TriggerGT applies the GT predicate on the "trigger" field.
func TriggerGT(v string) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldGT(FieldTrigger, v))
}

// TriggerGTE applies the GTE predicate on the "trigger" field.
func TriggerGTE(v string) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldGTE(FieldTrigger, v))
}

// TriggerLT applies the LT predicate on the "trigger" field.
func TriggerLT(v string) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldLT(FieldTrigger, v))
}

// TriggerLTE applies the LTE predicate on the "trigger" field.
func TriggerLTE(v string) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldLTE(FieldTrigger, v))
}

// TriggerContains applies the Contains predicate on the "trigger" field.
func TriggerContains(v string) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldContains(FieldTrigger, v))
}

// TriggerHasPrefix applies the HasPrefix predicate on the "trigger" field.
func TriggerHasPrefix(v string) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldHasPrefix(FieldTrigger, v))
}

// TriggerHasSuffix applies the HasSuffix predicate on the "trigger" field.
func TriggerHasSuffix(v string) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldHasSuffix(FieldTrigger, v))
}

// TriggerEqualFold applies the EqualFold predicate on the "trigger" field.
func TriggerEqualFold(v string) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldEqualFold(FieldTrigger, v))
}

// TriggerContainsFold applies the ContainsFold predicate on the "trigger" field.
func TriggerContainsFold(v string) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldContainsFold(FieldTrigger, v))
}

// DischargedEQ applies the EQ predicate on the "discharged" field.
func DischargedEQ(v int) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldEQ(FieldDischarged, v))
}

// DischargedNEQ applies the NEQ predicate on the "discharged" field.
func DischargedNEQ(v int) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldNEQ(FieldDischarged, v))
}

// DischargedIn applies the In predicate on the "discharged" field.
func DischargedIn(vs ...int) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldIn(FieldDischarged, vs...))
}

// DischargedNotIn applies the NotIn predicate on the "discharged" field.
func DischargedNotIn(vs ...int) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldNotIn(FieldDischarged, vs...))
}

// DischargedGT applies the GT predicate on the "discharged" field.
func DischargedGT(v int) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldGT(FieldDischarged, v))
}

// DischargedGTE applies the GTE predicate on the "discharged" field.
func DischargedGTE(v int) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldGTE(FieldDischarged, v))
}

// DischargedLT applies the LT predicate on the "discharged" field.
func DischargedLT(v int) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldLT(FieldDischarged, v))
}

// DischargedLTE applies the LTE predicate on the "discharged" field.
func DischargedLTE(v int) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldLTE(FieldDischarged, v))
}

// DeferredEQ applies the EQ predicate on the "deferred" field.
func DeferredEQ(v int) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldEQ(FieldDeferred, v))
}

// DeferredNEQ applies the NEQ predicate on the "deferred" field.
func DeferredNEQ(v int) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldNEQ(FieldDeferred, v))
}

// DeferredIn applies the In predicate on the "deferred" field.
func DeferredIn(vs ...int) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldIn(FieldDeferred, vs...))
}

// DeferredNotIn applies the NotIn predicate on the "deferred" field.
func DeferredNotIn(vs ...int) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldNotIn(FieldDeferred, vs...))
}

// DeferredGT applies the GT predicate on the "deferred" field.
func DeferredGT(v int) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldGT(FieldDeferred, v))
}

// DeferredGTE applies the GTE predicate on the "deferred" field.
func DeferredGTE(v int) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldGTE(FieldDeferred, v))
}

// DeferredLT applies the LT predicate on the "deferred" field.
func DeferredLT(v int) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldLT(FieldDeferred, v))
}

// DeferredLTE applies the LTE predicate on the "deferred" field.
func DeferredLTE(v int) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldLTE(FieldDeferred, v))
}

// GrossEQ applies the EQ predicate on the "gross" field.
func GrossEQ(v int64) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldEQ(FieldGross, v))
}

// GrossNEQ applies the NEQ predicate on the "gross" field.
func GrossNEQ(v int64) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldNEQ(FieldGross, v))
}

// GrossIn applies the In predicate on the "gross" field.
func GrossIn(vs ...int64) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldIn(FieldGross, vs...))
}

// GrossNotIn applies the NotIn predicate on the "gross" field.
func GrossNotIn(vs ...int64) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldNotIn(FieldGross, vs...))
}

// GrossGT applies the GT predicate on the "gross" field.
func GrossGT(v int64) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldGT(FieldGross, v))
}

// GrossGTE applies the GTE predicate on the "gross" field.
func GrossGTE(v int64) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldGTE(FieldGross, v))
}

// GrossLT applies the LT predicate on the "gross" field.
func GrossLT(v int64) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldLT(FieldGross, v))
}

// GrossLTE applies the LTE predicate on the "gross" field.
func GrossLTE(v int64) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldLTE(FieldGross, v))
}

// NetEQ applies the EQ predicate on the "net" field.
func NetEQ(v int64) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldEQ(FieldNet, v))
}

// NetNEQ applies the NEQ predicate on the "net" field.
func NetNEQ(v int64) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldNEQ(FieldNet, v))
}

// NetIn applies the In predicate on the "net" field.
func NetIn(vs ...int64) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldIn(FieldNet, vs...))
}

// NetNotIn applies the NotIn predicate on the "net" field.
func NetNotIn(vs ...int64) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldNotIn(FieldNet, vs...))
}

// NetGT applies the GT predicate on the "net" field.
func NetGT(v int64) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldGT(FieldNet, v))
}

// NetGTE applies the GTE predicate on the "net" field.
func NetGTE(v int64) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldGTE(FieldNet, v))
}

// NetLT applies the LT predicate on the "net" field.
func NetLT(v int64) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldLT(FieldNet, v))
}

// NetLTE applies the LTE predicate on the "net" field.
func NetLTE(v int64) predicate.NettingCycle {
	return predicate.NettingCycle(sql.FieldLTE(FieldNet, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.NettingCycle) predicate.NettingCycle {
	return predicate.NettingCycle(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.NettingCycle) predicate.NettingCycle {
	return predicate.NettingCycle(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.NettingCycle) predicate.NettingCycle {
	return predicate.NettingCycle(sql.NotPredicates(p))
}
